### ISSUE TITLE
cant change value (color and alpha) in color picker

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#8421] opened 2016-07-02 23:23 UTC
![color-picker](https://cloud.githubusercontent.com/assets/1214201/16542922/accf9d1a-40bc-11e6-8851-eba67d4d65d3.gif)

**Comment by saleiva** [comment] 2016-07-02 23:25
dupe of https://github.com/CartoDB/cartodb/issues/8363

**Closed by saleiva** 2016-07-02 23:25 UTC
