### ISSUE TITLE
302 error downloading csv source

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#2815] opened 2015-03-18 09:35 UTC
Trace: https://cartodb.com/superadmin/users/58607/data_imports/be0ece69-b82b-48b4-9617-006f69a48fa8

cc @saleiva

**Comment by Kartones** [comment] 2015-03-18 15:50
Seems the issue is [gnutls](https://github.com/taf2/curb/issues/217).

Upgrading my dev env to use `libcurl-openssl` everything works fine. Else I get TSL errors reading the certificate

**Comment by azamorano** [comment] 2015-04-21 10:42
Fixed installing libcurl4-openssl-dev instead.

**Closed by azamorano** 2015-04-21 10:42 UTC
Labels: 0 - Backlog, 2 - Working, bug, importer
