### ISSUE TITLE
Cannot duplicate dataset if the owner has hyphens(-) in the name

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#7466] opened 2016-05-23 14:22 UTC
When duplicating a shared dataset from an owner with hyphens in the name, an error 8003 occurs. Log:
```
"2016-05-23 14:05:17 UTC: Running on server cartodb with PID: 4577
2016-05-23 14:05:17 UTC: from_table()
2016-05-23 14:05:17 UTC: import_from_query()
2016-05-23 14:05:18 UTC: Going to set merge error with code 8003
2016-05-23 14:05:18 UTC: Additional error info: PG::Error: ERROR:  syntax error at or near \"-\"
LINE 1: ...TE TABLE untitled_table_copy AS SELECT * FROM demo-admin.unt...
                                                             ^
2016-05-23 14:05:18 UTC: After dispatch\n2016-05-23 14:05:18 UTC: ERROR!"
```

Seems like we need to escape the query.

cc @rafatower

**Comment by iriberri** [comment] 2016-05-24 13:53
@javitonino this is only failing to me when trying to duplicate the dataset from the dashboard. Did you reproduce it in other scenario?

**Comment by javitonino** [comment] 2016-05-24 13:55
No, just tested it from the dashboard. I also tried sharing the dataset and duplicating from another user's dashboard an also fails, but that should be the same case.

**Comment by iriberri** [comment] 2016-05-24 14:28
I think this could be in the scope of the Editor. In other scenarios such as duplicating from table view or creating table from query (everything with a table shared from a user with a hyphen in the name) the Editor seems to be quoting appropriately the user schema in the table name.

Internally, the imports controller receives strings for `sql` or `table_copy`, which are the fields that we will use.

I tried to follow the flow that the code follows when you click on "Duplicate dataset" from the dashboard for a dataset (`foo_bar_copy`) that the user  `zenitram-cloud` has shared with me in the organization.

I see that this [creates an import (CreateImport)](https://github.com/CartoDB/cartodb/blob/ebfb0e62bfdb6bd941408b4d2f0826b3195318fb/lib/assets/javascripts/cartodb/common/background_polling/models/import_model.js#L33) and the `table_copy` value is copied [here](https://github.com/CartoDB/cartodb/blob/ebfb0e62bfdb6bd941408b4d2f0826b3195318fb/lib/assets/javascripts/cartodb/common/background_polling/models/import_model.js#L92), as:

```js
if (type === "duplication") {
      _.extend(d, {
        table_name: data.table_name,
        table_copy: data.value
      });
    }
```

I put a breakpoint and I'm seeing that data is:

`data = Object {type: "duplication", value: "zenitram-cloud.foo_bar_copy", interval: 0, privacy: "", prog...`

so the problem is already existent in `value`, as ` "zenitram-cloud.foo_bar_copy"` does not have the schema quoted to allow the hyphens.

**Comment by jgoizueta** [comment] 2016-05-24 14:36
FYI, if this have to be fixed in the front end, this could be handy: 
https://github.com/CartoDB/Windshaft-cartodb/blob/master/lib/cartodb/utils/table_name_parser.js

**Comment by javitonino** [comment] 2016-05-24 14:37
Oh, sorry @iriberri. I saw an error in the import logs and I was too quick to think it belonged to the importer. I will check how the importer job is generated. Thanks for the detailed explanation!

**Comment by iriberri** [comment] 2016-05-24 14:40
@javitonino no problem at all! I didn't know very well that connection between Editor/Imports controller, so at least I know now :-)

**Closed** 2016-05-25 07:52 UTC
