### ISSUE TITLE
Annotations are deleted when editing text with Delete key (Similar to #2100)

### ISSUE THREAD

**Issue by cshirky** [CartoDB/cartodb#2853] opened 2015-03-21 16:02 UTC
STR:

1. Create a Visualization
2. Add Element -> Add Annotation Item
3. Triple-click on "I'm an **annotation overlay**" to select all text
4. Attempt to delete text with Delete key

Expected behavior: Text in annotation box is deleted, cursor is ready for input
Actual behavior: Annotation box is deleted

Tested in Chrome and Safari

ADDENDUM: This does look like #2100, sorry for the dupe.

**Comment by saleiva** [comment] 2015-03-21 18:40
#hotfix !

**Comment by javisantana** [comment] 2015-03-21 22:05
I think this is the same than #2100, we had some problems reproducing it and happens the same with this.

Which frontend version are you running ? you can see it in the developer console

**Comment by cshirky** [comment] 2015-03-21 23:37
cartodb.js 3.12.12
tracker.js:10 cartodbui v3.7.31 
sha1: 8bf0ddf752c4ad81554bb9dde1d9f2677c753a8f

On a Maf, 10.10.2

**Comment by javisantana** [comment] 2015-03-22 09:22
I'm not able to reproduce it with those steps, there should be another problem/extra step that makes this fail

**Comment by cshirky** [comment] 2015-03-22 09:36
Here's a movie of me doing it:
https://www.dropbox.com/s/5n7tpvgri0z80rb/Annotation_Delete.mov?dl=0

No extra steps other than those I documented. Add, triple-click, Delete key

Tested with Chrome and Safari on Mac

**Comment by alonsogarciapablo** [comment] 2015-03-22 13:50
I think this [is something we are doing on purpose](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/overlays/annotation.js#L141-L150): after a keypress, if there's no text left, we close the annotation.

**Comment by cshirky** [comment] 2015-03-22 14:41
Interesting. I think the user-expected behavior would be "Close an empty box only if the cursor/focus is elsewhere."

**Comment by alonsogarciapablo** [comment] 2015-03-23 08:47
@cshirky I agree with you. The use case you shared in the your video is totally realistic, users will want to delete all text to start typing again. @saleiva @javisantana what do you think?

**Comment by saleiva** [comment] 2015-03-23 08:55
I'm with @cshirky

**Comment by alonsogarciapablo** [comment] 2015-03-23 08:58
@javierarce this is assigned to you, but I can take care of it if you want.

**Comment by javierarce** [comment] 2015-03-23 09:24
Don't worry, @alonsogarciapablo, I'm back from holidays and I can take care of this. Thanks!

**Comment by saleiva** [comment] 2015-04-01 15:43
so what?

**Comment by javierarce** [comment] 2015-04-01 16:19
I'm pushing the PR. It will be released on Monday.

**Closed** 2015-04-08 08:20 UTC
Labels: 3 - Done
