### ISSUE TITLE
erratic behavior for natural earth data imports

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#2896] opened 2015-03-24 21:03 UTC
Natural Earth Data have unusual URL formats:
http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_populated_places.zip

Importing these files gives erratic behavior:
![screen shot 2015-03-24 at 16 54 10](https://cloud.githubusercontent.com/assets/1041056/6812635/7e3de1fe-d246-11e4-9ebd-2d513c87e302.png)

The schema of the first one looks like this:
![screen shot 2015-03-24 at 16 54 29](https://cloud.githubusercontent.com/assets/1041056/6812667/aaa5c3ec-d246-11e4-81e6-8d9e76658362.png)

The second one imported normally.

My account name is eschbacher if you want to inspect the import logs.

@andrewxhill observed similar behavior with `wget`.

`curl -O http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_populated_places.zip` doesn't work for me

**Comment by zenitraM** [comment] 2015-03-25 12:45
Duplicate of #2858, go there for more details :)

**Closed by zenitraM** 2015-03-25 12:45 UTC

**Comment by ohasselblad** [comment] 2015-03-25 12:48
:+1:
