### ISSUE TITLE
When opening a map from the delete warning modal in another tab the window gets closed.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2877] opened 2015-03-24 11:38 UTC

**Comment by xavijam** [comment] 2015-04-06 13:05
This is not happening anymore, at least what I've tried. It is opened in a new tab by default.

**Comment by xavijam** [comment] 2015-04-06 15:01
Closing since I can't reproduce it, if it happens again, new one, ok? :)

**Closed by xavijam** 2015-04-06 15:01 UTC
Labels: New dashboard
