### ISSUE TITLE
Description text still displays on map even after it has been deleted from the "metadata" section

### ISSUE THREAD

**Issue by Hayleyr** [CartoDB/cartodb#3941] opened 2015-06-05 19:42 UTC
In map view. Description only disappeared when the element was turned off in the options button and then turned back on.

**Comment by Hayleyr** [comment] 2015-06-05 19:57
Sorry, let me elaborate further. If I add a description in the metadata, turn on the description element and then delete the metadata description it doesn't go away until i turn it off from the "options" button. Shouldn't it disappear immediately upon deletion?

**Comment by ztephm** [comment] 2015-06-30 20:44
Hi, happening again for s/b 5560646 + slightly different problem also

Expected behavior: When user clicks on "Edit metadata" in Map View and changes existing description, the description will update in embedded iframe map.

I recreated here if u need: https://team.cartodb.com/u/stephaniemongon/viz/0deb4166-1f40-11e5-a147-0e9d821ea90d/public_map

To recreate:
1. Click "Edit metadata" in Map View and enter a description
2. Click Options button & toggle on Fixed description
3. Leave it toggled on & click "Edit metadata" again, enter new description & click "Save Settings"

Embedded map doesn't show updated settings even with page refreshed/cache cleared.

Console errors:
![screen shot 2015-06-30 at 4 36 58 pm](https://cloud.githubusercontent.com/assets/1779444/8441458/51d3d202-1f46-11e5-82e1-e9feed68653a.png)

User's problem is she's toggling on description in Editor's Options menu, but description isn't showing up in Editor or in embedded map. I can't recreate but ref s/b 5560646 for screenshots.

**Comment by ztephm** [comment] 2015-07-01 20:01
ref #4258

**Comment by javierarce** [comment] 2015-08-03 12:53
Hi, @ztephm and @auremoser: this should be fixed now, sorry for the delay taking care of this.

**Closed by javierarce** 2015-08-03 12:53 UTC

**Comment by auremoser** [comment] 2015-08-03 14:19
oh yay! this was my favorite issue before because of the long gif embed! thank you @javierarce !

**Comment by ztephm** [comment] 2015-08-03 22:22
No prob, thanks for taking care of that @javierarce ! I will let the Support Bee users know.
