### ISSUE TITLE
"Close" window button is justified left in Safari

### ISSUE THREAD

**Issue by auremoser** [CartoDB/cartodb#4968] opened 2015-08-10 15:24 UTC
## Current Result

Nit picky, but the "X" in the "close window" button doesn't center in Safari. 

## Expected Result

Centered "x"es like in Chrome.

## Screenshots

Mostly in the data view, but the problem federates across modals:
![data](https://cloud.githubusercontent.com/assets/1559703/9175193/4d8c815e-3f52-11e5-8147-a0f68cf24414.png)

![metadata](https://cloud.githubusercontent.com/assets/1559703/9175196/5038de66-3f52-11e5-9630-efc589821b91.png)

![public](https://cloud.githubusercontent.com/assets/1559703/9175200/540ecbd6-3f52-11e5-98fc-78edf7389fee.png)

**Comment by viddo** [comment] 2015-08-10 15:28
duplicate of #4960, should be fixed in a few minutes since the fix is not deployed quite yet (ETA ~5 min)

**Comment by auremoser** [comment] 2015-08-10 15:29
whoohoo! so fast!

**Closed by viddo** 2015-08-10 15:28 UTC
Labels: bug

**Comment by viddo** [comment] 2015-08-10 15:34
Works on my machine™/safari now, feel free to reopen if it still happens (don't forget to reload your browser before testing though ;))
