### ISSUE TITLE
Creating a map from a dataset redirects you to a wrong URL

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4294] opened 2015-07-03 13:14 UTC
it works, until you refresh the browser. It looks like is adding the table_name instead of 'map' and the end of the URL.

**Comment by Kartones** [comment] 2015-07-06 10:34
@saleiva as I told you on friday, this was a really scarce description and I doubted was the proper way to reprodce it...

My attempt:
```
From an existing "untitled_table" table, map view (after drawing a polygon to see some data):
https://team.cartodb.com/u/kartones/tables/untitled_table/map

create map -> "ok, create map"

I get redirected to https://team.cartodb.com/u/kartones/viz/e1d12fb2-23c9-11e5-b8a8-0e018d66dc29/map

I refresh, and still see https://team.cartodb.com/u/kartones/viz/e1d12fb2-23c9-11e5-b8a8-0e018d66dc29/map

----------
From the table view:
https://team.cartodb.com/u/kartones/tables/untitled_table

visualize -> "ok, create map"

https://team.cartodb.com/u/kartones/viz/60316232-23ca-11e5-9e58-0e9d821ea90d/table

Refresh, and still get https://team.cartodb.com/u/kartones/viz/60316232-23ca-11e5-9e58-0e9d821ea90d/table
```

So, please add detailed steps, as I cannot reproduce the bug

**Comment by iriberri** [comment] 2015-07-06 10:46
I saw yesterday that when you add a new layer to a table with the new modals, the name of the map is being generated as the name of the created table (but the URL worked correctly for me, with the appropriate ID of the viz instead of the table name)

**Comment by saleiva** [comment] 2015-07-06 11:00
yep, it's what @iriberri says. You need to have the new_modals feature flag activated

**Comment by saleiva** [comment] 2015-07-06 11:00
cc @viddo

**Comment by Kartones** [comment] 2015-07-06 11:02
Then is not a backend issue, no? I'm going to check and if with current modals it works ok I'm afraid it is a frontend issue.

**Comment by Kartones** [comment] 2015-07-06 11:08
As I expected, with current modals, from Dataset view, I click add layer, "ok, create map" and it correctly creates a map, goes to the proper url, works as expected even if I reload, etc.

So this has to be something of the new modals...

Also, as a side note, is this behaviour intended, to have exactly the same layer name if adding multiple times the same table instead of some `_1`, `_2`, etc. suffix?
![image](https://cloud.githubusercontent.com/assets/2085449/8520999/fdda5ec0-23df-11e5-9cbc-9f8bdb6f84a0.png)

**Comment by viddo** [comment] 2015-07-07 08:43
I have new modals enabled and I can't reproduce this error (neither locally or in production). So far I've tried:
- the steps kartones provided above
- duplicate a dataset through both "visualize" and "add layer"
- tried both from an existing dataset (with data) and from a new empty dataset

Since I can't reproduce and lack information on what's wrong, I'll close this issue for now. If it still happens to any of you please provide more info (steps-to-reproduce, more context-info etc.) so we can pinpoint where the issue is located.

**Closed by viddo** 2015-07-07 08:43 UTC
Labels: bug
