### ISSUE TITLE
Master role inherits from regular api key roles 

### ISSUE THREAD

**Issue by enekid** [CartoDB/cartodb#13529] opened 2018-02-08 17:40 UTC
When a regular api key user creates an analysis, the master role must be able to access the created tables. The proposed solution is that the master role inherits from the regular api key role:

`GRANT regular_role_XXX to master_role`

**Comment by javitonino** [comment] 2018-02-08 17:55
Uhm, I'm worried about this approach, let's discuss.

First, as it is now, `regular` api key roles cannot create tables. If we want them to be able to create analysis tables, they will also be able to create regular tables.

The mixed ownership (some objects owned by the key role) is also problematic. What would happen is we delete the api key? We would have to reassign ownership of all objects, or the role deletion would failed (a worse alternative is to delete the objects 🔥).

I'm also worried about details of things like cartodbfication, which I think would create the associated triggers of a table with the role of the master, so the table would have different ownership than the triggers. This feels like a bad idea, although I cannot point out at specific problems at the moment.

Maybe we should always create the analysis tables using the master role instead? That would fix all my issues, but I'm willing to bet it would make life harder for Windshaft. 🤔

**Comment by dgaubert** [comment] 2018-02-09 14:58
> Maybe we should always create the analysis tables using the master role instead? That would fix all my issues, but I'm willing to bet it would make life harder for Windshaft.

Before moving forward to find a solution, let me shed some light on what's going on when a user creates a map with analyses in Maps API. Right now, only the `user role (master)` is able to create node analysis. Within the workflow of creating a map with one analysis we have:

 1. If one node analysis requires being cached a new table is created and populated.
 2. Performs some meta-operations, to update `cdb_analysis_catalog` and/or read from `cdb_tablemetadata`.
 3. When creating a map that reads from that cached analysis table, Maps API performs some operations to calculate surrogate keys and affected tables. These operations are performed with `user role (master)`

If we want a `regular api-key role` will be able to create a map with analyses we need to grant permissions to read/write on `cdb_analysis_catalog` and read on `cdb_tablemetadata`. Once a cache table is created with a `regular api-key role` the ownership belongs to that role. So, when we create a map that uses the previous analysis the operations described in point `3` will fail because master role doesn't have perms on that table. That's why @enekid opened this ticket. ;)

If we decide this issue should be fixed in Maps API side we need to tell to Analysis API to create the analysis cache table with `user role (master)` and then grant perms to the actual role that creates the analysis (`regular api-key role`). That means, we are coupling Analysis API to Auth API and it sounds really weird to me.

Thoughts?

**Comment by javitonino** [comment] 2018-02-09 15:53
🤔 I think that we have a similar situation right now, don't know if the situation is the same. But if a map has an analysis that depends on a widget, if any public viewer (using no api key) clicks a widget, an instantiation request is made using no api key, but the user db role is used to create the analysis cache tables. 

So there must be some way inside Windshaft already to use a different role than what is specified by the request. I'm not saying this is the way to go, but this is how we solved this in the past.

I think we  need to keep something like this, because we still need analysis tables to be able to be rendered without api key, but without making the analysis tables accessible to the publicuser (public maps with private data). In that sense, it makes some sense to me that the `regular` keys behave similar to the `default` one (use a different connection for analysis).

In your proposal: if you want to make the map created with the `regular` api key public (and render it without providing an apikey). If the user forces the analysis to rerun, how would the tiler know which role to use? It cannot use the public user (which is the one that matches the provided api key).

Note that this is not a problem exclusive with analysis. If we ever want to give api keys rights to `CREATE TABLE` we would have the same issues I highlighted in my previous comment, derived from tables owned by different roles. So if this is something we see us doing, we should think about how to solve/workaround those.

The idea to grant the keys role to master is a good solution, but it doesn't cover all cases by itself (e.g: api key deletion and reassigning ownership).

**Comment by javitonino** [comment] 2018-02-12 08:58
Also, another concern, the analysis API needs `CREATE TABLE` permissions in order to work. So if we go for the approach of giving the needed rights to the API Key role, we would end up with all `regular` api keys being able to create tables in the user schema (which I think is something we don't want).

Some ideas that might work:
- Create different roles for SQL API and Maps API. They would have the same rights, except the Maps API one will have access to the analysis cache/catalog, etc.
- We could look into using `SET ROLE` for the Api Key user to escalate privileges. But we would have to restrict its usage somehow in SQL Api.
- We could create some SECURITY DEFINER functions to manage analysis tables (probably inside the extension). This would allow to safely manage analysis tables without granting rights on it to any user.

**Comment by dgaubert** [comment] 2018-02-12 11:29
> I think that we have a similar situation right now, don't know if the situation is the same.

Yep, you are right. We have a similar situation with public viewers which is solved through named maps™️. When a public viewer clicks a widget, a **named map** instantiation request is made w/o `api_key`. Behind the scenes, Maps API uses the `user role (master)` to perform the analysis work. Having in mind that one of the side effects of releasing Auth API is to deprecate named maps (we are not totally sure about that, but it's there), so I'm afraid that we don't want to switch to `master` when an analysis is involved in map instantiation with regular `api-keys`.  

On the other hand, we might try to solve a problem from the technical point of view or we might try to solve it by designing a totally different approach. It would be:

  - In the future, Analysis API will have its own entity (by creating a totally new service ¿¿ ... ??). It might a user can perform analysis w/o visualizing them with maps.
  - A user will want to create a regular `api-key` to allow to create analysis. I'm pretty sure about that ;)
  - Currently, we grant access to different APIs (Maps or SQL) by reading the property `grants_maps` or `grants_sql`.

I propose to add a new field in  `api-key`'s structure to indicate that a regular `api-key` can create analysis (cached tables) and also it will have access to the needed metadata tables (`grants_analysis`). In Maps API we can check if a regular `api-key` can create an analysis or not whether a map instantiation involves analyses.

By default `grants_analysis` will be `false` so we can add it later as we don't want regular `api-key` to create analysis yet in this first stage. For `master` it will be `true` by default.

Thoughts??

**Comment by dgaubert** [comment] 2018-02-12 12:36
After having an off-line conversation:

  - We aren't going to implement anything regarding `regular api-key` and analysis until we have a clearer version of Analysis API.
  - If for some reason we have to implement a `workaround/solution/hack`, our best option is:  `create SECURITY DEFINER functions to manage analysis tables (probably inside the extension)`.
  - We need to keep user metadata `map_key` property when migrating to `api-key`s. We need them to provide a fallback mechanism and support named maps.

Anything else?

**Comment by javitonino** [comment] 2018-02-12 13:21
I think this covers everything. Since we are not going to implement anything (just keep using master for named maps), closing this!

**Closed by javitonino** 2018-02-12 13:21 UTC
Labels: Backend, blocked
