### ISSUE TITLE
Fix thumbnails zoom 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2462] opened 2015-02-23 21:12 UTC
Make zoom +1 / +2 on actual ones.

**Comment by javisantana** [comment] 2015-02-23 21:24
I'd use the zoom//center instead of the bbox for small thumbnails in order to avoid lower zoom levels

**Comment by javisantana** [comment] 2015-02-23 21:31
maybe adding a config to cdb.Image in order to not use bbox from the vizjson file? like

```
cartodb.Image(v.url, { override_bbox: true }).size(250, 250)
```

what do you think @javierarce

**Comment by javierarce** [comment] 2015-02-24 10:15
Yeah, that was the approach I was thinking of.

BTW, @saleiva, this ticket is a duplicate of https://github.com/CartoDB/cartodb/issues/2348.

**Comment by javierarce** [comment] 2015-02-24 15:20
*Before*:

![screen shot 2015-02-24 at 16 19 54](https://cloud.githubusercontent.com/assets/4933/6352176/08522af6-bc41-11e4-95aa-79d23ba8f1a5.png)

*After* (zoom +2):

![screen shot 2015-02-24 at 16 19 41](https://cloud.githubusercontent.com/assets/4933/6352177/085cb106-bc41-11e4-9315-5f7cb15dbc4e.png)

**Comment by javierarce** [comment] 2015-02-24 17:20
I've just created a ticket to apply the same solution in the new public dashboard.

**Comment by saleiva** [comment] 2015-02-24 18:12
Can we deploy so we try first in the private one?

**Comment by javierarce** [comment] 2015-02-24 18:27
Sure, let's do it tomorrow morning. We could use the actual zoom for the visualizations of the public dashboard and the tweaked one (zoom +2) for those in the private dashboard.

**Closed** 2015-02-26 10:02 UTC
Labels: 2 - Working, New dashboard
