### ISSUE TITLE
Missing elements on 'Connect Dataset' menu in Firefox

### ISSUE THREAD

**Issue by mapninja** [CartoDB/cartodb#6434] opened 2016-01-20 19:27 UTC
Seems like a Firefox issue, on several versions of Firefox, both OSX and Win. Here is a link to a screenshot of the page after selecting a CSV for upload. The button is working fine in Chrome. 

[screenshot](https://www.dropbox.com/s/h5g8zbgih2spdu9/Screenshot%202016-01-20%2011.13.05.png?dl=0)

**Comment by ernesmb** [comment] 2016-01-21 11:20
## Description
The _Connect Dataset_ button and the _Let CartoDB automatically guess..._ checkbox do not appear when trying to upload a file to import. 
Those elements seem to be displaced to the bottom part of the page, where they are not reachable.
Also note that the closing 'X' button is displaced as well.

## Context
The issue reproduces with Firefox versions earlier than `38.5.2 ESR`

## Screenshot 
![screenshot 2016-01-20 11 13 05](https://cloud.githubusercontent.com/assets/10940006/12478985/a04d0f96-c038-11e5-84c7-a072b62bdec9.png)


Please @matallo review

**Comment by xavijam** [comment] 2016-01-21 11:33
I've checked Firefox version 42 and 43 (latest ones) and seems like it appears correctly, what is your version?

<img width="1440" alt="screen shot 2016-01-21 at 12 31 53" src="https://cloud.githubusercontent.com/assets/132146/12479397/1a923e3c-c03b-11e5-8ecc-d0e0415454a0.png">
<img width="1286" alt="screen shot 2016-01-21 at 12 32 26" src="https://cloud.githubusercontent.com/assets/132146/12479398/1a96a0c6-c03b-11e5-99fe-2f1da1ba51da.png">

**Comment by ernesmb** [comment] 2016-01-21 11:51
Closing since v38 is the [minimum version required](https://github.com/CartoDB/cartodb#requirements)

**Closed by ernesmb** 2016-01-21 11:51 UTC
