### ISSUE TITLE
Allowed to add a point outside the bounding box

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#11898] opened 2017-03-31 09:10 UTC
### Context
Right now I'm able to place a point outside the bounding box on some explicit zones:

### Steps to Reproduce

1. Create an empty map
2. Enter into the empty layer
3. Add a point
4. Drag the point from the center to the bottom of the map (outside the bounding box)
5. Add the point
6. Go back, you won't be able to see the point on the map

### Current Result
![bug 1](https://cloud.githubusercontent.com/assets/596509/24544151/89d2aad4-1602-11e7-9d72-2c8e16910a40.gif)

### Expected result
When I try to add a point outside the bounding box I expect to not be able to do that

### Browser and version
Chrome 59.0

**Comment by saleiva** [comment] 2017-03-31 10:51
Whi @josecruz this is a dupe of https://github.com/CartoDB/cartodb/issues/11476

Thanks!

**Closed by saleiva** 2017-03-31 10:51 UTC
Labels: bug
