### ISSUE TITLE
When a map/dataset is shared with a group, the info in the privacy icon is empty

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5659] opened 2015-09-22 10:31 UTC
### STR:

- Being the owner of an organization.
- Create a user within that organization.
- Add that user to a group.
- Create a new map and open the share options.
- Only share with a group, choose a privacy and save.

<img width="1138" alt="screen shot 2015-09-22 at 12 28 26" src="https://cloud.githubusercontent.com/assets/132146/10016206/7fe80af2-6125-11e5-9725-11733823c3b5.png">

What to do in this case?

cc @viddo

**Comment by viddo** [comment] 2015-09-22 10:32
duplicate of #5533

**Comment by xavijam** [comment] 2015-09-22 10:32
:clap:

**Closed by viddo** 2015-09-22 10:32 UTC
Labels: bug, cdb-Groups
