### ISSUE TITLE
Latin1 Filenames defeat the Importer

### ISSUE THREAD

**Issue by pramsey** [CartoDB/cartodb#2119] opened 2015-02-06 18:02 UTC
For some versions of ruby (?) including the one running the production system, the following file will not import:  [pd308.2011.zip](https://github.com/CartoDB/cartodb/files/99827/pd308.2011.zip)

It's just a zip file with a shape file and some metadata files. The trick is, one of the files includes a filename with a LATIN1 accent (donnée). During extraction the filename is read from stderr in the unzip output and then ruby gets unhappy with it (?)

**Comment by javisantana** [comment] 2015-02-06 18:04
the problem is in this line:
```
https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/unp.rb#L174
```

FYI

```
irb(main):008:0> b = "Dictionnaire de donn\x82es.doc"
=> "Dictionnaire de donn\x82es.doc"
irb(main):009:0> b =~ /.*Cannot read.*/
ArgumentError: invalid byte sequence in UTF-8
```

**Comment by saleiva** [comment] 2015-02-08 20:07
Love the title of the issue :P

**Comment by pramsey** [comment] 2016-01-21 20:12
Uploaded [pd308.2011.zip](https://github.com/CartoDB/cartodb/files/99827/pd308.2011.zip) so it's not dependent on my dropbox folder anymore.

**Comment by iriberri** [comment] 2016-02-29 11:11
Should be fixed with: https://github.com/CartoDB/cartodb/issues/6276

**Closed** 2016-03-01 12:02 UTC
Labels: bug, Data-services, importer
