### ISSUE TITLE
several problems using subdomainless urls

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#3334] opened 2015-04-22 20:36 UTC
the setup is the following:

```
  session_domain:     'localhost.lan:3000'
  subdomainless_urls: true
```

the machine url is http://192.168.1.188:3000

- [x] when I got to http://192.168.1.188:3000/login, "192.168.1.188" appears as the user in the form. It should be empty
- [x] when I login using user "cartodb" I get redirected to http://192.168.1.188.localhost.lan:3000/user/cartodb/dashboard/ (it should be http://192.168.1.188:3000/user/cartodb/dashboard/
- [x] when I write http://192.168.1.188:3000/user/cartodb/dashboard/ this is user_data.base_url

```
"http://192.168.1.188.localhost:3000/user/cartodb"
```

We should provide access using a single IP addreess

**Comment by santisaez** [comment] 2015-04-24 10:19
@Kartones I have done some tests enabling subdomain-less URLs feature and accessing to the dashboard/editor using the domain name, instead of the IP, and seems there are some new issues.

Relevant `app_config` settings:

```ruby
session_domain: 'subdomain.example.com'
subdomainless_urls: true
account_host: '${organization}.subdomain.example.com' # see [1]
```

[1] see https://github.com/CartoDB/cartodb-onpremise/issues/226 since this could be a misconfigured setting, just for the record.

When I go to `https://${organization}.subdomain.example.com/login` I get an incorrect username **with with a dot** as suffix, something like the issue reported by @javisantana:

![login_bad](https://cloud.githubusercontent.com/assets/223956/7316891/47a79e3a-ea7b-11e4-8001-05124aac3753.png)

Also, when clicking on the "logout" link I'm redirect to the following URL `https://maps.subdomain.example.com/user/maps./maps` - in this case, "maps" is the organization name and "maps-admin" the organization admin' username.

**Comment by rafatower** [comment] 2015-04-27 16:22
> when I write http://192.168.1.188:3000/user/cartodb/dashboard/ this is user_data.base_url

@javisantana I don't get what you mean here in the description of the ticket.

**Comment by javisantana** [comment] 2015-04-27 19:11
ok, sorry, what I meant is:

- having an user called 'cartodb' and the config.yml as I pasted
- when I write this url http://192.168.1.188:3000/user/cartodb/dashboard/ the base_url sent to client side is wrong

You can check out base_url going to a dataset, open developer tools and print user_data.base_url. 

FYI base_url is the url we use to access API endpoints from client side

**Comment by rafatower** [comment] 2015-04-28 07:12
Just a quick note about the config in the ticket description: the port shouldn't be part of the `session_domain`, there are other entries `http_port` and `https_port` that should be used instead.

**Comment by rafatower** [comment] 2015-04-28 08:53
The relevant parts of the config:
```yaml
#File config/app_config.yml

  http_port: 3000      # nil|integer. HTTP port to use when building urls. Leave empty to use default (80)
  https_port: null # nil|integer. HTTPS port to use when building urls. Leave empty to use default (443)

  session_domain:     '172.17.0.1'    # note there's NO port here
  subdomainless_urls: true

  account_host:       '172.17.0.1:3000' # note there's port here
```

**Comment by rafatower** [comment] 2015-04-28 09:46
After talking with Sergio: the logout should send to the public page of the user who's just logged off, for both on-premise and the public cloud. I'll review usages of `account_host` because it shouldn't be needed in most cases, at least for on-premise.

**Comment by rafatower** [comment] 2015-04-30 10:37
What's remaining:
- [ ] Fix redirection from http://localhost.lan to login page only in domainless (reverted in 6bcae77 and 6dd8ef0a)
- [ ] Fix org user -> organization -> new user
- [ ] nginx rules to route to sql api (Santi)

**Comment by rafatower** [comment] 2015-05-04 16:35
This fixed some of the issues with URL generation:
```
cartodb_production=# insert into feature_flags values (1, 'new_public_dashboard', false);
INSERT 0 1
cartodb_production=# insert into feature_flags values (2, 'new_dashboard', false);
INSERT 0 1
cartodb_production=# insert into feature_flags values (3, 'new_public_dashboard_global', false);
INSERT 0 1
```
Related to https://github.com/CartoDB/cartodb/issues/3488

**Comment by Kartones** [comment] 2015-05-04 20:15
Oh shit, yes... we were supossed to remove all non-new-dashboard code, ifs,
etc. but it's being delayed and hurting on-premise.... so +1 to increase
priority of #3488

*Diego / Kartones  |  *Developer*  |  *CartoDB <http://www.cartodb.com>*  |
 *diego@cartodb.com

**Comment by rafatower** [comment] 2015-05-06 12:22
I'm closing this issue, if we find more stuff during regression I prefer to open a new one. Feel free to reopen if you disagree

**Closed by rafatower** 2015-05-06 12:22 UTC
Labels: 2 - Working, major-priority

**Comment by sandeepgadhwal** [comment] 2017-01-21 21:50
sir ia am getting the same error mentioned above what to do

**Comment by rafatower** [comment] 2017-01-23 08:12
@sandeepgadhwal what problem? could you please open a ticket with steps to reproduce, configuration and any logs that could be useful? thanks!
