### ISSUE TITLE
"Force all rows" in Street geocoding not being applied correctly

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5508] opened 2015-09-14 16:51 UTC
**Steps**:

1. Create a new table
2. Add three rows, with three complete addresses (like "Eloy gonzalo, 27, madrid, spain") in the description field
3. generate a cartodb_georef_column, of type boolean. Set it to false in one of the rows and leave the rest as null.
4. Geocode by street addresses, DISABLE the force all rows option. Set "description" in the first selector and geocode.
5. The request will look as follows:
![image](https://cloud.githubusercontent.com/assets/1730320/9855907/8769447c-5b11-11e5-9a74-5c2cba8aab8f.png)

Nevertheless, it seems that the cartodb_georef_status is not taking into account and it's being overwritten. Also, the "false" rows are being geocoded anyways.

**Comment by iriberri** [comment] 2015-09-14 16:57
More info: I did an extra test.

From that result, I ended up with 2 true geocoded rows, and one false (because I had left it "null"). Then,  I added a NY address in this null row, but also in a true row.

I geocoded again, disabling the forcing of all rows. The false row was geocoded, but the true one too, so I'd say everything is being geocoded all the time.

**Comment by iriberri** [comment] 2015-09-14 16:59
One more test:

I enabled the "force all rows" checkbox, and again, all rows have been geocoded.

**Comment by rafatower** [comment] 2015-09-30 08:02
> Also, the "false" rows are being geocoded anyways.
this is by design, regardless of `force_all_rows` flag.

https://github.com/CartoDB/cartodb/issues/3958

I'm therefore closing this ticket. If you have a strong opinion against, then we need to agree on new requirements

**Closed by rafatower** 2015-09-30 08:02 UTC
Labels: bug

**Comment by iriberri** [comment] 2015-09-30 08:45
Is it the expected behaviour that "true" rows are being geocoded again? :S

**Comment by rafatower** [comment] 2015-09-30 10:04
Sorry, I misunderstood the description on top..
> Set it to false in one of the rows and leave the rest as null.

if they are set to false/null then it is expected to geocode them, regardless of the value of `force_all_rows`

are you sure rows with true are geocoded again when `force_all_rows = false`?

**Comment by iriberri** [comment] 2015-09-30 10:30
My steps:

* Create a new table with an empty row
* Geocode by street addresses, it's going to fail, but it will generate the status column
* Create 4 new rows, fill the different rows with values false/null/true for the status
* Set all rows with points in the coordinates (1,1)
* Put an address in the description column. I set up the office address in all of them
* Geocode by street addresses, without forcing

All the status get converted to true, and all geometries get converted to the coordinates of the office. Even those ones that were set to true.

**Comment by rafatower** [comment] 2015-09-30 13:52
Ah. Because of the way it works, this is kind of expected because it (a) gets the results for 1 unique input row and then (b) computes the end result as a "join" of your table and what it got from (a). If you use different addresses for your experiment, that won't happen.

**Comment by iriberri** [comment] 2015-09-30 14:03
Hah :/ Thanks for clarifying! It makes sense, actually... thanks!
