### ISSUE TITLE
Removing analysis node or dragging a node outside a layer, makes the layer style unchangeable

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9116] opened 2016-07-26 13:27 UTC
This is because the aggregation method is set to NONE, instead to the default one.

Might be related to:
https://github.com/CartoDB/cartodb/issues/8827
https://github.com/CartoDB/cartodb/issues/9042

**Comment by saleiva** [comment] 2016-07-26 13:28
cc/ @javisantana

**Comment by viddo** [comment] 2016-07-28 08:51
Can't reproduce it, from what I know this should already be fixed by #9144 (#9146 might also have helped). Please reopen if still happen.

**Closed by viddo** 2016-07-28 08:51 UTC
Labels: bug
