### ISSUE TITLE
Table sync seems to not update last modified time at dashboard

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#3754] opened 2015-05-25 14:39 UTC
From the dashboard (new endpoint and frontend cache active):
![outdated_sync_1](https://cloud.githubusercontent.com/assets/2085449/7798632/6dadb9f4-02fc-11e5-9393-dcca6c65d24f.jpg)
But entering the table:
![outdated_sync_2](https://cloud.githubusercontent.com/assets/2085449/7798631/6dacaa96-02fc-11e5-9617-2771779df30f.jpg)

**Comment by juanignaciosl** [comment] 2015-05-26 11:29
Couldn't replicate. There's a missing detail: dataset update date doesn't change if synch data hasn't changed either. So, IMHO, this is not a bug.

**Comment by Kartones** [comment] 2015-05-26 11:51
do you have FE caching activated? maybe is that... @javisantana 

I just didn't research enough, just saw it. Data is for sure updated (there are new entries), maybe not each hourly call but each X hours for sure (X < 15)

**Comment by juanignaciosl** [comment] 2015-05-26 11:56
Yes. In fact I've diff'd the response of v1 and v1_1 of dashboard viz listings, and that's why I saw the differences fixed in #3770. I've checked it works if data is changed, not sure what might I be missing. Could you change data of the sync file and trigger it again?

**Comment by Kartones** [comment] 2015-05-26 12:02
mm I did and now is updated in the listing. maybe a manual sync updates always but scheduled one doesnt?

Anyway leave as low priority and assign it to me for next sprint or so, I can check it and finally close or debug it as I'm "suffering" it.

**Comment by juanignaciosl** [comment] 2015-05-26 12:37
I've checked it (local) with the rake task and it works. I'd close this, but if you think there might be a problem I can hand it over to you to check.

**Comment by Kartones** [comment] 2015-05-26 12:48
If you think is ok then close, no problem. If happens I'll reopen

**Comment by juanignaciosl** [comment] 2015-05-26 13:06
:+1:

**Closed** 2015-05-26 13:06 UTC
Labels: 2 - Working, backend, backend-refactor, bug
