### ISSUE TITLE
Error changing privacy from private to with link.

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2407] opened 2015-02-20 15:29 UTC
We've had two issues here.

1. Changing privacy from API wasn't changing the privacy really.
  In this case, in the dashboard the table appeared as "with link", but once you entered in the table it was private. Also, the privacy selector in the dashboard was kind of bugged and didn't allow to change the privacy from there.

2. Changing privacy from dashboard wasn't changing the privacy really. 

cc @rochoa @Kartones

**Comment by Kartones** [comment] 2015-02-24 10:58
Dev install, repeating steps with an already existing private table:

### Current status
```
curl -i -H 'Content-Type: application/json' -H 'Accept: application/json' -X GET -d '{}' "http://kartones.localhost.lan:3000/api/v1/tables/empty?api_key=ab428f00dfe5366754b9d2d8ff47bfcbcc9f3742"

[...] "privacy":"PRIVATE" [...]
```
### Change
```
curl -i -H 'Content-Type: application/json' -H 'Accept: application/json' -X PUT -d '{"privacy":"LINK"}' "http://kartones.localhost.lan:3000/api/v1/tables/empty?api_key=ab428f00dfe5366754b9d2d8ff47bfcbcc9f3742"

[...] "privacy":"LINK" [...]

curl -i -H 'Content-Type: application/json' -H 'Accept: application/json' -X GET -d '{}' "http://kartones.localhost.lan:3000/api/v1/tables/empty?api_key=ab428f00dfe5366754b9d2d8ff47bfcbcc9f3742"

[...] "privacy":"LINK" [...]
```

Tried the same in live with a test table, and works also as expected. I can change as many times as I want the privacy and both the viz json data is ok and from the editor (old Dashboard) I can see the correct privacy.

**Comment by rochoa** [comment] 2015-02-24 14:29
I think the key here is that you are missing the communication issue with the tiler. Although is not this very same scenario I gonna try to give you some details about a similar one:

# STR

1. create a new table
1. ensure privacy is set to true
1. create a visualisation with that table
1. turn off the tiler
1. change the privacy on the table to private

# Current result

The table privacy is changed, however it was not possible to communicate with the tiler to propagate that change. In this case the layergroup will stop using the anonymous and start using a named map with a table (because the table is now private) but as it failed the layer didn't change from anonymous to named type and will continue using the anonymous map.

# Expected result

If it was not possible to propagate the changes to the layers (and the tiler) the privacy change in the table should not happen because all the visualisations that didn't get the changes in its layers (and in the tiler templates) will be broken trying to use a private table as a public one.

**Comment by rochoa** [comment] 2015-02-24 14:33
BTW change `4. turn off the tiler` with `4. there was a connectivity issue with the tiler in production` or `4. tiler was down in production` and you get the production scenario :-)

**Comment by Kartones** [comment] 2015-02-24 14:34
Yes, that could be. I can research into revert in case of error (by trying to save the named map as early as possible), of course. 

But worries me that we have so frequent communication failures, IIRC I already setup a retry system with multiple attempts.

**Comment by rochoa** [comment] 2015-02-24 14:42
It's not a matter of retrying. If it keeps failing we should not allow to change the table privacy if we cannot guarantee the consistency, i.e., the layer model not matching the required table privacy. If after N retries it failed we should not change the table privacy.

I know it's not easy to do this kind of transactions/rollbacks giving the current models and frameworks but we need to, otherwise we cannot rely on the models to keep its consistency.

**Comment by Kartones** [comment] 2015-02-24 14:43
No no, of course it should rollback. What I mean is that even rolling back that's only a way to ensure Table consistency, but doesn't solves the communication problems themselves (which seem to happen more often than they should)

**Comment by rochoa** [comment] 2015-02-24 14:52
I know but ... CAP, pick two! In this case I go with CP because we cannot guarantee availability in our distributed system.

Obviously we have to improve on the communications problems between the different components but IMO we cannot guarantee it so we should keep the consistency by tolerating the partitions.

**Comment by rochoa** [comment] 2015-02-24 17:55
Another **STR** for this:

1. Create a private table
1. Add some points
1. Create a visualization from it
1. Publish it
1. Make the table public
1. Try to see the embed map

## Current result

The visualisation tries to use the named maps api but the template that it tries to use was removed (most likely in step 5.) and it no longer exists it fails to render.

## Expected result

The visualisation should use the anonymous maps api

From a manual regression suite.

**Comment by javisantana** [comment] 2015-02-24 18:55
@rafatower @Kartones I checked it in local installation and happens with the steps @rochoa described.
I also tested the revision before merging the vizjson caching (6bffdfc) and it works as expected.

**Comment by rafatower** [comment] 2015-02-25 09:05
First I'm gonna fix tests in master and then Kartones will help me fix the caching part.

**Comment by rafatower** [comment] 2015-02-25 13:36
Just wondering what we're invalidating. I added some traces to the code and using the last scenario mentioned by rochoa I found that the keys being invalidated:

requesting the viz.json with the private table:
```
$ curl http://development.localhost.lan:3000/api/v2/viz/5779ab04-bce1-11e4-aab1-d2f8bb8a98de/viz.json
RTORRE: setting redis: visualization:5779ab04-bce1-11e4-aab1-d2f8bb8a98de:vizjson
```

changing the privacy of the table to public:
```
RTORRE: invalidating varnish: .*1f524362-bce1-11e4-aab1-d2f8bb8a98de:vizjson
RTORRE: invalidating redis: visualization:1f524362-bce1-11e4-aab1-d2f8bb8a98de:vizjson
RTORRE: invalidating varnish: .*1f524362-bce1-11e4-aab1-d2f8bb8a98de:vizjson
RTORRE: invalidating redis: visualization:1f524362-bce1-11e4-aab1-d2f8bb8a98de:vizjson
```

and when requested again:
```
$ curl http://development.localhost.lan:3000/api/v2/viz/5779ab04-bce1-11e4-aab1-d2f8bb8a98de/viz.json

# redis log
1424871224.148953 [0 127.0.0.1:60348] "get" "visualization:5779ab04-bce1-11e4-aab1-d2f8bb8a98de:vizjson"
```

so when setting and requesting the vizjson it uses the `Visualization::Member#id 5779ab04-bce1-11e4-aab1-d2f8bb8a98de` but when invalidating it is another `1f524362-bce1-11e4-aab1-d2f8bb8a98de`

**Comment by rafatower** [comment] 2015-02-25 15:25
Doing a bit more debugging it seems like varnish was working ok just by chance:

when caching, it is using this header in the response:
```
X-Cache-Channel:cartodb_dev_user_fe3b850a-01c0-48f9-8a26-a82f09e9b53f_db:public.untitled_table_14,5779ab04-bce1-11e4-aab1-d2f8bb8a98de:vizjson
```
see [visualizations_controller.rb#L195](https://github.com/CartoDB/cartodb/blob/9c8fa36aa54c03a7e19ffee4afc721e0b97775af/app/controllers/admin/visualizations_controller.rb#L195), [visualizations_controller.rb#L273](https://github.com/CartoDB/cartodb/blob/9c8fa36aa54c03a7e19ffee4afc721e0b97775af/app/controllers/admin/visualizations_controller.rb#L273) and [visualization/member.rb#L350-L357](https://github.com/CartoDB/cartodb/blob/83ba1a2f2037560310fddce4265277faa0dea889/app/models/visualization/member.rb#L350-L357)

when invalidating, it is effectively using a regexp that matches that header (from tcpdump session):
```
	0x0000:  0000 0304 0006 0000 0000 0000 0000 0800  ................
	0x0010:  4500 00b9 169e 4000 4006 259f 7f00 0001  E.....@.@.%.....
	0x0020:  7f00 0001 bbfe 17c2 fd2a a0a0 e96e dba4  .........*...n..
	0x0030:  8018 015e fead 0000 0101 080a 03a6 b604  ...^............
	0x0040:  03a6 b604 7075 7267 6520 6f62 6a2e 6874  ....purge.obj.ht
	0x0050:  7470 2e58 2d43 6163 6865 2d43 6861 6e6e  tp.X-Cache-Chann
	0x0060:  656c 207e 205e 6361 7274 6f64 625f 6465  el.~.^cartodb_de
	0x0070:  765f 7573 6572 5f66 6533 6238 3530 612d  v_user_fe3b850a-
	0x0080:  3031 6330 2d34 3866 392d 3861 3236 2d61  01c0-48f9-8a26-a
	0x0090:  3832 6630 3965 3962 3533 665f 6462 3a28  82f09e9b53f_db:(
	0x00a0:  2e2a 7075 626c 6963 5c2e 756e 7469 746c  .*public\.untitl
	0x00b0:  6564 5f74 6162 6c65 5f31 342e 2a29 7c28  ed_table_14.*)|(
	0x00c0:  7461 626c 6529 240d 0a                   table)$..
```
see [user.rb#L1717](https://github.com/CartoDB/cartodb/blob/a55290114bbc215c27f46193fd71cdfe80e75c62/app/models/user.rb#L1717)

**Comment by Kartones** [comment] 2015-02-25 16:14
I've built a list of stuff that touches varnish (I think I haven't left anything):
```
admin/visualizations_controller.rb
	public_map
		response.headers['X-Cache-Channel'] = "#{@visualization.varnish_key}:vizjson"
	show_organization_embed_map
		response.headers['X-Cache-Channel'] = "#{@visualization.varnish_key}:vizjson"
	show_protected_public_map
		response.headers['X-Cache-Channel'] = "#{@visualization.varnish_key}:vizjson"
	embed_map
		response.headers['X-Cache-Channel'] = "#{@visualization.varnish_key}:vizjson"

api/json/tables_controller.rb
	vizzjson
		response.headers['X-Cache-Channel'] = "#{table.varnish_key}:vizjson"

api/json/visualizations_controller.rb
	set_vizjson_response_headers_for
		response.headers['X-Cache-Channel'] = "#{visualization.varnish_key}:vizjson"

models/user.rb
	after_save
		invalidate_varnish_cache(regex: '.*:vizjson')
	before_destroy
		invalidate_varnish_cache
	invalidate_varnish_cache
		options[:regex] ||= '.*'; CartoDB::Varnish.new.purge("#{database_name}#{options[:regex]}")
	setup_new_user
		self.create_function_invalidate_varnish
	create_function_invalidate_varnish
	create_function_invalidate_varnish_http
		"^#{self.database_name}:(.*%s.*)|(cdb_tablemetadata)|(table)$"' % table_name.replace('"','')
	create_function_invalidate_varnish_telnet
		('^#{self.database_name}:(.*%s.*)|(cdb_tablemetadata)|(table)$' % table_name.replace('"','')

models/table.rb
	invalidate_varnish_cache
		CartoDB::Varnish.new.purge("#{varnish_key}")
		invalidate_cache_for(affected_visualizations) if id && table_visualization
	varnish_key
		"^#{self.owner.database_name}:(.*#{owner.database_schema}\\.#{self.name}.*)|(table)$"
	after_save
		manager.propagate_to_varnish
	after_destroy
		invalidate_varnish_cache
	name=
		self.invalidate_varnish_cache if !owner.nil? && owner.database_name
	add_column!
		self.invalidate_varnish_cache
	drop_column!
		self.invalidate_varnish_cache
	modify_column!
		self.invalidate_varnish_cache

models/table/privacy_manager.rb
	invalidate_varnish_cache
		table.invalidate_varnish_cache(false)
	propagate_to_varnish
		invalidate_varnish_cache

models/visualization/member.rb
	varnish_key
		"#{user.database_name}:#{sorted_table_names},#{id}"
	varnish_vizzjson_key
		".*#{id}:vizjson"
	invalidate_varnish_cache
		CartoDB::Varnish.new.purge(varnish_vizzjson_key)
		parent.invalidate_cache unless parent_id.nil?
	invalidate_cache
		invalidate_varnish_cache
	propagate_privacy_to
		CartoDB::TablePrivacyManager.new(table).set_from(self).propagate_to_varnish

models/layer.rb
	after_save
		maps.each(&:invalidate_vizjson_varnish_cache)
		affected_tables.each(&:invalidate_varnish_cache)    if data_layer?
	before_destroy
		maps.each(&:invalidate_vizjson_varnish_cache)

models/map.rb
	after_save
		invalidate_vizjson_varnish_cache
	before_destroy
		invalidate_vizjson_varnish_cache
	invalidate_vizjson_varnish_cache
		visualization.invalidate_cache_and_refresh_named_map unless visualization.id == being_destroyed_by_vis_id

models/synchronization/adapter.rb
	cartodbfy
		table.send(:invalidate_varnish_cache)

```

**Comment by rafatower** [comment] 2015-02-26 10:36
We've seen an issue with x-cache-channel not being set for public viz. Looking into it...

**Comment by rafatower** [comment] 2015-02-26 13:06
I made sure the rails backend is setting the X-Cache-Host header. I'll dig deeper to check if it is rui varnish config or what.

**Comment by rafatower** [comment] 2015-02-26 13:30
Seems like we're having negative caching with private views that reply non-logged users with 403 forbidden. Checking it...

**Comment by rafatower** [comment] 2015-02-26 13:49
Seems like an issue with varnish `hit-for-pass` config that's been in production for ages. @zenitraM can give more details on it.

The scenario:
1. Create a private visualization
2. Access the viz.json url without session cookie. The server replies with 403 forbidden
3. Change the visualization privacy to public. The server invalidates the caches (key not cached anyways but...)

Expected: from that point on, the viz.json is cached and served by varnish.

Actual: the viz.json is never cached, `varnishstat` show increments on `Cache hits for pass` counter for every request to that viz.json.

**Comment by rafatower** [comment] 2015-03-02 15:36
Fixed both the legacy varnish issue and re-deployed with fix for redis caching of vizjson in https://github.com/CartoDB/cartodb/pull/2510

**Comment by rochoa** [comment] 2015-03-13 17:43
Hey, we closed this issue because we fixed the regression with the viz.json but the real problem still exists.
See https://github.com/CartoDB/cartodb/issues/2407#issuecomment-75765930 and https://github.com/CartoDB/cartodb/issues/2407#issuecomment-75768221

**Comment by rochoa** [comment] 2015-03-13 17:44
cc @juanignaciosl

**Comment by juanignaciosl** [comment] 2015-03-13 18:05
Today scenario: SB/4781937

Changing table privacy to private throws 400:  {"errors":["Unknown error"]}

It happened with a broken sync table (broken because of the `wkb_geometry` problem).

**Comment by iriberri** [comment] 2015-03-16 15:27
We're suffering this in both:

SB/4617460
and
SB/4781937

**Comment by iriberri** [comment] 2015-03-16 15:49
I just checked all vizs involved in 4781937 and seem to be working atm.

**Comment by rafatower** [comment] 2015-04-24 10:28
I'd say this is to be considered after the refactor

**Comment by Kartones** [comment] 2015-09-09 10:51
Will attack at https://github.com/CartoDB/cartodb/issues/4992 so considering this as a duplicate and closing

**Closed by Kartones** 2015-09-09 10:51 UTC
Labels: 0 - Backlog, backend, backend-refactor, bug, From Support
