### ISSUE TITLE
[ogr2ogr] GeoJSON Field Guessing - Numbers as Strings when there are Null values 

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#6572] opened 2016-02-11 17:05 UTC
S/B 8104974
@iriberri 

### Context
Number values not correctly guessed in GeoJSON value when some of the values are null

### Process
Import a GeoJSON file where one of the objects has null values in the number columns
The columns with number values will sometimes be guessed as string, sometime as number

### Expected Result
Null columns that are number values should be guessed as type number

###  Current Result
![screen shot 2016-02-11 at 11 09 27 am](https://cloud.githubusercontent.com/assets/5423288/12981741/f605b87a-d0af-11e5-9547-d915c493b385.png)

Example geojson:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
          "name": "Dinagat Islands",
          "test1": 1234,
          "test2": 56789.5,
          "test3": 23456,
          "test4": 229494.5,
          "test5": 407.5,
          "test6": 52341,
          "test7": 6494.5,
          "test8": 12345
      },
      "geometry": {
        "type": "Point",
        "coordinates": [125.6, 10.1]
      }
    },
    {
      "type": "Feature",
      "properties": {
          "name": "Dinagat Islands",
          "test1": null,
          "test2": null,
          "test3": null,
          "test4": null,
          "test5": null,
          "test6": null,
          "test7": null,
          "test8": null
      },
      "geometry": {
        "type": "Point",
        "coordinates": [-125.6, 10.1]
      }
    }
  ]
}
```

**Comment by iriberri** [comment] 2016-04-18 14:01
It doesn't seem to be an option for GeoJSON files, but the ogr2ogr CSV driver allows to set this option:

````
EMPTY_STRING_AS_NULL=YES/NO (default NO) (GDAL >= 2.1) Whether to consider empty strings as null fields on reading'.
````

which made me remember about this issue.

http://www.gdal.org/drv_csv.html

**Comment by iriberri** [comment] 2016-07-04 10:22
@saleiva this is the issue I mentioned to you

@rafatower it looks like ogr2ogr is not setting a column (from GeoJSON) as numeric if there's any null value in it. An example once imported:

![image](https://cloud.githubusercontent.com/assets/1730320/16557751/ec0e7854-41e1-11e6-85fe-acf6c1ae5189.png)

Do you think it makes sense to report this in ogr2ogr?

**Comment by rafatower** [comment] 2016-07-07 15:15
It is fixed in most recent versions of gdal library (the upstream project). We need to package, test and release a new version.

Fix confirmed with `gdal2.1-static-bin 2.1.0+svn.34515-precise1`. We might one to pick `2.2.0` instead of a development version.

**Comment by rafatower** [comment] 2016-07-07 15:17
related to: https://github.com/CartoDB/cartodb/issues/6853
(also to be fixed with updated binaries)

and to: https://github.com/CartoDB/gdal/issues/1
(which I've been dragging for a bit long)

**Comment by iriberri** [comment] 2016-07-29 09:21
We just released the new ogr2ogr version, so fixed. :)

**Closed by iriberri** 2016-07-29 09:21 UTC
Labels: Data-services
