### ISSUE TITLE
scrolling in carousel is not working :(

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#9704] opened 2016-09-07 21:38 UTC
@xavijam i think... this bug's back :(

![carousel](https://cloud.githubusercontent.com/assets/1214201/18329522/1ab4fb7e-7554-11e6-9bf5-cd39ff8bd192.gif)

**Comment by xavijam** [comment] 2016-09-08 07:18
Not happening to me, checked in production.

**Comment by xavijam** [comment] 2016-09-08 10:44
Closing since I can't reproduce it man 💋

**Closed** 2016-09-08 10:44 UTC
