### ISSUE TITLE
Embed enhancements 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13765] opened 2018-03-26 17:35 UTC
- [x] This element collapsed shouldn't have a white shadow nor a scrolling bar.

![screen shot 2018-03-26 at 17 00 47](https://user-images.githubusercontent.com/16247628/37919764-227706ac-3125-11e8-94e6-cd602dee4ee9.png)

- [x] If you collapse it, and expand the viewport, the legend looks like the image below. It should be shown entirely. This can also be seen in the gif below.

![screen shot 2018-03-26 at 18 40 40](https://user-images.githubusercontent.com/16247628/37919799-3cd5ef36-3125-11e8-91d2-4894d0d01c83.png)
 
- [x] Long legends are getting covered by the horizontal nav of widgets in viewports between 600px and 760px. The legends box is not adjusting its height on that breakpoint. (Could it be related to it being a custom legend?) 

![embed](https://user-images.githubusercontent.com/16247628/37921732-e737fd7a-312a-11e8-827b-940d2b7f86a8.gif)

- [x] There has to be at least 8px of margin between the legends and the map buttons

![screen shot 2018-03-26 at 19 20 45](https://user-images.githubusercontent.com/16247628/37921710-d88fd932-312a-11e8-848c-22684a87ec89.png)

- [ ] Since we had to add more light blue margins in the latest iterations of the embed that weren't considered in the original design, the current bottom bar has some visual issues. We want to solve them by making the whole bottom bar also light blue with 8px of margin all around it. 

Production
![screen shot 2018-03-26 at 19 26 43](https://user-images.githubusercontent.com/16247628/37922025-c1ee45b4-312b-11e8-9e2a-40be60f5923c.png)

Design
![screen shot 2018-03-26 at 19 27 31](https://user-images.githubusercontent.com/16247628/37922030-c3f4eac0-312b-11e8-8ddc-590a430baf30.png)

- [x] Social media icons should have a Builder blue hover effect

- [x] We want to add a `border: 1px solid #DDD` to the whole embed on viewports below 600px to avoid these situations in which the embed's boundaries aren't obvious. 

![screen shot 2018-03-26 at 19 30 31](https://user-images.githubusercontent.com/16247628/37922241-53a595c0-312c-11e8-8dae-8ddfd94067ef.png)

- [x] There's an unnecessary border radius on the legends div on viewports below 600px that we should remove.

![screen shot 2018-03-26 at 19 35 23](https://user-images.githubusercontent.com/16247628/37922453-dd037ef4-312c-11e8-940b-5e2e5e34ea4c.png)
 

Assigning @ramiroaznar as requested.

**Comment by ivanmalagon** [comment] 2018-03-27 15:30
I'm adding here some visual tweaks related with embed legends that haven dropped out from a related ticket.

This is how it should look: 

## Below 600px: 

![embed 300 layer selector](https://user-images.githubusercontent.com/16247628/37898387-fca2f774-30e8-11e8-8dde-457640d5abd7.png)
  
- "LEGENDS" should say "LAYERS" instead. 
- 16px margin between layers

## Above 600px:

![screen shot 2018-03-26 at 11 04 01](https://user-images.githubusercontent.com/16247628/37898506-45d0893e-30e9-11e8-9ad2-a96b1c662d7c.png)
(**Left:** Production | **Right:** Design)

- 16px margin between header and layers (currently is set on 8px)
- 16px margin between layers (currently is set on 24px)
- 12px margin top and bottom of the whole box (right now, the last layer is adding a margin bottom of 24px)

**Comment by rjimenezda** [comment] 2018-04-04 15:59
Second case is fixed on prod :ship:

**Comment by rjimenezda** [comment] 2018-04-04 17:34
@ivanmalagon should it never say 'Legends'? The code switches depending on whether there are legends + layer selector, or only layer selector

@arianaescobar The first one I can't reproduce, maybe it's been fixed in another one.

**Comment by arianaescobar** [comment] 2018-04-05 09:01
@rjimenezda yeah, I can't reproduce it either. 

> should it never say 'Legends'? 

Nope. If there are legends, it should say Legends.

**Comment by rjimenezda** [comment] 2018-04-05 09:13
@arianaescobar Oh, I just reproduced it 🎉 

You need a big legend that scrolls, scroll it a bit, but not so much that you can't collapse it anymore. Collapse it and bam, there it is.

**Comment by arianaescobar** [comment] 2018-04-05 09:26
there you go!

**Comment by rjimenezda** [comment] 2018-04-09 15:35
Staging User: embedimprove

**Comment by rjimenezda** [comment] 2018-04-12 10:48
On production 🚢

**Comment by ramiroaznar** [comment] 2018-04-13 09:19
Hey @rjimenezda legends margins should be `20px top and bottom, 24px left and right`

**Comment by rjimenezda** [comment] 2018-04-13 10:38
![image](https://user-images.githubusercontent.com/446970/38730625-85f89d08-3f17-11e8-85ad-7b52f7a7c247.png)

@arianaescobar @ramiroaznar

**Comment by ramiroaznar** [comment] 2018-04-13 10:50
It looks good to me. Let's see what Ari has to say.

**Comment by arianaescobar** [comment] 2018-04-13 10:59
I'm sorry guys, I'm just reviewing this more calmly and I was wrong when I gave you those numbers, @ramiroaznar. Damn context switch. 

Our design mockups are not updated with the latest decisions on that, the correct ones (for legends above 600px of viewport) are those that @ivanmalagon shared in [his comment](https://github.com/CartoDB/cartodb/issues/13765#issuecomment-376568905) above.

> 10px margin top and bottom of the whole box (right now, the last layer is adding a margin bottom of 24px), and 12px margin left and right.

Also, careful with the margin-bottom of each legend, I can see that the last one is adding extra margin.

**Comment by rjimenezda** [comment] 2018-04-13 13:10
So, to clear up. Leave them as they are, but double check all legends types in case they're inserting margin-bottom?

**Comment by arianaescobar** [comment] 2018-04-13 13:55
That extra margin-bottom needs to be fixed, yup. We're taking a lot of screenshots right now for CARTO Locations' talks and that's a problem. 

Buuuut, honestly, it worries me making other types of changes (like the surrounding margins) on this right now, given how this component breaks with the slightest change and because right now we're so busy with the event that we don't have the time to properly review every case and perform proper acceptances.

**Closed** 2018-04-23 08:18 UTC
Labels: Frontend, enhancement
