### ISSUE TITLE
After editing a geometry, we should get the left panel back to the layer one (wherever the user would be before clicking on edit)

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10472] opened 2016-10-31 19:04 UTC

**Comment by alonsogarciapablo** [comment] 2016-11-02 15:41
Closed via https://github.com/CartoDB/cartodb/commit/d070f6bca46b5092648d249cb5311841e290c544

**Comment by saleiva** [comment] 2016-11-05 15:39
Not working for me in https://matatageom.carto-staging.com/builder/5b31d9b4-4bae-4fc3-874e-efc2cec65f21

**Comment by alonsogarciapablo** [comment] 2016-11-07 09:19
@saleiva it seems to be working "fine" for me (i.e: clicking back takes the left panel to latest panel the user was seeing when he/she clicked the Edit geometry button):

![back-to-the-future](https://cloud.githubusercontent.com/assets/390398/20052144/ee10d4fe-a4d2-11e6-9573-8be3fb8ab41a.gif)

In the example, if the user had clicked the layer before clicking the "Edit" and going back, it will show the Layer panel. But, if it clicked "Edit" and then Back, while viewing the list of layers, it will then see the list of layers again. That's how I understood `wherever the user would be before clicking on edit`...

Please check the gif and confirm if this is right or wrong. If it's wrong, I'd appreciate some Steps To Reproduce. Thanks @saleiva!

**Closed** 2016-11-07 14:12 UTC
Labels: bug
