### ISSUE TITLE
Clicking on undo after animated=true breaks the form area 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7800] opened 2016-06-13 18:03 UTC
Create a point map
Change the point color
Click on "animated"
Click on undo.

The form area gets empty forever

**Comment by xavijam** [comment] 2016-06-24 09:32
Not happening to me in local, let me try in production.

**Comment by xavijam** [comment] 2016-06-24 09:34
_reproduced_

**Comment by xavijam** [comment] 2016-06-24 10:15
It is like "broken" because query-schema-model status attribute is resetted to 'unfetched' when the analysis is saved. I feel after @viddo finishes his work in the ticket about analysis persistence we can't fix it.

**Comment by xavijam** [comment] 2016-06-27 14:34
Already fixed by @viddo with https://github.com/CartoDB/cartodb/pull/8232 👏

**Closed by xavijam** 2016-06-27 14:34 UTC
Labels: bug
