### ISSUE TITLE
Missing tables from dashboard when cartodbfying them

### ISSUE THREAD

**Issue by jesusvazquez** [CartoDB/cartodb#5464] opened 2015-09-10 09:54 UTC
I've been performing the smoke tests and I think I've found a bug. 

Create and delete table seems to work nice but when catodbfying the table it never appears in the dashboard.
```
DROP TABLE Persons;
CREATE TABLE Persons
(
    PersonID int,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255)
);

SELECT cdb_cartodbfytable('jesus', 'persons');

```

We don't know if this is just a bug related with the onpremise release, @rafatower is checking it in production right now.

cc/ @azamorano @javisantana @rafatower

**Comment by rafatower** [comment] 2015-09-10 12:47
Executed from console:
```
Sequel::DatabaseError: PG::Error: ERROR:  relation "public.municipios" does not exist

	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `async_exec'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/logging.rb:33:in `log_yield'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `block in execute'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:111:in `check_disconnect_errors'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:132:in `execute'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:411:in `_execute'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block (2 levels) in execute'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:423:in `check_database_errors'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `block in execute'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `synchronize'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:242:in `execute'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/dataset/actions.rb:778:in `execute'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:523:in `fetch_rows'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/dataset/actions.rb:154:in `each'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel_pg-1.6.3/lib/sequel_pg/sequel_pg.rb:58:in `each'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/dataset/actions.rb:55:in `all'
	from /home/ubuntu/www/production.cartodb.com/releases/20150910082107/app/models/user.rb:1228:in `search_for_cartodbfied_tables'
	from /home/ubuntu/www/production.cartodb.com/releases/20150910082107/app/models/user.rb:1188:in `link_ghost_tables'
	from (irb):17
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/railties-3.2.22/lib/rails/commands/console.rb:47:in `start'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/railties-3.2.22/lib/rails/commands/console.rb:8:in `start'
	from /home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/railties-3.2.22/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
```
I think it is not logged in rollbar.

**Comment by rafatower** [comment] 2015-09-10 12:52
And in que05:
```
$ grep "public.municipio" resque.log
** [09:42:26 2015-09-10] 16242: (Job{users} | Resque::UserJobs::SyncTables::LinkGhostTables | ["08d08948-27a5-4ac9-aab0-8bcc7dfbecdc"]) failed: #<Sequel::DatabaseError: PG::Error: ERROR:  relation "public.municipios" does not exist
** [09:42:31 2015-09-10] 16297: (Job{users} | Resque::UserJobs::SyncTables::LinkGhostTables | ["08d08948-27a5-4ac9-aab0-8bcc7dfbecdc"]) failed: #<Sequel::DatabaseError: PG::Error: ERROR:  relation "public.municipios" does not exist
** [09:50:23 2015-09-10] 21641: (Job{users} | Resque::UserJobs::SyncTables::LinkGhostTables | ["08d08948-27a5-4ac9-aab0-8bcc7dfbecdc"]) failed: #<Sequel::DatabaseError: PG::Error: ERROR:  relation "public.municipios" does not exist
```
so the problem is that it is failing in some circumstances and we're not getting traces of it

**Comment by rafatower** [comment] 2015-09-10 13:52
I created an issue to log all exceptions in resque jobs: https://github.com/CartoDB/cartodb/issues/5468

**Comment by rafatower** [comment] 2015-09-10 14:23
The query that is failing: https://github.com/CartoDB/cartodb/blob/master/app/models/user.rb#L1192-L1218

in that particular case:
```sql
SELECT table_name, count(column_name::text) cdb_columns_count
FROM information_schema.columns c, pg_tables t, pg_trigger tg
WHERE
  t.tablename = c.table_name AND
  t.schemaname = c.table_schema AND
  c.table_schema = 'public' AND
  t.tableowner = 'cartodb_user_08d08948-27a5-4ac9-aab0-8bcc7dfbecdc' AND
  c.table_name NOT IN ('tracking_eric','data','untitled_table','natural2','sgp2014_mun022','testing_1','out_4','parts4a','quater_mile','untitled_table_11','analysis_all','testing_3','out_5','strava_290350441','untitled_table_18','tm_world_borders_s_2','untitled_table_1','hours','untitled_table_9','strava','m2010b','seaward_boundary','bikeroutes_ny','scge_migration','world_borders','query_4','range_test','untitled_table_14_1','table_1431847093200','fon_100k_the_geom_sample','untitled_table_5','loteria_poblaciones_2','ne_50m_urban_areas','ne_10m_populated_places_simple','roads_3','untitled_table_4_281_29','spanish_adm2_provinces','out_2','mapacyl10_altimetr_p_va','sensor_log_2015_07_07_21_08','untitled_table_4','inv_4123','inv','out_7','sgp2014_mun022_1','roads','testing','tornado','test_table','jamon_es_gay','out_1','query_1','sensor_log_2013_03_17_13_08','untitled_table_3','agroguia_plane','car_log_nurburgring_2013_05_30','out_6','madrid_spain_osm_line_1','query','query_2','untitled_table_10','untitled_table_7','untitled_table_6','sensor_log_2015_07_07_21_08_merge','query_5','sasairinov_2015_espagne_application','untitled_table_8','madrid_spain_osm_line','out_3','untitled_table_14','out','fon_100k_the_geom_sample_1','untitled_table_12','sensor_log_2015_05_17_11_11','untitled_table_13','untitled_table_2','inv_1417430127','gnis_nm_airpt09') AND
  column_name IN ('cartodb_id','the_geom','the_geom_webmercator') AND
  tg.tgrelid = (t.schemaname || '.' || t.tablename)::regclass::oid AND
  tg.tgname = 'test_quota_per_row'

  GROUP BY 1;
```

**Comment by rafatower** [comment] 2015-09-10 14:38
By commenting out this line in the query above:
```
--tg.tgrelid = (t.schemaname || '.' || t.tablename)::regclass::oid AND
```

I got these results:
```
cartodb_user_08d08948-27a5-4ac9-aab0-8bcc7dfbecdc_db-#   GROUP BY 1;
      table_name       | cdb_columns_count 
-----------------------+-------------------
 testing_json          |               243
 _parcel               |               243
 testing.test          |               243
 Municipios            |               243
 jesus                 |               243
 tm_world_borders_s_11 |               243
```
and the solution is proper quoting of identifiers:
```sql
tg.tgrelid = (quote_ident(t.schemaname) || '.' || quote_ident(t.tablename))::regclass::oid AND
```

**Comment by rafatower** [comment] 2015-09-10 15:28
There are other places to touch, such as here: https://github.com/CartoDB/cartodb/blob/master/app/models/user.rb#L1263 and here: https://github.com/CartoDB/cartodb/blob/master/app/models/table.rb#L720

**Comment by rafatower** [comment] 2016-05-30 10:05
If not fixed here then I hope it was with the ghost tables manager. closing this ftm.

**Closed by rafatower** 2016-05-30 10:05 UTC
Labels: Data-services
