### ISSUE TITLE
Migrate to Dropbox API v2

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#8303] opened 2016-06-29 06:44 UTC
From a Dropbox notification: "On June 28, 2017, API v1 will be turned off.". CartoDB currenly uses `dropbox-sdk` gem, which is based on API v1. There's no v2 gem.

cc @rafatower @luisbosque @xavijam

**Comment by rafatower** [comment] 2016-07-12 10:27
Mentioning @ethervoid in case you want to take a look.

This is the kind of issue that is not urgent but is kind of important. I thought of adding this to the next milestone (I just added to the current one cause I lack a "Next" in my tickets/milestone workflow yet).

**Comment by ethervoid** [comment] 2016-07-12 10:27
Great! assign it to me :D

**Comment by rafatower** [comment] 2016-07-12 10:32
(there's stuff that I assign to myself just to not forget, not because I'm that greedy :smile: )

**Comment by ethervoid** [comment] 2016-07-13 09:56
https://github.com/dropbox/dropbox-sdk-ruby/issues/41

**Comment by ethervoid** [comment] 2016-09-22 08:12
Here we have a gem that seems enough for our purposes https ://github.com/waits/dropbox-sdk-ruby

**Comment by ethervoid** [comment] 2017-02-15 09:35
This gem looks better https://github.com/Jesus/dropbox_api

**Comment by jorgesancha** [comment] 2017-04-25 11:00
Added to the technical debt section of What's Next to ensure we don't forget about it

**Comment by micagm** [comment] 2017-04-25 13:04
As mentioned in #651 a customer is making use of the Dropbox connector, and he would like to know if we are going to support the new version after June 2017. 

Could you please confirm and let me know what should we answer?

**Comment by jorgesancha** [comment] 2017-04-25 13:27
I just confirmed with @saleiva that we will support it

**Comment by micagm** [comment] 2017-04-25 15:34
Thank you!

**Comment by juanignaciosl** [comment] 2017-05-09 11:02
The good news: the PR (#12099) works for new users.

The bad news: it won't work for existing users: [(now) "there are two permissions: App folder and Full Dropbox."](https://www.dropbox.com/developers/reference/migration-guide#authentication). Our application has "permission type: Documents", which is no longer supported. So, we'll have to...

1. Create a new application (with "full dropbox" permission).
2. Change our server configuration (so it now uses that new application).
3. Get rid of every existing dropbox token, because they're from an application that doesn't exist anymore.
4. Ask every user with Dropbox integration to re-authenticate with Dropbox again.

The problem with this flow is that it will probably lead do broken sync tables. I've already contacted support but they won't probably come up with any workaround. I will take a look at migration alternatives. The simplest approach that I can think of right now is just switching, but it would break every sync table. The most complex one would be supporting both API v1 and API v2 until June, 28th, so there's a migration window for users.

As after API v1 is gone tables from users that don't re-authenticate won't work, we'll have to write to all users with Dropbox (more than 2k) asking them to do it (cc @noguerol ).

cc @CartoDB/builder-backend @javisantana

**Closed** 2017-06-12 07:24 UTC
Labels: Backend, blocked, Data-services
