### ISSUE TITLE
iw fields are not showed in the right order

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#9347] opened 2016-08-08 11:57 UTC
### Steps

* Add a click iw.
* Activate more than one field.
* The order of the fields showed in the iw are not the same as in the UI. Changing the order manually (or just moving them) does not change the output.

![iworder](https://cloud.githubusercontent.com/assets/5215798/17479001/05013f6e-5d70-11e6-9b3d-cb9ed81c5eba.png)

**Comment by matallo** [comment] 2016-08-18 11:02
can't reproduce following the steps, there's a know issue that might be this case https://github.com/CartoDB/cartodb/issues/8191

duplicated, closing then

**Closed by matallo** 2016-08-18 11:02 UTC
Labels: bug, Builder
