### ISSUE TITLE
feature request: carousel for related maps when removing datasets

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#4269] opened 2015-07-02 10:50 UTC
When removing a dataset only shows 3 maps that contain it

suggestion:
- we could list the rest of affected maps, so you can access them in a separate tab
- or we could have a carousel which slides and shows all the affected maps

![screen shot 2015-06-29 at 12 22 45](https://cloud.githubusercontent.com/assets/36676/8475531/f76cb3d2-20b8-11e5-955f-aa283b5b6ed1.png)

**Comment by viddo** [comment] 2015-07-02 10:58
duplicate of #1780

**Closed by viddo** 2015-07-02 10:58 UTC

**Comment by matallo** [comment] 2015-07-02 12:24
ooh, sorry for the noise, I already found other issues I was going to request already submitted but not this one! Thanks for pointing out @viddo
