### ISSUE TITLE
Hitting delete button when selecting Annotation/Text/Title item should not be browser back action

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#2100] opened 2015-02-05 23:56 UTC
I keep hitting the back button when I select a title item in my visualization. I keep doing it because i'm an idiot. But in my head I expect it to delete the item. In reality it does a back history request and i'm back in the dashboard, lonely and confused

**Comment by javierarce** [comment] 2015-03-12 14:26
Fixed :)

**Comment by andrewxhill** [comment] 2015-03-17 01:38
Waiiiit... now when the text area is select (so I am actually typing) if I hit delete it removes the window!

Here is how it works and I like it,

![del](https://cloud.githubusercontent.com/assets/370259/6679855/cf3f650a-cc24-11e4-99b7-d19f5715cd49.gif)

Now here is the behavior that doesn't work

![del2](https://cloud.githubusercontent.com/assets/370259/6679858/d73bbe3e-cc24-11e4-97a2-2e07829bd4af.gif)

**Comment by javierarce** [comment] 2015-03-17 09:12
Weird :( I can't reproduce the bug in Chrome, Firefox or Safari. Which browser did you use?

**Comment by javisantana** [comment] 2015-03-17 11:54
hey, this is a hotfix, it closes the overlay when you are editing. 

@alonsogarciapablo could you revert changes ?

**Comment by javisantana** [comment] 2015-03-17 11:55
steps to reproduce:

- create a visualization
- add a title item
- start editing text and press remove key

the item disappears but it should delete text

**Comment by alonsogarciapablo** [comment] 2015-03-17 14:53
I cant reproduce this bug either. It seems to be working as expected for me:

![editing_title](https://cloud.githubusercontent.com/assets/390398/6689857/3b36532a-ccbd-11e4-99ac-3ba1efc2e56c.gif)
 
![editing_text](https://cloud.githubusercontent.com/assets/390398/6689944/a2e48ee2-ccbd-11e4-8a8b-93658ffc0aaf.gif)

I'm using Chrome. @javisantana @andrewxhill are you using a different browser?

**Comment by javisantana** [comment] 2015-03-17 15:01
chrome on osx: 

cartodb.js 3.12.12
cartodbui v3.7.30 sha1: ed1574563a7458be3244a9695c309bee6df76c4c

**Comment by javisantana** [comment] 2015-03-17 15:01
working for me, I guess it was some cache?

**Comment by alonsogarciapablo** [comment] 2015-03-17 15:32
Great.

@andrewxhill can you please confirm that it's working?

**Comment by andrewxhill** [comment] 2015-03-17 15:54
yes, it works fine now!

On Tue, Mar 17, 2015 at 11:32 AM, Pablo Alonso <notifications@github.com>
wrote:

> Great.
>
> @andrewxhill <https://github.com/andrewxhill> can you please confirm that
> it's working?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/2100#issuecomment-82416222>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by alonsogarciapablo** [comment] 2015-03-17 16:06
Closing it then. Thanks!

**Closed by alonsogarciapablo** 2015-03-17 16:06 UTC
