### ISSUE TITLE
Error adding a geometry running cartodb in ruby2

### ISSUE THREAD

**Issue by azamorano** [CartoDB/cartodb#6324] opened 2015-12-28 10:55 UTC
While testing cartodb running ruby2 geometries don't manage to get added to the table view until we force some refresh and eventually appear. In that state frontend behaves badly and for example allows you to add different kind of geometries as the one that was previously added can not be determined.

Steps to reproduce:
1. Create an empty map
2. Add a new point.
3. Add a different kind of geometry (polygon or line). It should not allow you but it does. The previous geometries get messed up or take the form of the most recent added geometry.
4. Go to table view. Is empty.
5. Hit refresh until some content is got there.
6. Then everything seems to work normally.

**Comment by juanignaciosl** [comment] 2015-12-28 12:20
Ok, it seems like cache is not being cleared after adding the point (step 2). Step 2, which is a `POST` to `records` works. Then there're two subsequent calls to the SQL API, one of them should return a value but it won't. If you load the page again the points are there but controls keep disabled because of the same reason. A Cmd+shift+R reload, avoiding caches, make it work.

I don't know the cause yet, stay tuned.

cc @xavijam

**Comment by juanignaciosl** [comment] 2015-12-28 14:33
Closing, this was related to SQL API instead.

cc @dgaubert @luisbosque

**Closed by juanignaciosl** 2015-12-28 14:33 UTC
Labels: bug, ruby-2
