### ISSUE TITLE
Incorrect Geocoding of ISO-2 country code for Bahrain/Bosnia & Herzegovina

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#6371] opened 2016-01-08 22:39 UTC
@iriberri  
S/B 7826854

## Context

Geocoding based on ISO-2 Country code returns incorrect result for Bahrain.

## Process

Upload or create a dataset in CartoDB using Country Code for Bahrain (BH) and Bosnia & Herzegovina (BA). Geocode the dataset based on Admin Region using the column containing the ISO 2 country codes. Resulting polygon for Bahrain will be for Bosnia. 

See example dataset here: https://team.cartodb.com/u/chandra/tables/iso_country_code_test/table

## Expected Result

Country code for Bahrain (BH) should result in polygon for Bahrain, not polygon for Bosnia & Herzegovina (BA).

## Current Result

Country code for Bahrain (BH) returns polygon for Bosnia & Herzegovina (BA).

See earlier issue closed last year: https://github.com/CartoDB/cartodb/issues/1399

http://en.wikipedia.org/wiki/ISO_3166-2:BH

http://en.wikipedia.org/wiki/ISO_3166-2:BA

**Comment by iriberri** [comment] 2016-01-13 16:58
The cause of the issue comes from: https://github.com/CartoDB/data-services/blob/cb4b6411a108414ebad52ef839bef253d4915bd3/geocoder/admin0/sql/build_synonym_table.sql#L80

**Comment by iriberri** [comment] 2016-02-03 17:26
Fixed in production.

**Closed by iriberri** 2016-02-03 17:26 UTC
Labels: Data-services
