### ISSUE TITLE
add analysis raises a javascript exception

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#7758] opened 2016-06-10 06:25 UTC
- go to a layer and click on add analysis
- select any analysis and click on "done"

it raises a javascript exception: `simpleGeometryTypeInput is required`

**Comment by alonsogarciapablo** [comment] 2016-06-10 08:11
This is a duplicate of https://github.com/CartoDB/cartodb/issues/7728.

**Closed by alonsogarciapablo** 2016-06-10 08:11 UTC
Labels: bug, editor-3
