### ISSUE TITLE
Numeric calculation issues when importing a small raster

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#7082] opened 2016-04-08 07:48 UTC
See RB/17210:
```
FloatDomainError: -Infinity

services/importer/lib/importer/raster2pgsql.rb, line 154 in ceil
services/importer/lib/importer/raster2pgsql.rb, line 154 in calculate_raster_overviews
services/importer/lib/importer/raster2pgsql.rb, line 37 in run
services/importer/lib/importer/tiff_loader.rb, line 23 in run
services/importer/lib/importer/runner.rb, line 236 in file_based_loader_run
services/importer/lib/importer/runner.rb, line 182 in import
services/importer/lib/importer/runner.rb, line 344 in execute_import
services/importer/lib/importer/runner.rb, line 273 in block (3 levels) in single_resource_import
services/importer/lib/importer/runner.rb, line 267 in each
services/importer/lib/importer/runner.rb, line 267 in each_with_index
services/importer/lib/importer/runner.rb, line 267 in block (2 levels) in single_resource_import
lib/cartodb/stats/aggregator.rb, line 45 in block in timing
lib/cartodb/stats/aggregator.rb, line 43 in timing
services/importer/lib/importer/runner.rb, line 262 in block in single_resource_import
lib/cartodb/stats/aggregator.rb, line 45 in block in timing
lib/cartodb/stats/aggregator.rb, line 43 in timing
services/importer/lib/importer/runner.rb, line 240 in single_resource_import
services/importer/lib/importer/runner.rb, line 97 in run_import
services/importer/lib/importer/runner.rb, line 90 in block in run
lib/cartodb/stats/aggregator.rb, line 45 in block in timing
lib/cartodb/stats/aggregator.rb, line 43 in timing
services/importer/lib/importer/runner.rb, line 89 in run
app/connectors/importer.rb, line 43 in run
app/models/data_import.rb, line 663 in new_importer
app/models/data_import.rb, line 389 in dispatch
app/models/data_import.rb, line 176 in run_import!
lib/resque/importer_jobs.rb, line 9 in block in perform
lib/resque/base_job.rb, line 21 in call
lib/resque/base_job.rb, line 21 in run_action
lib/resque/importer_jobs.rb, line 9 in perform
```

**Comment by rafatower** [comment] 2016-04-08 07:51
To reproduce:

[test_peru_rafa.tif.zip](https://github.com/CartoDB/cartodb/files/209804/test_peru_rafa.tif.zip)

```
$ gdalinfo test_peru_rafa.tif 
Driver: GTiff/GeoTIFF
Files: test_peru_rafa.tif
Size is 40, 23
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (113.264499999999998,-2.734250000000001)
Pixel Size = (0.000250000000000,-0.000250000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( 113.2645000,  -2.7342500) (113d15'52.20"E,  2d44' 3.30"S)
Lower Left  ( 113.2645000,  -2.7400000) (113d15'52.20"E,  2d44'24.00"S)
Upper Right ( 113.2745000,  -2.7342500) (113d16'28.20"E,  2d44' 3.30"S)
Lower Right ( 113.2745000,  -2.7400000) (113d16'28.20"E,  2d44'24.00"S)
Center      ( 113.2695000,  -2.7371250) (113d16'10.20"E,  2d44'13.65"S)
Band 1 Block=40x23 Type=Int32, ColorInterp=Gray
  NoData Value=0
```

**Comment by azvoleff** [comment] 2016-05-16 19:40
I see the same problem on a custom install running the latest CartoDB code, and also on cartodb.com. The file I am using is attached. Any thoughts on how to address this?
[example.tif.zip](https://github.com/CartoDB/cartodb/files/266836/example.tif.zip)

**Comment by drzhouq** [comment] 2016-09-07 23:18
I tracked down the error was caused by function  calculate_raster_overvies in the raster2pgsql.rb file under cartodb/services/importer/lib/importer.

When the bigger_size is smaller than 256, you will get a zero. And when you perform log function on zero, you get infinity. 

Possible patch, instead of divided by 256, divide it by 256.0 to avoid zero (perhaps, also need to check if bigger_size is zero or not before feed it to log function)

  1  def calculate_raster_overviews(raster_size)
  2         bigger_size = raster_size.max
  3 
  4         max_power = (Math::log(bigger_size / 256, 2)).ceil.to_i
  5 
  6         range = Range.new(1, max_power + 1)
  7 
  8         overviews = range.map{ |x| 2 ** x }
  9                          .select { |x| x <= 1000 }
 10 
 11         self.additional_tables = overviews
 12 
 13         overviews.join(',')
 14       end

**Comment by jgoizueta** [comment] 2016-09-09 09:22
Thank for your analysis @rzhouq!

You're right in your conclusions. Actually I think there are two separate issues here that you have detected:

First, we must avoid having negative values of `max_power`, e.g. by doing this:

```ruby
if bigger_size >= 256
  max_power = (Math::log(bigger_size / 256, 2)).ceil
else
  max_power = 0
end
```
(note the `.to_i` was unnecessary: `ceil` returns integers)

Then there's the question of computing `bigger_size / 256` in floating point (using 256.0), and how it affects the values with bigger_size > 256.

Currently it is an integer division (so 255/256 == 0 and 511/256 == 1)

Using floating point makes the results consistent in that we always reduce the rasters till they're no bigger than 256 in any dimension.

With the integer dimension, maximum reduction can be bigger or smaller than 256 (e.g. with bigger_size = 1279 the factor is 2 reducing the raster to 320, and with 1280 the factor is 3 and the raster gets down to 160).

I'd go for the floating point division which I think matches the original intent of the code, so:

```ruby
if bigger_size >= 256
  max_power = (Math::log(bigger_size / 256.0, 2)).ceil
else
  max_power = 0
end
```

**Comment by drzhouq** [comment] 2016-09-10 12:14
Thanks for fixing this issue, @jgoizueta. Is this fix in the carto.com production now?

**Comment by jgoizueta** [comment] 2016-09-12 06:22
@drzhouq: it is not yet in production, we still need to do some testing an reviewing; when it is in production we'll close this ticket.

**Closed** 2016-09-13 09:52 UTC
Labels: Data-services, raster-import

**Comment by jgoizueta** [comment] 2016-09-13 10:29
@drzhouq: this is in production now

**Comment by drzhouq** [comment] 2016-09-13 16:30
@jgoizueta fantastic. Carto rocks.
