### ISSUE TITLE
Labels-on-top doesn't work on twitter cards when having a private dataset on the map

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4462] opened 2015-07-15 12:16 UTC

**Comment by Kartones** [comment] 2015-07-15 12:24
Some preliminar tests:
- It does work, but looks as if **only** changing the basemap didn't updated the named map
- Privacy of datasets is not the reason, it works (and fails) the other way too (with public dataset)

**Comment by Kartones** [comment] 2015-07-15 12:37
Ok, reproduced.

Given an existing map (maybe a "new" map works also) that doesn't has a basemap with labels on top:
1) Get its static image: Should render fine
2) Change its basemap to one with labels on top
3) Check again its static image: It renders the new basemap but labels aren't present.

It is as if the labels layer was not stored, because if then you zoom out + in it fixes automatically.

**Comment by Kartones** [comment] 2015-07-15 12:56
Before basemap change:
```
plain layer @ 0
layergroup with mapnik layer @1
```

after basemap change (nothing else touched):
```
tiled layer @ 0 (no_labels)
tiled layer @ 2 (labels_only)
layergroup with mapnik layer @1
```

after touching zoom levels:
same structure as before

**Comment by Kartones** [comment] 2015-07-15 13:13
Confirmed that named map seems to not be full. When you change the basemap, named map only has stored the new http layer, it is only after a change such as zooming when the 2nd http layer with labels gets saved.

Checking as it might be Rails after all.

**Comment by Kartones** [comment] 2015-07-15 13:33
Checked that backend reflects changes when they come:
```
layer.after_save -> maps.each(&:update_related_named_maps)
map.after_save -> update_related_named_maps
```
In fact, manually debugging in local, it works fine the first time if come 2 PUT to the layers endpoint (probably one per layer), else fails, so I guess the editor is not sending properly always the labels

**Comment by alonsogarciapablo** [comment] 2015-07-15 13:54
On it!

**Comment by alonsogarciapablo** [comment] 2015-07-15 15:50
I've updated some code in the frontend so that the requests to add/update/destroy the layers related to the basemap go out in the right order. Still, when a new layer with labels is added, it seems that the basemaps is not updated. It works fine when there's a layer with labels and it's either updated or removed. Here're the requests that I'm seeing when basemap didn't have labels and a basemap with labels is selected:

<img width="1197" alt="screen shot 2015-07-15 at 17 46 31" src="https://cloud.githubusercontent.com/assets/390398/8702716/ddb2653e-2b19-11e5-93f8-cc22e2795d39.png">

**Comment by alonsogarciapablo** [comment] 2015-07-16 16:46
@kartones I assigned this back to you. We might end up saving all layers at once, but I thinks it's worth investigating what's going here in the meanwhile.

**Closed** 2015-07-17 10:58 UTC
Labels: 3 - Done, bug
