### ISSUE TITLE
Category colors get reverted

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#11250] opened 2017-01-13 18:30 UTC
### Context

* When working with customizing a category legend it gets reverted to the default value.

### Steps to Reproduce

1. Create a map with a point layer
2. Apply a category style
3. Change one of the colors of the legend
4. Try to change a second, when you click on the ramp it's reverted

![anim](https://cloud.githubusercontent.com/assets/188264/21940830/594ffb6e-d9c6-11e6-9a11-291762c57685.gif)

### Current Result
* Impossible to change more than one color

### Expected result
* Changes on the ramp are retained so you can change more than one.

### Browser and version
* Linux (Ubuntu 16.10)
* Chrome (`Version 55.0.2883.87 (64-bit)`) and Firefox (`50.1.0`)

### .carto file

[cicloton_cdmx map (on 2017-01-13 at 18.19.27).carto.zip](https://github.com/CartoDB/cartodb/files/705022/cicloton_cdmx.map.on.2017-01-13.at.18.19.27.carto.zip)

**Comment by matallo** [comment] 2017-02-02 16:42
can't reproduce :S

**Comment by xavijam** [comment] 2017-02-02 16:47
I can't reproduce either. @jsanz, could you check it please?

**Comment by xavijam** [comment] 2017-02-06 10:58
Already checked, with those steps to reproduce is not happening. Closing!

**Comment by nygeog** [comment] 2017-02-06 17:56
I was experiencing this issue w/ Category colors with Torque Animation for the Super Bowl Twitter map. The issue is still present there.

**Comment by xavijam** [comment] 2017-02-06 18:55
Steps to reproduce? Please.

**Comment by jsanz** [comment] 2017-02-06 19:07
I've been able to reproduce it again, same steps as in the issue description:

- Create a map with a point dataset
- Choose a field and category legend for the fill property
- Choose a color for one of the categories
- When you go back to change another, the full ramp gets reverted to the default status

![anim](https://cloud.githubusercontent.com/assets/188264/22661978/a67f6962-eca7-11e6-8de5-60563008888a.gif)

**Comment by ztephm** [comment] 2017-02-06 19:18
Seeing this also with same STR, here's my test:

[all_day map (on 2017-02-06 at 19.17.19).zip](https://github.com/CartoDB/cartodb/files/755628/all_day.map.on.2017-02-06.at.19.17.19.zip)

1. Create map from [this dataset](https://team.carto.com/u/stephaniemongon/dataset/stephaniemongon.all_day)
2. Click on map layer name, then on STYLE tab. 
3. In Fill section click on color bar, then BY VALUE & choose **magtype** column name.
4. Under default color scheme, click on "ml" column & change it's swatch color via picker:

  ![screen shot 2017-02-06 at 2 08 05 pm](https://cloud.githubusercontent.com/assets/1779444/22662155/0322734e-ec76-11e6-995e-1fa1ed1ac80b.png)

  ![screen shot 2017-02-06 at 2 10 52 pm](https://cloud.githubusercontent.com/assets/1779444/22662176/1cea0846-ec76-11e6-9015-fde8d0692de4.png)

5. Click outside of By Value tab to close it.
6. Click on Fill color bar again to re-open By Value panel

* Now the custom colors revert to original default palette:

  ![custom_cat](https://cloud.githubusercontent.com/assets/1779444/22662266/6036e4de-ec76-11e6-8919-f684b4b8e276.gif)

* NOTE: If you change all of the swatches at once without closing & re-opening the palette the issue doesn't happen:

  ![custom_cat_2](https://cloud.githubusercontent.com/assets/1779444/22662356/acea2ec6-ec76-11e6-9ce4-2df7057cc0f8.gif)

**Comment by matallo** [comment] 2017-02-07 11:25
I swear I can't reproduce this, also from my testing I do have the "Img" tab active when styling per value so it can be preventing that somehow (see attached)

![screen shot 2017-02-07 at 12 24 12](https://cloud.githubusercontent.com/assets/36676/22689282/853b1088-ed30-11e6-8be2-e002d443d245.png)


Can you confirm with icon styling feature activated this is still happening?

**Comment by ztephm** [comment] 2017-02-07 17:42
When I activate **icon-styling** SuperAdmin feature flag in my account I do not get this error any more.

**Comment by saleiva** [comment] 2017-02-07 18:34
which sounds great!!! :) Closing then since we will activate this pretty soon!

**Closed by saleiva** 2017-02-07 18:34 UTC
Labels: bug, Frontend
