### ISSUE TITLE
Exporting a AOI Drive time file returns underlying point features instead of Network Buffer polygons.

### ISSUE THREAD

**Issue by nygeog** [CartoDB/cartodb#11115] opened 2016-12-21 17:17 UTC
### Context

Exporting a AOI Drive time file returns underlying point features instead of Network Buffer polygons.
 

### Steps to Reproduce

1. Insert Points layer. 
2. Drive-time Analysis.
3. Export from Layer Card. 

### Current Result
I got the points back, not the network buffer polys. 

### Expected result
I'd like the polygon features from Drive Time isolines. It exports the underlying point layer. 

### Browser and version
Chrome 
 
### .carto file
Too big to upload. 
https://www.dropbox.com/s/4t35vx4bck7w2bg/5.%20GSTV%20-%20Drive%20Time%20-%20Avg.%20Population%20Estimate%20%28on%202016-12-20%20at%2021.18.41%29.carto?dl=1

**Comment by javitonino** [comment] 2017-01-05 10:12
Hey @nygeog 

I just imported your .carto, exported E layer (Drive Time) and I got polygons for the drivetime. Can you check again to see if it is fixed now?

**Comment by nygeog** [comment] 2017-01-06 15:42
Thanks @javitonino not sure I notated, but was seeing dif. behavior w/ dif. file export formats. I'll give a shot either later today or next week, in DC at moment for meetings. Thanks!

**Comment by nygeog** [comment] 2017-01-06 16:15
@javitonino Exporting a **shapefile** seems to still be showing up as a point layer. Can you verify if that's happening on your end when you export **shapfile**?

**Comment by javierarce** [comment] 2017-01-09 12:06
I can confirm the problem is happening to me too. 

I created a new layer with just two points. I added a AOI Drive time analysis that correctly produced a couple of polygons. I then exported the layer in CSV and shapfile formats and imported them.
The map that used the CSV file showed two polygons, as expected, whereas the shapefile one contained a couple of points. 

In both cases, the rest of the columns where the same (that is, only the geometry of the tables where affected).

**Comment by javitonino** [comment] 2017-01-09 13:16
Not an issue with the builder, the the SQL API. Moved to https://github.com/CartoDB/CartoDB-SQL-API/issues/402

Basically, the issue is that `.shp` export takes the first geometry column, and in the case of AOI drive time analysis, there are two columns (the original data and the polygons), so that the points go first and polygons last. Workaround: use any other export format.

**Closed by javitonino** 2017-01-09 13:16 UTC
Labels: bug

**Comment by nygeog** [comment] 2017-01-09 16:17
Thanks @javitonino!
