### ISSUE TITLE
In search, show user tables always before results from data library

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3936] opened 2015-06-05 16:26 UTC
If you have a table called "buildings", for example, you'll get several results from Data Library on the top of the search results, which makes difficult accessing the table you want.

cc @xavijam @saleiva

**Comment by saleiva** [comment] 2015-06-05 16:29
+1 Love it.

**Comment by xavijam** [comment] 2015-06-12 08:56
Could we do it in the backend side @juanignaciosl @Kartones?

**Comment by Kartones** [comment] 2015-06-12 09:30
No, at least not in the normal visualizations endpoint. 

Data Library doesn't exists from the REST APIs point of view, so this should be done at Explore API level, performing two searches (one for data library items, one for user items) and then merging them. This means also that the editor probably should point to the Explore API instead of the REST one at least for this searches.

It's really nice from the editor/product point of view, indeed, but shouldn't be done inside REST APIs but above them...

**Comment by xavijam** [comment] 2015-06-12 09:31
meh, ok, we will make magic in the frontend side.

**Comment by Kartones** [comment] 2015-06-12 09:33
no, I didn't said FE, it can perfectly be Ruby, but it needs to be above current endpoint, it's the classic platform vs product @javisantana argument...

**Comment by javisantana** [comment] 2015-06-12 09:42
is this a duplicate of https://github.com/CartoDB/cartodb/issues/2830 ? this needs to be done in backend

**Comment by juanignaciosl** [comment] 2015-06-12 09:53
"Mine" before "shared with me" before "datalibrary", with neither date nor alphabetic sorting? I'm not so sure, it's neither explicit not obvious. _Maybe_ always searching for mine + shared only, and fallback to data library if first query returned no results?

Whatever @saleiva or design team decides, I guess...

**Comment by saleiva** [comment] 2015-06-12 09:55
Nope, the idea is to change the order in case you have duplicated datasets for example...

**Comment by juanignaciosl** [comment] 2015-06-12 10:03
Ok, so we want to "sort by (<sorting criteria>, name, mine >> shared >> datalibrary) so in those cases where there's name collision, mine comes first, isn't it?

**Comment by Kartones** [comment] 2015-06-12 10:05
I'm a bit lost here so leaving the decision to you @juanignaciosl (if I have to implement something I'll ask for specifics)

**Comment by juanignaciosl** [comment] 2015-06-12 10:27
My proposal is the previous one, I can do it if you think if fixes the confusion.

**Comment by saleiva** [comment] 2015-06-12 10:30
Yep, but leave it to later :)

**Comment by alonsogarciapablo** [comment] 2016-11-16 16:19
There has been no activity on this issue for more several months. We are closing it. If you think this still needs to be addressed please open a new issue.

**Closed by alonsogarciapablo** 2016-11-16 16:19 UTC
Labels: enhancement
