### ISSUE TITLE
Country selectors in geocodings are "space sensitive"

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3392] opened 2015-04-27 15:34 UTC
In the namedplaces, zipcodes and admin1 options where you can specify a column with country names:

* [Available geometries remove the empty spaces in the country names](https://github.com/CartoDB/cartodb/blob/master/app/controllers/api/json/geocodings_controller.rb#L117)

but when getting the actual country values to make the search, these spaces are not removed.

This is causing that a dataset like:

````
zipcode, country
03204, "Spain "
````

is not geocoded (although the country is guessed OK in available geometries).

cc @rafatower

**Comment by iriberri** [comment] 2015-04-27 15:34
Just guessing:

Should this be solved by adding something similar like the line 117 here? https://github.com/CartoDB/cartodb/blob/master/app/controllers/api/json/geocodings_controller.rb#L49

**Comment by rafatower** [comment] 2015-04-27 16:16
@iriberri not in those lines, there's some ruby code elsewhere to trim the inputs before sending it to the geocoding functions.

I prefer to fix those cases in the geocoding postgres functions rather than in ruby code

I'm pretty sure there's a duplicate of this ticket.

**Comment by iriberri** [comment] 2015-04-27 16:17
I think the other ticket is about City Names explicitly

**Comment by iriberri** [comment] 2015-07-08 13:36
I'm going to move this to the following sprint. This requires creating a new function, loading it in the database and changing the ruby code to access to it + tests. I'm currently finishing the geocoding tests so once all the documentation of that part is cleaner working in issues like this one should be easier.

**Comment by saleiva** [comment] 2015-08-17 19:01
I saw another user with this problem, today

**Comment by ztephm** [comment] 2015-08-17 19:04
Yep S/B 6308570 today had leading spaces before city names causing geocode failure, all fixed after removing via text editor.

**Comment by saleiva** [comment] 2015-09-02 13:45
ping!

**Comment by iriberri** [comment] 2015-11-26 14:57
@rafatower do we remove the sprint here? if we want to do this in Postgres side this involves releasing new geocoding functions.

**Comment by rafatower** [comment] 2015-11-26 15:44
This still can be fixed in the new geocoder extension, we have time until a public release, instead of upgrading it to 0.0.2. You can go ahead and fix it in https://github.com/CartoDB/data-services/tree/master/geocoder/extension

Can tickets be moved to another repo? otherwise I would keep it in the history and avoid that overhead.

**Closed** 2015-12-01 14:33 UTC
Labels: 0 - Backlog, bug, EASY, geocoding
