### ISSUE TITLE
Search on the create map modal doesn't work correctly

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2356] opened 2015-02-19 15:19 UTC
I'm getting datasets that doesn't fit in the search term

![screen shot 2015-02-19 at 16 18 12](https://cloud.githubusercontent.com/assets/132149/6269356/f3ba306c-b852-11e4-8dd2-a57990eeb1de.png)

**Comment by xavijam** [comment] 2015-02-19 17:51
We have to check this, because I haven't been able to reproduce it.

**Comment by xavijam** [comment] 2015-02-20 14:12
Closing since we haven't reproduced it again.

**Closed by xavijam** 2015-02-20 14:12 UTC
Labels: New dashboard
