### ISSUE TITLE
Spurious vizualization step discards data from second table

### ISSUE THREAD

**Issue by cshirky** [CartoDB/cartodb#2145] opened 2015-02-10 08:44 UTC
Carto now requires the creation of a visualization whenever a second layer is created in map view.

The interface reports that data added to this second layer gets saved, when in fact it is discarded, and the newly created layer is destroyed.

Steps to reproduce.

1. Create a new table with one layer and at least one data point.
2. Go to map view.
3. Add layer, using Empty Table.
4. A dialog box pops up asking you to name a new visualization. Provide a name and submit. (Note that the upper-right button will still read Visualize, not Share.)
5. Add an element to layer #2 in Map view. (I drew a box around the original point.) Carto will show elements in both layers, and the popup above the map will show "Saving..." and then "Saved".
![screen shot 2015-02-10 at 4 32 12 pm](https://cloud.githubusercontent.com/assets/226500/6123859/74e927fa-b142-11e4-895a-3751a7c725a1.png)

6. Switch to data view. The screen will briefly switch to the table from layer #2, with an overlay reading "Setting table...", then redirect to table #1.
7. Switch back to Map view. Layer #2 has been deleted.
![screen shot 2015-02-10 at 4 39 26 pm](https://cloud.githubusercontent.com/assets/226500/6123944/9299517a-b143-11e4-9ad6-493c71af8c14.png)

The workaround is to name a visualization in step #4, then click Visualize and name a second Visualization before step #6, making the named visualization in step #4 completely spurious, and the "Saving.../Saved" dialog inaccurate.
 
The right behaviors would be:

a) Making the visualization from step #4 save any subsequent layers or, 
b) leaving the creation of a visualization to the Vizualize button, and just showing the user layered maps until they want to create a Visualization. 

I prefer a, as it's closer to the right behavior, but either a or b would be much better than this.

**Comment by saleiva** [comment] 2015-02-10 08:49
Hi Clay, this is a bug. It should behave like you say on A.
Prioritizing

**Comment by iriberri** [comment] 2015-02-10 09:10
The visualization remains with the two layers, the issue is that clicking on the "Table view" is using the URL of the first table (tablename/table) instead of the table view of the visualization (viz-id/table). So you get redirected to your actual table and you're no longer browsing your visualization (check that in your step 7 you're again in the "Visualize" process, which belongs to a table).

If you check your saved visualizations, the two layers are there. The issue is that creating a visualization from a table is not updating the links in the view.

**Comment by cshirky** [comment] 2015-02-10 09:54
Ah, got it, thanks.

If creating a visualization from adding a second layer in Map view _did_ update the links, would that also shift the upper-right button option from Visualize to Share?

**Comment by javierarce** [comment] 2015-02-10 10:02
Yes, I think so. The problem is that right now we are only changing the browser URL  and not triggering any changes in the UI:

https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/actions_menu.js#L352

So if you reload the page after you've added the second table, everything will work as expected.

**Comment by cshirky** [comment] 2015-02-10 10:17
That works. It looks like the problem is that the URL is getting altered in the URL bar, but the URL attached to Data View from within Map View of the second layer is NOT updated, and still sends me to 
https://cshirky3.cartodb.com/tables/untitled_table/table

**Comment by javierarce** [comment] 2015-02-10 15:41
@cshirky, we've pushed a fix that should solve this issue. Thanks for the nice bug report!

**Comment by javierarce** [comment] 2015-02-10 17:40
Bad news, we had to rollback the change. I'm sorry about it. I'll let you know when it's fixed.

**Comment by javierarce** [comment] 2015-03-13 11:29
We deployed a fix yesterday, so this should no longer be a problem. Sorry it took us so long to fix this issue!

**Closed by javierarce** 2015-03-13 11:29 UTC
