### ISSUE TITLE
Adding infowindow to more than one layer do not delete the infowindow upon deactivate

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#2403] opened 2015-02-20 14:51 UTC
How to reproduce:

1. Create a table with two layers (select different wizards/colors on them to be able to separate them)
1. Enable hover infowindow on both layers
1. Disable infowindow on the lower layer
1. Open the visualization in a new window (e.g. through "Share" button in top-right corner)

**Expected:** should only see hover window on the enabled layer
**Actual:** the lower layer still has the hover infowindow but with text of "No data available".

The vizjson contains the infowindow configuration for the lower layer even if it should have been removed upon disabling the infowindow for that layer.

A temporary fix/hack/workaround is to set a custom template with an empty space to not show anything on hover.

**Comment by viddo** [comment] 2015-02-20 17:59
@CartoDB/frontend how would you prioritize this one? don't know the internals of the layers to be able to say if it's easy to fix or not either

**Comment by saleiva** [comment] 2015-02-20 18:51
Uhm... this is important...

**Comment by javisantana** [comment] 2015-02-20 19:25
this bug could be:

- frontend not sending correct data to backend
- backend not disabling tooltip in the infowindow when there are no fields
- cartodb.js adding infowindows and or tooltips when there are no fields

The second one is the right place to do this since I checked frontend is sending empty fields

(this has been like this since the beginning of tooltips)

**Comment by viddo** [comment] 2015-02-23 09:19
So if it's important (and added to the scope of this sprint) then it would probably be a good idea to assign it to someone (that knows backend I guess, based on where the culprit is) so it don't fall between the cracks, but who?

**Comment by Kartones** [comment] 2015-05-05 11:58
As it is important assigning to @rafatower, but he already has a lot so might need to priorize...

**Comment by rafatower** [comment] 2015-05-26 13:22
I could not reproduce it so most likely a caching/invalidation issue, I'm closing this ticket

**Closed by rafatower** 2015-05-26 13:22 UTC
Labels: 0 - Backlog, backend, bug
