### ISSUE TITLE
After deleting maps, the thumnails doesn't show up

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2624] opened 2015-03-04 19:08 UTC
But if you refresh, it works correctly

**Comment by viddo** [comment] 2015-03-05 09:21
thumbnails == map previews?

**Comment by saleiva** [comment] 2015-03-05 11:12
yep

**Comment by viddo** [comment] 2015-03-05 11:15
@javierarce any ideas on why this could happen?

**Comment by javierarce** [comment] 2015-03-05 11:20
I'll check it.

**Comment by javierarce** [comment] 2015-03-05 11:23
It seems that [_renderConfirmDeletion](https://github.com/CartoDB/cartodb/blob/dc3cbba77d26c0acbcf5d70476199df76aaa5d55/lib/assets/javascripts/cartodb/new_dashboard/dialogs/delete_items_view.js#L72) is not being called anymore.

**Comment by viddo** [comment] 2015-03-05 11:28
But if I understand @saleiva correctly, the map previews this happens _after_ deletion is (successfully?) done, so I think this is an error on the map view and not in the delete dialog itself. Right?

Btw, that method is called, but implicitly, through the [general render](https://github.com/CartoDB/cartodb/blob/dc3cbba77d26c0acbcf5d70476199df76aaa5d55/lib/assets/javascripts/cartodb/new_dashboard/dialogs/delete_items_view.js#L52) and depending on [view model's current state](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_dashboard/dialogs/delete_items_view_model.js#L33).

**Comment by saleiva** [comment] 2015-03-05 11:33
Exactly.

**Comment by javierarce** [comment] 2015-03-05 11:34
After deleting? That's not what I've experienced :|, for me the problem for me is that if I try to delete a table, the remove dialog appear but the previews are empty.

What I'm seeing now is that [at this point](https://github.com/CartoDB/cartodb/blob/dc3cbba77d26c0acbcf5d70476199df76aaa5d55/lib/assets/javascripts/cartodb/new_dashboard/dialogs/delete_items_view.js#L78)  `this.$el.find('.MapCard')` is empty.

**Comment by javierarce** [comment] 2015-03-05 12:09
So, I've fixed the problem I described. 

How can I reproduce the problem you found, @saleiva?

**Comment by saleiva** [comment] 2015-03-05 12:15
It happens to me just by deleting a map from the dashboard, then the previews are re-requested but I never got them rendered

**Comment by javierarce** [comment] 2015-03-05 12:22
Ok, thanks, I'll check that too.

**Comment by javierarce** [comment] 2015-03-05 13:47
I can't reproduce the problem, but in my tests I saw that the previews are getting rendered twice, @viddo:
 
![delete](https://cloud.githubusercontent.com/assets/4933/6505848/5fca69e0-c346-11e4-9ba8-b9a15c1614a9.gif)

**Comment by viddo** [comment] 2015-03-05 13:51
@javierarce must be some event listener that trigger's a 2nd re-render on the listing

**Comment by javierarce** [comment] 2015-03-10 15:33
@saleiva: after testing in several browsers, I can't reproduce the original problem (although I've fixed two related bugs that were discovered thanks to this issue), so I'm closing the ticket. 

Please, reopen it if it happens again.

**Closed by javierarce** 2015-03-10 15:33 UTC
Labels: New dashboard
