### ISSUE TITLE
Custom infowindow migration misses some details importing .carto files

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11380] opened 2017-01-27 14:54 UTC
> Custom-HTML infowindows and legends may import somewhat successfully, but likely styling and width and other factors will be off/incorrect/not stay true.

**Comment by javitonino** [comment] 2017-02-02 14:42
Uhm... @andrewbt Do you have an example of what goes wrong here? We recently (a few weeks ago) did another round of improvement to importing HTML legends from editor to builder and it seems it works pretty well for me. Some advanced legends will not be displayed exactly the same (specially if they have custom styles) but the typical minor modification works pretty well.

Example:
![screenshot_20170202_154039](https://cloud.githubusercontent.com/assets/7569673/22553730/0dc8b346-e95e-11e6-9a96-2e70039a13c8.png)
![screenshot_20170202_154117](https://cloud.githubusercontent.com/assets/7569673/22553731/11354a80-e95e-11e6-81f3-3290c3d6d33d.png)

Also, keep in mind, that after migration with `.carto` the imported map will still open in the old embed and display the old legend, it will only switch to the new legend format once you open the map in Builder for the first time.

**Comment by javitonino** [comment] 2017-02-02 16:14
Sorry, I misread infowindow as legend. Tested with infowindows.

1.3.0
![screenshot_20170202_170913](https://cloud.githubusercontent.com/assets/7569673/22557472/eb815fb0-e96a-11e6-8d13-b5d8dd4c55f3.png)

[[1.3] Custom infowindows (on 2017-02-02 at 16.09.36).zip](https://github.com/CartoDB/cartodb/files/748286/1.3.Custom.infowindows.on.2017-02-02.at.16.09.36.zip)

2.0.0
![screenshot_20170202_171233](https://cloud.githubusercontent.com/assets/7569673/22557478/f00f5654-e96a-11e6-9507-21884d4ee30a.png)

I'd say that's pretty good considering the limitations of having a completely different framework for them. And it seems there is no `.carto` specific problem (it's just the migration it's like that).

**Comment by andrewbt** [comment] 2017-02-02 16:32
@javitonino I believe I tested infowindows with the "header green" and the designs like that. If those work just as well for you now, then we can probably close the issue.

We will just have to make customers aware that in migrating there's no way to keep the infowindows (and legends!) from looking exactly the same because it's backwards incompatible...

**Comment by javitonino** [comment] 2017-02-03 10:17
Ok, so with custom HTML infowindow with color headers, the migration looks pretty bad. Seems like something we could improve a little. Note for implementation: this is not `.carto` specific, it reproduces with normal migration as well (but it's easier with `.carto`)

1.3.0
![screenshot_20170203_110928](https://cloud.githubusercontent.com/assets/7569673/22587381/c0586e40-ea01-11e6-8930-b6b25f93526b.png)
[[1.3] Custom green infowindow (on 2017-02-03 at 10.09.52).zip](https://github.com/CartoDB/cartodb/files/750106/1.3.Custom.green.infowindow.on.2017-02-03.at.10.09.52.zip)

2.0.0
![screenshot_20170203_111253](https://cloud.githubusercontent.com/assets/7569673/22587397/c963abf8-ea01-11e6-968b-c282429cf72a.png)

**Comment by matallo** [comment] 2017-02-07 11:32
taking this myself

**Comment by matallo** [comment] 2017-02-07 11:41
hey, from the moment the user selects custom infowindow I don't think we should support old styles, even adding old infowindows styles in the default new infowindows css? 😱

https://github.com/CartoDB/cartodb.js/blob/50d7c78349c72306c99ada599aedf23bd2dfd01a/themes/scss/infowindow/cartodb-infowindow-default.scss#L8

of course they won't appear pretty but I think they would be a disservice for builder 😞

**Comment by matallo** [comment] 2017-02-07 11:48
having discussed this, and as we *have* to put up with the migrations I'd separate the css derived from the migration to a separate file, so we won't pollute the default infowindows

**Comment by javitonino** [comment] 2017-02-07 11:51
Then we probably should extract some code that was already in this file previous to this PR, right? So all old-infowindow CSS goes in a separate file. Also, we would have to include that CSS everywhere, right? So this is just for code organization.

**Comment by javierarce** [comment] 2017-02-08 14:49
Back to dev from acceptance due to [this comment](https://github.com/CartoDB/cartodb.js/pull/1568#issuecomment-278343105).

**Comment by javierarce** [comment] 2017-02-09 12:15
Acceptance passed!

**Comment by gfiorav** [comment] 2017-02-09 14:37
Closed via https://github.com/CartoDB/cartodb.js/issues/1568

**Closed by gfiorav** 2017-02-09 14:37 UTC
Labels: bug, export, Frontend
