### ISSUE TITLE
Exception when trying to send mail from import from query

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#7146] opened 2016-04-15 12:05 UTC
Scenario: type a query in the editor and try to create a table from the query.

Expected: everything ok.

Actual: it broke with `An unknown error has happened`.

At the very least the import process shall be resilient to not being able to send a mail. IIRC that notification mail is only sent when the import takes some time. Should be easy to fix.
```
Exception: no implicit conversion of nil into String

services/importer/lib/importer/mail_notifier.rb:58:in `basename'
services/importer/lib/importer/mail_notifier.rb:58:in `extract_file_names'
services/importer/lib/importer/mail_notifier.rb:31:in `send!'
services/importer/lib/importer/mail_notifier.rb:18:in `notify_if_needed'
app/models/data_import.rb:837:in `notify'
app/models/data_import.rb:315:in `handle_success'
app/models/data_import.rb:195:in `run_import!'
lib/resque/importer_jobs.rb:9:in `block in perform'
lib/resque/base_job.rb:21:in `call'
lib/resque/base_job.rb:21:in `run_action'
lib/resque/importer_jobs.rb:9:in `perform'
```

**Comment by iriberri** [comment] 2016-04-15 12:46
Duplicated: https://github.com/CartoDB/cartodb/issues/6296

**Comment by iriberri** [comment] 2016-04-15 12:48
Gonna close this one and assign the other one to me. Thanks! :-)

**Closed by iriberri** 2016-04-15 12:48 UTC
Labels: bug, Data-services, EASY

**Comment by rafatower** [comment] 2016-04-15 13:51
IMHO related but not duplicate. The original issue was a timeout... but ok as long as you take care of it :D

**Comment by iriberri** [comment] 2016-04-15 13:59
The other seems to be related with the mail notifier when the import fails (timeout), this one when the import succeeds. The problem is the same, so sure, I'll take care of it!

**Comment by rafatower** [comment] 2016-04-15 17:15
the focus of the other was in the timeout when importing, thus two distinct issues.

the timeout issue was fixed in the prev sprint. That makes this one surface.
