### ISSUE TITLE
Geocoding: Country-Name not trimming the blank spaces after the name

### ISSUE THREAD

**Issue by miguelarias** [CartoDB/cartodb#1703] opened 2015-01-12 11:34 UTC
"Germany_" is not being recognised as "Germany"

**Comment by rafatower** [comment] 2015-01-15 17:54
I tried with capitals, in lowercase, with trailing whitespaces and trailing underscores (`_`) and worked alright. You can import this [file](https://gist.githubusercontent.com/rafatower/50b7f821babdfd91d9c5/raw/8e48c52fe104bedc08a7fe42c09b862538cfd1e0/test_issue_1703.csv) to check it. You can see the result of geocoding that file by country_name [here](https://team.cartodb.com/u/rtorre/tables/test_issue_1703/)

It must be something else.

@miguelarias can you please provide instructions or a file to reproduce the issue? Thanks!

**Comment by miguelarias** [comment] 2015-01-16 10:57
Mmm, it was reported by a customer, I will check back with them and report if needed. Sorry.

**Comment by miguelarias** [comment] 2015-01-16 11:17
This is what they tell me: 

Debug session with the user involved went something like this:
- - saw Germany was not correctly geocoded in CartoDB
- - go into his MS Excel on Mac spreadsheet, and discovered that there
was trailing whitespace (or something looking like whitespace?)
- - remove whatever _emptiness_ there was after the 'y' in Germany
- - Excel export to CSV, then load that CSV into CartoDB -> Now Germany
was geocoded correctly

**Comment by rafatower** [comment] 2015-01-16 11:36
Weird, because the geocoder does a normalization on strings before comparing for a match.

Anyway, since we don't have more debugging information I suggest closing this ticket and re-opening it if it arises again. Do you agree?

**Closed** 2015-01-20 13:40 UTC
Labels: 0 - Backlog, bug
