### ISSUE TITLE
kml file imports as multiple geometry types in one table

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#5096] opened 2015-08-18 22:02 UTC
Here's the dataset:
http://data.gdeltproject.org/blog/mapping-global-refugee-flows/global-refugee-network-kml.kmz

Within the dataset, I get mixed types when checking the geometry:

<img width="1006" alt="screen shot 2015-08-18 at 17 58 57" src="https://cloud.githubusercontent.com/assets/1041056/9343897/dd8271fc-45d2-11e5-9f71-a4435770d61f.png">

The dashboard icon shows it as a line, but the map shows it as points by default. I can put CartoCSS rules for lines in and I get roughly the map as it appears in Google Earth:

<img width="872" alt="screen shot 2015-08-18 at 18 01 27" src="https://cloud.githubusercontent.com/assets/1041056/9343947/2f55afda-45d3-11e5-88e9-0ba255687d5d.png">

**Comment by saleiva** [comment] 2015-08-19 07:59
This should create a single map with 2 different layers (datasets) cc/ @javisantana

**Comment by Kartones** [comment] 2015-09-01 10:55
Duplicate of https://github.com/CartoDB/cartodb/issues/4556

**Comment by Kartones** [comment] 2015-09-01 10:56
Well,ok, not duplicate but relates so reopened, but #4556 is still pending discussion as this is not a trivial change to the importer...

**Comment by alonsogarciapablo** [comment] 2016-11-16 16:23
There has been no activity on this issue for more several months. We are closing it. If you think this still needs to be addressed please open a new issue.

**Closed by alonsogarciapablo** 2016-11-16 16:23 UTC
Labels: bug, Data-services
