### ISSUE TITLE
When using FME and running same procedure 2 times I get the table 2 times registered

### ISSUE THREAD

**Issue by jatorre** [CartoDB/cartodb#1840] opened 2015-01-16 23:53 UTC
I ran through FME a table migration. I canceled one process and run it again.

When I looked at CartoDB later I got the same table 2 times on the UI.

![screen shot 2015-01-16 at 6 51 02 pm](https://cloud.githubusercontent.com/assets/127803/5786309/caf428b6-9db0-11e4-9f93-4a713fc561b1.png)

So something went wrong when "cartodbfying" the table that the same table ended up 2 times on the UI.

A constrain should maybe be done on the metadata tables to not allow 2 tables with same name as it is not posssible really on the user_database.

But also to be research why it got 2 times registered.

**Comment by jatorre** [comment] 2015-01-18 17:08
The same happens with ogr2ogr by the way

**Comment by javisantana** [comment] 2015-01-18 17:16
do you have the ogr2ogr command

**Comment by jatorre** [comment] 2015-01-18 17:25
You can give it a try it through this tool
http://gc.testbox.ca/

**Comment by javisantana** [comment] 2015-01-19 12:37
I tested with the ogr2ogr command and it works as expected. There should be something different in your workflow. I can't test anything with that tool.

What is the command used ? this is mine

```
./apps/ogr2ogr --config CARTODB_API_KEY XXXX  -f CartoDB "CartoDB:rambo-test" ne_50m_urban_areas.shp
```

@jorgeas80

**Comment by andrewxhill** [comment] 2015-01-19 14:42
hey, i'm seeing the same I think outside of FME

![screen shot 2015-01-19 at 9 42 04 am](https://cloud.githubusercontent.com/assets/370259/5802078/76e7c870-9fbf-11e4-9ec1-1f094dc2f1cd.png)

I created this table via drag-drop. I tried to delete it while in tableview, it failed. i went to the dashboard and saw this duplicate listing and can't delete either

**Comment by javisantana** [comment] 2015-01-19 14:46
maybe it's related to ghost tables while importing ? @Kartones is it possible that a table is registered while it's being imported?

**Comment by Kartones** [comment] 2015-01-19 14:59
mm no, it shouldn't happen in theory, registration is the last step, everything takes place on cdb_importer schema and just at the end it gets moved to user schema and registered...

Why one of the tables ffrom @andrewxhill 's photo has description and the other not? Are we sure we're not calling twice the import or something from ths FME stuff?

**Comment by javisantana** [comment] 2015-01-19 15:02
in @andrewxhill case he is using the drag and drop import.

> gets moved to user schema and registered

Imagine ghost tables is raised in between those two steps

**Comment by Kartones** [comment] 2015-01-19 15:14
sorry, didn't read that his scenario was without FME.

Table registar does this:
```
      table.save
      table.optimize
      table.map.recalculate_bounds!
```

And table model:
```
def after_create
    ...
    $tables_metadata.hset key, 'user_id', user_id
    ...
```
As soon as data is moved to destination schema and created, it is added to metadata. Before running the `.optimize` stuff at the registar.

There's always the possibility of while data is being moved, after the table is physically present on the user schema and not yet registered, to have the `link_ghost_tables` check trigger. 
But against that right now the only easy way to avoid the scenario is to disable the check for users who have ongoing imports...

**Comment by javisantana** [comment] 2015-01-19 15:21
how the table is moved?

**Comment by andrewxhill** [comment] 2015-01-19 15:33
here is the file that messed up for me,
https://dl.dropboxusercontent.com/u/1307405/CartoDB/trash/Leadership%20in%20homing%20pigeon%20flocks%20%28Columba%20livia%29%20%28data%20from%20Santos%20et%20al.%202014%29.csv

On Mon, Jan 19, 2015 at 10:21 AM, javi santana <notifications@github.com>
wrote:

> how the table is moved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/1840#issuecomment-70510463>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com

**Comment by javisantana** [comment] 2015-01-19 15:36
for the record: the file from @andrewxhill is 30mb csv so importing this would take some time. Maybe that makes some processes longer and it's easy to reproduce

**Comment by jatorre** [comment] 2015-01-19 15:42
What FME, and ogr2ogr does too is loading the data in batches.

That means, it creates the table and keeps adding records to it.

But thats through the SQL API so I am not sure this is related to Andrew.

**Comment by saleiva** [comment] 2015-01-19 15:42
Hey guys, moving this to the current milestone since it looks like we are working on this. I'll try to move other stuff to the next sprint then.

**Comment by Kartones** [comment] 2015-01-19 15:42
:/ I just imported it and it was quick (`2015-01-19 15:38:13` to `2015-01-19 15:38:57`)  and worked fine, no duplicate created.

**Comment by javisantana** [comment] 2015-01-19 15:44
@Kartones but did you keep requesting the dashboard so ghost tables process is raised?

@jatorre but ogr2ogr does not cartodbfy until the import finish

**Comment by Kartones** [comment] 2015-01-19 15:44
uhmmm, @jatorre But they addd the data while on the cdb_importer schema no? while still importing.

If they create the table (empty) in the user schema and then try to fill it with data there might be some scenario where table gets duplicated. 

ogr2ogr has never given problems until now of duplicate tables, CartoDB importer works with the mentioned cdb_importer schema until everything is ready.

**Comment by Kartones** [comment] 2015-01-19 15:47
@javisantana you're right, I was able to reproduce it by constantly doing dashboard refreshes while importing. Now I have two tables with the same name. So at least can be reproduced.

**Comment by Kartones** [comment] 2015-01-19 16:04
After a quick local hack, this is where it was at the import process when it tried to enqueue the ghost table register:

```
2015-01-19 16:00:21 UTC: Before persisting metadata 'leadership_in_homing_pigeon_flocks_columba_liv' data_import_id: b785636b-b9a0-449e-9d9c-25ddb5ca7682
```

I'm checking the code but is at the block of saving at our ORM

**Comment by Kartones** [comment] 2015-01-19 16:33
ok, is because we hit the scenario of while the table is cartodbfied the user refreshes the UI or calls the index endpoint of /viz, triggering the enqueue of an additional name register.

I'm going to add a check of the table having the last added trigger by cartodbfication (`test_quota_per_row`) to be considered candidate for registering.

**Closed** 2015-01-20 13:44 UTC
