### ISSUE TITLE
Broken viz undefined method `scrollwheel' for nil:NilClass

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3286] opened 2015-04-20 15:32 UTC
````
NoMethodError: undefined method `scrollwheel' for nil:NilClass
1
File "/home/ubuntu/www/production.cartodb.com/releases/20150420143525/app/models/visualization/vizjson.rb", line 34 in to_poro
2
File "/home/ubuntu/www/production.cartodb.com/releases/20150420143525/app/models/visualization/member.rb", line 626 in calculate_vizjson
3
File "/home/ubuntu/www/production.cartodb.com/releases/20150420143525/app/models/visualization/member.rb", line 353 in block in to_vizjson
4
File "/home/ubuntu/www/production.cartodb.com/releases/20150420143525/app/models/visualization/member.rb", line 634 in redis_cached
5
File "/home/ubuntu/www/production.cartodb.com/releases/20150420143525/app/models/visualization/member.rb", line 352 in to_vizjson
6
File "/home/ubuntu/www/production.cartodb.com/releases/20150420143525/app/controllers/api/json/visualizations_controller.rb", line 217 in vizjson2
... 6 non-project frames
13
File "/home/ubuntu/www/production.cartodb.com/releases/20150420143525/app/controllers/application_controller.rb", line 54 in wrap_in_profiler
... 68 non-project frames
```

SB/5128927

**Comment by Hayleyr** [comment] 2015-04-21 15:27
@Kartones hi! what is the status of this? have an ansy user :)

**Comment by Kartones** [comment] 2015-04-21 15:51
Hi @Hayleyr: It will probably have to wait more days (or until I can squeeze a few minutes and fix it). If you feel it is important talk to @javisantana so he reprioritizes it higher.

**Comment by Hayleyr** [comment] 2015-04-21 17:01
@javisantana Hi! You will see that @Kartones has suggested that perhaps I refer this issue to you! We have a Coronelli user who needs to be presenting some maps with the above issue in the next few days, so I am thinking that it should definitely get some attention.

**Comment by javisantana** [comment] 2015-04-21 21:11
@Kartones yes, let's fix it

**Comment by rafatower** [comment] 2015-04-22 08:48
There's also this trace:
```
ActionView::Template::Error: undefined method `public_values' for nil:NilClass
1 File "app/views/admin/visualizations/show.html.erb", line 18 in _app_views_admin_visualizations_show_html_erb__2081754932533754588_63344380
... 32 non-project frames
34 File "app/controllers/admin/visualizations_controller.rb", line 76 in show
... 6 non-project frames
41 File "app/controllers/application_controller.rb", line 54 in wrap_in_profiler
... 68 non-project frames
```
RB/5355

**Comment by rafatower** [comment] 2015-04-22 09:15
The problem is that the `visualization.map` does not exist. It has a `visualization.map_id` with an uuid that is not found in DB. I don't know how it got to that situation.

**Comment by Kartones** [comment] 2015-04-22 09:19
uhmmm then **might** be again from the problems we had with vis deletion breaking mid-way (after deleting the map, etc.). Not 100% sure but my guess as I bugfixed similar errors

**Comment by rafatower** [comment] 2015-04-22 12:57
There's no way to recover the related table for that case automatically and I guess it's the same case for the other ~15 users affected. I will fix it manually for this particular case.

For the other cases I suggest to detect and delete the affected visualizations with a supervised rake task. They cannot be deleted manually from the new dashboard.

**Comment by rafatower** [comment] 2015-04-22 13:30
As far as I can see the table the viz was based upon was deleted time ago, presumably around June'14 so there's no way to recover that visualization.

**Comment by Hayleyr** [comment] 2015-04-22 13:45
@rafatower okay thanks very much for trying!

**Comment by rafatower** [comment] 2015-04-23 14:24
I added a script to delete inconsistent visualizations, should it be needed, but I haven't deleted any in production:
```
$ RAILS_ENV=production bundle exec rake cartodb:vizs:delete_inconsistent['diasporaalliance']

viz.name = idea_20members_20march_202014_cartodb
viz.type = table
viz.related_tables = []
viz.map_id = ef592a93-e1e6-4f74-958e-c2684d114add
About to delete. Are you sure? (y/n)
n

viz.name = IdEA Members
viz.type = derived
viz.related_tables = []
viz.map_id = 42571f0b-0ed4-4c18-ae5a-d3c9e5b9164b
About to delete. Are you sure? (y/n)
n
```
Closing this ticket.

**Closed by rafatower** 2015-04-23 14:24 UTC
Labels: 0 - Backlog, bug
