### ISSUE TITLE
Map is cached after a publish

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11094] opened 2016-12-16 20:02 UTC
### Steps to Reproduce

1. Create a map with link privacy.
2. Publish it.
3. Open it in a Chrome incognito window.
4. Change the style (feature color, for example).
5. Publish it again.
6. Reload it (Cmd + R) in the incognito window.

### Current Result

You get the old color.

_Note: sometimes it works. If you're replicating this and it works, retry a couple of times._

### Expected result

New color should've been displayed.

If you "hard-reload" (Cmd + Shift + R) it works. Firefox also works.

### Browser and version

Chrome  54.0.2840.98 (64-bit)

### Additional info

The problem seems to be the caching of the map instantiation.  That request returns `Cache-Control:public,max-age=300,must-revalidate`  header. Chrome returns next requests straight from disk. Opening a different browser, it works.

After some minutes it works in Chrome as well.

**Comment by juanignaciosl** [comment] 2016-12-19 07:39
cc @CartoDB/builder-backend @rochoa @saleiva

**Comment by javisantana** [comment] 2016-12-19 08:34
we should avoid to send caching headers to the client but cache in varnish if possible (since it contains invalidation headers)

I think is totally wrong to send any cache header (it says must-revalidate but I don't know if that takes effect after a "public" control)

**Comment by javitonino** [comment] 2016-12-19 08:43
`must-revalidate` only acts when the cache expires. After the cache expired, the browser makes a new request for fresh content. If that request fails, without `must-revalidate`, it returns the cached version. With `must-revalidate` it returns an error. So I don't think that part is an issue here.

**Comment by rochoa** [comment] 2016-12-19 10:19
@juanignaciosl Can you be more specific about what request is returning that cache header?

**Comment by rochoa** [comment] 2016-12-19 10:26
Do you mean the `/api/v1/map/named/:template_id/jsonp?callback=cb...` request?

**Comment by javitonino** [comment] 2016-12-19 10:28
Yup @rochoa, it's that one.

**Comment by rochoa** [comment] 2016-12-19 11:03
@javisantana We introduced that header a while ago: https://github.com/CartoDB/Windshaft-cartodb/pull/226, to be more aggressive with users changing too frequently the styling/data (election maps).

With the builder, all embeds use named maps, where the problem is way more obvious, as the URL is fixed, as opposed to using SQL + CartoCSS directly.

The problem is related to the max-age + must-revalidate combination, because if you remove the max-age but keep public + must-revalidate you get the "expected behavior".

My proposal is to stop exposing that named map instantiation header (max-age) to the client (browser) as you are already proposing, but we need to do some changes so Varnish is somehow hinted about so it can cache it, something in the line of https://github.com/CartoDB/Windshaft-cartodb/issues/334 but for map instantiations.

**Comment by javisantana** [comment] 2016-12-20 08:45
ok, sounds fine.

We should try to follow fastly guidelines for header caching (because I think they are reasonble). FOr example https://docs.fastly.com/guides/tutorials/cache-control-tutorial says to use `Surrogate-Control` so specify varnish/faslty headers and keep cache-control for the browser.



cc @zenitraM @luisbosque

**Comment by juanignaciosl** [comment] 2016-12-21 12:35
_sorry about issue management noise_ . @rochoa this is for Maps API then, isn't it? Should this be moved there, or can we somehow help you?

**Comment by ztephm** [comment] 2016-12-21 16:02
@CartoDB/support please notify Enterprise S/B 10859873 when fixed.

FYI I commented S/B 10859873 ticket w/animated gif example if we need - not posting private data b/c public repo.

**Comment by oriolbx** [comment] 2016-12-22 10:59
The changes of the cached map are not visible to the users that have the map shared within the org.

**Comment by jorgesancha** [comment] 2016-12-29 10:05
Bumping importance of this one on the board

**Comment by rochoa** [comment] 2017-01-03 17:29
This should be fixed after changing the configured max-age Cache-Control directive for Named Maps instantiations.

P.S.: There is a broader discussion about Cache-Control header and how to deal with intermediate caches at https://github.com/CartoDB/Windshaft-cartodb/pull/615.

**Closed by rochoa** 2017-01-03 17:29 UTC
Labels: bug
