### ISSUE TITLE
WMS with valid XML can't be imported

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#5561] opened 2015-09-16 20:20 UTC
@viddo (or @saleiva please let us know if this goes elsewhere, thanks)

Please ref S/B 6651888

Expected:
User would be able to use this WMS as a basemap:

XML file url:
http://sit.cittametropolitana.na.it/arcgis/services/poi/MapServer/WMSServer?request=GetCapabilities&service=WMS

WMS being added:
http://sit.provincia.napoli.it/arcgis/services/poi/MapServer/WMSServer

Happening:
"Data download timed out." error

Is this an error on our side or from where user's getting the url?

**Comment by viddo** [comment] 2015-09-17 08:38
> "Data download timed out." error

Where does this error appear/happen? Can you provide more detailed steps-to-reproduce?

> WMS being added:
> http://sit.provincia.napoli.it/arcgis/services/poi/MapServer/WMSServer

This URL doesn't work, testing with `curl` yields _curl: (6) Could not resolve host: sit.provincia.napoli.it_.

According to our [WMS proxy](https://cartodb-wms.global.ssl.fastly.net/api/check?url=http%3A%2F%2Fsit.cittametropolitana.na.it%2Farcgis%2Fservices%2Fpoi%2FMapServer%2FWMSServer%3Frequest%3DGetCapabilities%26service%3DWMS%3Frequest%3DGetCapabilities%26service%3DWMS&type=wms) the XML file is not a valid capabilities doc (returns _"error": "not a valid capabilities document"_), I'd need @CartoDB/systems to know the reason since I don't have access to the logs

**Comment by iriberri** [comment] 2015-09-17 09:07
I think there's a confusion here.

WMS is not a supported format for importing data to CartoDB. It can be used to add WMS layers as a custom basemap, but it cannot be used as a URL to import.

**Comment by viddo** [comment] 2015-09-17 09:09
> User would be able to use this WMS as a basemap:

@iriberri :point_up:, but @ztephm can probably clarify if the user was trying to import or adding a basemap

**Comment by iriberri** [comment] 2015-09-17 09:17
According to the support thread, it's been always an import error. Adding WMS basemaps does not give any error ID neither :-)

**Comment by iriberri** [comment] 2015-09-17 09:47
We have studied this issue again just focusing in the WMS basemap approach, and the Capabilities of the WMS are announcing 3 possible projections: 

CRS="CRS:84"
CRS="EPSG:4326"
CRS="EPSG:102113"  info [here](https://epsg.io/102113)

CRS:84 is equivalent to EPSG:4326 but changing the axis from Lat-Long to Long-Lat.

**Comment by nicoali** [comment] 2015-09-17 14:20
if can help same thing happens with this WMS:
http://sit.regione.campania.it:80/arcgis/services/cartografia_base/MapServer/WMSServer
 
with this error code:
9c6fd585-ec56-4903-b595-9c13751e1d75

i've tested this WMS in Qgis and arcgis and works fine i can see the layers.

**Comment by ztephm** [comment] 2015-09-17 15:05
She tried importing so that's why I sent the error. We're clarifying with her that it needs to be used via 'Change basemap' but in the meantimej it also fails that way. @dani checked it out & XML looked ok?

**Comment by nicoali** [comment] 2015-09-17 15:29
if i import as basemap all is fine for this WMS:
http://sit.regione.campania.it:80/arcgis/services/cartografia_base/MapServer/WMSServer

i can see and import layers as basemap.

I hoped that i could import also datas.

**Comment by iriberri** [comment] 2015-09-17 16:42
@nicoali, unfortunately WMS is not of our supported formats, as we are focused on importing vector data. You can check more details about this here: http://docs.cartodb.com/cartodb-editor.html#supported-file-formats


As the WMS seems to be working, I'm closing the issue. Please, don't hesitate to ask us any other doubt or question you might have in our support channel or directly opening a new issue in GitHub if you think it's due to a technical issue.

**Closed by iriberri** 2015-09-17 16:42 UTC
