### ISSUE TITLE
Namedplaces guessing errors

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3024] opened 2015-04-06 12:28 UTC
**Syntax errors** [[1](https://rollbar.com/vizzuality/CartoDB/items/5318/), [2](https://rollbar.com/vizzuality/CartoDB/items/5016/)]

```
create_the_geom_from_namedplaces_guessing failed: syntax error at or near "s"
["/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/sql-api/sql_api.rb:48:in `raise_if_error'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/sql-api/sql_api.rb:35:in `handle_response'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/sql-api/sql_api.rb:28:in `fetch'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:76:in `block in namedplaces_guess_country'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:72:in `each'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:72:in `namedplaces_guess_country'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:35:in `run!'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/georeferencer.rb:161:in `block in create_the_geom_from_namedplaces_guessing'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/importer_stats.rb:56:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/georeferencer.rb:159:in `create_the_geom_from_namedplaces_guessing'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/georeferencer.rb:50:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/loader.rb:96:in `post_ogr2ogr_tasks'"
```

**cannot determine type of empty array** [[1](https://rollbar.com/vizzuality/CartoDB/items/5017/)]

```
["/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/sql-api/sql_api.rb:48:in `raise_if_error'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/sql-api/sql_api.rb:35:in `handle_response'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/sql-api/sql_api.rb:28:in `fetch'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:76:in `block in namedplaces_guess_country'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:72:in `each'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:72:in `namedplaces_guess_country'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:35:in `run!'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/georeferencer.rb:161:in `block in create_the_geom_from_namedplaces_guessing'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/importer_stats.rb:56:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/georeferencer.rb:159:in `create_the_geom_from_namedplaces_guessing'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/georeferencer.rb:50:in `run'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/loader.rb:96:in `post_ogr2ogr_tasks'"
```

**create_the_geom_from_namedplaces_guessing failed: undefined method `[]' for nil:NilClass** [[1](https://rollbar.com/vizzuality/CartoDB/items/5014/)]

```
["/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/content_guesser.rb:138:in `country_proportion'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:62:in `country_proportion'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:48:in `country_column'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:32:in `run!'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/georeferencer.rb:161:in `block in create_the_geom_from_namedplaces_guessing'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/importer_stats.rb:56:in `timing'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/georeferencer.rb:159:in `create_the_geom_from_namedplaces_guessing'"
```

**can't convert nil into String** [[1](https://rollbar.com/vizzuality/CartoDB/items/5019/)]

```
["/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:74:in `+'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:74:in `block (2 levels) in namedplaces_guess_country'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:74:in `map'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:74:in `block in namedplaces_guess_country'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:72:in `each'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:72:in `namedplaces_guess_country'", "/home/ubuntu/www/production.cartodb.com/releases/20150406101751/services/importer/lib/importer/namedplaces_guesser.rb:35:in 
```

**Comment by rafatower** [comment] 2015-04-24 08:59
The bug can be reproduced with this csv dataset:
```
country,city
Cote d'Ivoire,Yamoussoukro
Cote d'Ivoire,Abidjan
Ghana,Kumasi
```
It is due to unescaped quotes in the input.

**Comment by rafatower** [comment] 2015-04-24 15:35
Some of the warnings are due to imports that end up in tables with 0 rows.

**Comment by rafatower** [comment] 2015-04-27 08:54
I think all cases are fixed. I'm closing this ticket. I'll take another look at the error log by the end of the day to confirm and reopen if needed.

**Comment by rafatower** [comment] 2015-04-27 13:14
There's still one failure:
https://rollbar.com/vizzuality/CartoDB/items/5014/
```
undefined method `[]' for nil:NilClass

services/importer/lib/importer/namedplaces_guesser.rb:86:in `proportion'
services/importer/lib/importer/namedplaces_guesser.rb:68:in `guess_with_country_column'
services/importer/lib/importer/namedplaces_guesser.rb:33:in `run!'
services/importer/lib/importer/georeferencer.rb:163:in `block in create_the_geom_from_namedplaces_guessing'
```

**Closed** 2015-04-28 07:39 UTC
Labels: 2 - Working, backend, bug
