### ISSUE TITLE
Start using assets modal within organization profile

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11009] opened 2016-12-12 12:13 UTC
In order to start implementing proper things for this modal in this page, we should use the modal implemented in the builder side [here](https://github.com/CartoDB/cartodb/pull/11005/files) (remember the feature flag).

![screen shot 2016-12-12 at 13 11 16](https://cloud.githubusercontent.com/assets/132146/21099071/7e93070e-c06c-11e6-88f4-ccd545aff39b.png)
![screen shot 2016-12-12 at 13 11 09](https://cloud.githubusercontent.com/assets/132146/21099072/7e9621dc-c06c-11e6-955f-b59a6b37e1fd.png)

Things to take into account:

- Select and remove icons behaviour should be addressed [here](https://github.com/CartoDB/cartodb/issues/11006), *not in this issue*.
- This list should be only visible for organization owners.

**THIS TICKET CAN'T BE STARTED WITHOUT http://github.com/CartoDB/cartodb/issues/11007.**

**Comment by ivanmalagon** [comment] 2017-01-24 15:32
Moving it back to `development` because of this -> https://github.com/CartoDB/cartodb/pull/11306#issuecomment-274833378

**Comment by ivanmalagon** [comment] 2017-01-24 16:13
Getting this to fix those 2 problems and a possible related one. The `organization users` tab is not rendered and we have to take a look on what the problem is.

**Comment by xavijam** [comment] 2017-01-25 11:02
Don't forget to check this behaviour with one of the design team involved (or @saleiva).

**Comment by ivanmalagon** [comment] 2017-01-25 12:02
Pushed a commit for the issues found on acceptance.

Passing to Code Review again.

**Comment by ivanmalagon** [comment] 2017-01-25 13:24
Hi @brittanymicek 

Do you mind reviewing the next copy?

![screen shot 2017-01-25 at 14 11 27](https://cloud.githubusercontent.com/assets/1078228/22292023/a335f368-e309-11e6-9833-6a4ef9686b62.png)

This pops up when an administrator wants to delete some marker icons. We want to warn the user about two outcomes:
- The icons to delete can be already in use in some maps. If she delete them, those maps will break.
- The icons cannot be recovered once they're deleted.

Thank you!

**Comment by ivanmalagon** [comment] 2017-01-25 14:10
After design review, there are some minor fixes:

- Got rid of modal tab: it has no sense until we have the Dropbox tab.
- Bad margin in modal fixed.
- If only one icon was meant to occupy a new line, it was placed in previous line, breaking the harmony (all lines with X icons, last line with X + 1 icon).

**Closed** 2017-01-25 17:01 UTC
Labels: Frontend

**Comment by brittanymicek** [comment] 2017-01-25 19:04
@ivanmalagon sure!

**Comment by brittanymicek** [comment] 2017-01-25 21:10
@ivanmalagon 

NEW COPY:
You are deleting 4 icons from your organization.
Once icons are deleted they cannot be recovered. Any maps within the organization that use these icons will be adversely affected. Please be sure before proceeding.
