### ISSUE TITLE
Add sql tag clickable

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#10871] opened 2016-11-29 10:01 UTC
![image](https://cloud.githubusercontent.com/assets/1214201/20705343/da865d12-b622-11e6-995c-b5ce70abb4e4.png)

**Comment by xavijam** [comment] 2016-11-29 13:17
Yeah, I agree with you, it would be super convenient.

**Comment by csobier** [comment] 2017-04-18 19:04
I found this issue when I was searching for the SQL tag... (which is clickable now, BTW). Can you advise about the intended behavior though?

- Is this SQL tag only supposed to appear for map layers with Analysis applied?
(I know that the SQL tag also appears when importing .carto files from other accounts, but that is another issue).
- I was expecting that if I apply a SQL query from the DATA tab of a selected layer, this SQL tag would appear in the LAYERS pane.
  - If you run an `UPDATE` or `INSERT` statement in the SQL view, the SQL code disappears after being applied, and no SQL tag is displayed from the LAYERS pane.  (**Note**: Clicking the undo button from the SQL view displays the applied statement though)
  - If you run a `SELECT` query, the statement remains in the the SQL view and the SQL tag appears in the LAYERS pane.

tagging @noguerol for transparency (since I was bugging him about this ;-)

**Comment by noguerol** [comment] 2017-04-19 13:02
SQL tag appears on SELECT because is a non destructive query, while UPDATE and INSERT are directly applied to the table.

**Comment by csobier** [comment] 2017-04-19 14:21
Okay, thanks for confirming the expected behavior. 

@xavijam , did you want to close this issue? (Since the SQL tag is clickable)

**Comment by noguerol** [comment] 2017-04-19 16:20
Yep, lets close it.

**Closed by noguerol** 2017-04-19 16:20 UTC
Labels: feature
