### ISSUE TITLE
Bug when you try to edit metadata in a map with a dataset that has several geometry columns

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/cartodb#1959] opened 2015-01-27 14:43 UTC
The error is when you try to edit medata using a dataset have two geometries columns.
![bug_op_edit_data](https://cloud.githubusercontent.com/assets/3958416/5920110/4de8da8c-a63a-11e4-910d-7f1aae8e3492.gif)

The dataset that I was using is [this](https://dl.dropboxusercontent.com/u/22131567/world_borders_2.csv) (wkb_geometry in this case)

The line: 
>         this.row.isGeomLoaded() ? this._chooseGeom() : this._loadGeom()

fails because this.row is undefined. 
 
The reason is because it's trying to work with this new geometry column data, because the_geom column was avoid before.

**Comment by Xatpy** [comment] 2015-01-27 14:43
@javisantana I hope that I explained correctly the issue.

**Comment by viddo** [comment] 2015-03-12 10:06
Closing, I can't reproduce. @Xatpy mentioned that there were another bug related with the importer that was probably the root cause to this error, so it got fixed together with that one, see #2107

**Closed by viddo** 2015-03-12 10:06 UTC
Labels: bug, Frontend
