### ISSUE TITLE
Deleting dataset does not invalidate varnish cache

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#5516] opened 2015-09-15 08:28 UTC
Same steps as in #5515:

- create a new empty dataset from dashboard
- add a new column
- rename a column
- delete the dataset
- create a new empty dataset again

Actual result:
GET requests to the SQL API returns old column fields (e.g. one of the renames from previous steps). 

Expected result:
GET requests should return correct data of the new dataset (e.g. the column fields).

For what it's worth, it could be because the new dataset will have the previously-deleted-dataset ("_untitled_table_") which is probably cached in varnish.

**Comment by gfiorav** [comment] 2015-09-15 09:15
I looked into the invalidation code and it seems to be called upon any modification!

Since we are unable to reproduce the problem atm let's close this issue until it reappears. Could you close it?

Thanks @viddo! :smile:

**Comment by viddo** [comment] 2015-09-15 10:01
Have not been able to reproduce it again either. :( So yes, let's close this, whoever reads this and manages to reproduce it please feel free to re-open it.

**Comment by gfiorav** [comment] 2015-09-15 16:01
@javisantana pointed out that there's more to this so I reopen the issue:

I'm seeing this code:
https://github.com/CartoDB/cartodb/blob/master/app/models/table.rb#L598-L613

```ruby
  def after_destroy
    # Delete visualization BEFORE deleting metadata, or named map won't be destroyed properly
    @table_visualization.delete(from_table_deletion=true) if @table_visualization
    Tag.filter(:user_id => user_id, :table_id => id).delete
    remove_table_from_stats
    invalidate_varnish_cache
    cache.del geometry_types_key
    @dependent_visualizations_cache.each(&:delete)
    @non_dependent_visualizations_cache.each do |visualization|
      visualization.unlink_from(self)
    end
    remove_table_from_user_database unless keep_user_database_table
    synchronization.delete if synchronization

    related_templates.each { |template| template.destroy }
  end
```

I'll debug it a bit to all places where invalidation is used see if I can see any exception point.

**Comment by javisantana** [comment] 2015-09-16 07:12
The thing in that code: varnish is invalidated *before* the table has been removed from user database, that means if we execute a query to the SQL just in between is invalidated and is removed it will be cached and never invalidated.

The invalidation when a table is created should be managed by the extension as we always talked cc @rochoa

**Comment by gfiorav** [comment] 2015-09-16 07:21
Ok I see! I'll try to reproduce by stopping the execution with the debugger in between those operations and launching an SQL API command. Just to make sure we can reproduce to test the fix later on.

The fix has to be done in the extension then?

**Comment by javisantana** [comment] 2015-09-16 07:28
No, it's been there since ages but never actually did it. We can try to minimize the problem placing the invalidation just after removing the table but in any case we will have a race condition

**Comment by gfiorav** [comment] 2015-09-16 09:45
@javisantana should we try to mitigate it by reordering then?

**Comment by rochoa** [comment] 2015-09-16 09:55
For the time being I would try that. Add an issue to cartodb-postgresql about this so we can manage this situations at extension level.

**Comment by rafatower** [comment] 2015-09-18 17:18
It is a problem with varnish invalidations that only affects organizations with a dash in the name:

t is the table and `t.varnish_key` is the key used for invalidation:
```ruby
irb(main):035:0> puts t.varnish_key
^cartodb_user_b3ab0740-9d0d-42bf-8899-90b8d63c5f14_db:(.*metrics-user\.test_bug_varnish.*)|(table)$
```

and this is the keys used to cache the queries from the frontend:
```
TxHeader     c X-Cache-Channel: cartodb_user_b3ab0740-9d0d-42bf-8899-90b8d63c5f14_db:"\"metrics-user\".test_bug_varnish"
```
Mind the quotes. I'm hotfixing this.

cc/ @rochoa @viddo @javisantana

**Comment by javisantana** [comment] 2015-09-21 08:06
rochoa +1

**Closed** 2015-09-21 09:38 UTC
Labels: backend, bug
