### ISSUE TITLE
Map created from file without geometries gets centered in Null Island

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#4616] opened 2015-07-22 10:15 UTC
**Steps:**

* Import [this CSV](https://gist.githubusercontent.com/iriberri/40b63cbc775f805b5eaf/raw/206bb50496cb439f4a6eee7e218c971730a9942f/examplessssssss.csv)

Resulting map in the Editor:

![image](https://cloud.githubusercontent.com/assets/1730320/8823193/231a7d2c-306b-11e5-97e9-360ac334340c.png)

Viz.json info (https://vmg.cartodb.com/viz/3f9726e6-305a-11e5-966b-0e5e07bb5d8a/map):

````
[
[
0,
0
],
[
0,
0
]
],
center: "[30, 0]",
zoom: 3,
````

After refreshing the page, the map is always being shown near Null Island and zoom 18.

cc @javisantana

**Comment by javisantana** [comment] 2015-07-22 10:26
@viddo not sure if the change we did yesterday about the bounds calculation is related

**Comment by javisantana** [comment] 2015-07-22 10:31
anyways, the bounding box calculated server side does not match with center and zoom

**Comment by viddo** [comment] 2015-07-22 10:51
yeah, confirmed that the change is the culprit indeed :(

Having a 2nd look, actually not sure if we should return zoom or min zoom (like 1) instead. either way we need would need to change this or the [other use-case](https://github.com/CartoDB/cartodb/issues/4552) to make them work as desired. What do you think?

**Comment by viddo** [comment] 2015-07-22 12:34
On a 2nd (or rather 3rd) look, I'll revert this change to fix this bug, and I'll look for another solution to the other use-case (#4552).

**Comment by javisantana** [comment] 2015-07-22 12:39
not sure if your fix actually shown a backend side bug (not calculating bbox properly)

**Comment by javisantana** [comment] 2015-07-22 12:44
@Kartones could you give more light about why the bbox is [[0,0], [0,0]] ?

**Comment by iriberri** [comment] 2015-07-27 12:35
bump

**Comment by Kartones** [comment] 2015-07-27 12:46
I recall answering that no idea because that bbox code was from 2012, but anyway, replying again. I released https://github.com/CartoDB/cartodb/pull/4652 that should fix "backend part".

**Comment by javisantana** [comment] 2015-07-28 06:48
then this should be fixed

**Comment by javisantana** [comment] 2015-07-28 09:28
ok, ``view_bounds_*`` are still [0,0] so only when importing a dataset wihtout geometry. When you create an empty map they are 

```
view_bounds_ne:
0: 85.0511
1: 85.0511

view_bounds_sw
0: -85.0511
1: -85.0511
```

basically I don't know why we have two variables storing the bbox, we are using view_bounds to set the map bounds. ``bounding_box`` is something we are moving around without using it :(

**Comment by Kartones** [comment] 2015-07-28 09:33
uhm, ok, then the map.recalculate bounds! probably is faulty on Ruby code, and when map has no geometries wipes out even the default value. I'll take a look.

About the `bounding_box` I have even less idea, in fact the code does things like building the view_bounds from the bounding box sometimes:
```
def view_bounds_data
        if view_bounds_sw.nil? || view_bounds_sw == ''
:         bbox_sw = DEFAULT_OPTIONS[:bounding_box_sw]
```
So I don't know why the duplication... I can fix the 0,0 issue and if you want create another ticket to research and eliminate the duplication.

**Comment by javisantana** [comment] 2015-07-28 09:35
https://github.com/CartoDB/cartodb/issues/4717

**Closed** 2015-07-29 11:36 UTC
Labels: 3 - Done, bug
