### ISSUE TITLE
Editor content blocks are not getting all the available space

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7463] opened 2016-05-23 12:52 UTC
![screen shot 2016-05-23 at 14 51 24](https://cloud.githubusercontent.com/assets/132146/15471382/f1e49892-20f5-11e6-922a-68d30c2db36b.png)

cc @piensaenpixel

**Comment by nobuti** [comment] 2016-05-23 13:40
Not sure wether it's the same, but in that view the scroll view was not applied correctly. I fixed it in https://github.com/CartoDB/cartodb/commit/66277f3e415d9d6eac3a839754677d0d242116df. I can't reproduce it in others views, branch @xavijam?

**Comment by xavijam** [comment] 2016-05-23 13:41
Don't worry, if you have fixed there, let's close the ticket ;).

**Comment by xavijam** [comment] 2016-05-23 13:41
I spotted it in production by the way.

**Comment by nobuti** [comment] 2016-05-23 14:03
Fixed in https://github.com/CartoDB/cartodb/commit/b5bce87ef965251bd6bd2559814685bdae4f2545

**Closed by nobuti** 2016-05-23 14:03 UTC
Labels: bug
