### ISSUE TITLE
Don't show auto-style button on widgets connected to hidden layers

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11137] opened 2016-12-27 13:40 UTC
### Steps to Reproduce
1. Create a map with 2 layers and add some widgets for some columns of both layers (as you can see in the [Attached .CARTO](https://github.com/CartoDB/cartodb/files/674180/Madrid.Airbnb.Listings.ct.on.2016-12-27.at.13.37.43.carto.zip) sometimes it makes sense)
2. Click on the auto-style button for one of the layers

### Current Result
Nothing happens - as it should be - but from the UX perspective is missleading

### Expected result
Auto-style button should be hidden on those widgets that are attached to a hidden layer

**Comment by MariaCheca** [comment] 2017-01-09 15:37
This issue is blocked as we need to discuss some deep-insights concerns with @alonsogarciapablo to determine if it makes more sense to add the changes to avoid or not the auto-styling in the widget model on cartodb or deep-insights.js.

**Comment by MariaCheca** [comment] 2017-01-12 15:14
This ticket has already a PR made (https://github.com/CartoDB/deep-insights.js/issues/508). Tests in deep-insights.js are not passing right now, I remove my assignment because there is a problem with a bug not always showing up in https://github.com/CartoDB/cartodb/pull/11187 that is urgent.

**Comment by nobuti** [comment] 2017-01-13 10:32
Picking this.

**Comment by nobuti** [comment] 2017-01-14 10:28
I found that making the layer hidden, the autostyle is put to false, but the cartocss generated by the autostyle is not reset, so when is back to visible, the layer remains in a weird state. Not sure if this the behaviour we desire @saleiva @xavijam.

**Comment by saleiva** [comment] 2017-01-14 11:45
When disabling a layer we shouldn't reset the cartocss until we apply
auto-style in other widget or change the style in the editing panel IMO

**Comment by nobuti** [comment] 2017-01-16 11:20
PR created in https://github.com/CartoDB/cartodb/pull/11255, adding the `don't-merge-yet` label until https://github.com/CartoDB/deep-insights.js/pull/509 is merged, in order to fix the package and the shrinkwrap.

**Comment by javitonino** [comment] 2017-01-16 15:21
I did acceptance for this. I tested a lot of thing in builder and embed and pretty much everything works as expected 👏 

I found an issue which I'm reporting as a separate ticket as it also happens in production. It seems pretty related to this PR (it involves autostyle and layer visibility) so you may want to check it out -> https://github.com/CartoDB/cartodb/issues/11258

Moving to deploy unless you tell me otherwise.

**Comment by javitonino** [comment] 2017-01-16 15:26
After a quick chat, it seems we are addressing https://github.com/CartoDB/cartodb/issues/11258 in this PR as well. Moving back to development.

**Comment by xavijam** [comment] 2017-01-16 15:58
Hey, checking the problem with @nobuti, we have noticed that preserving the auto-style when a layer is hidden is giving us some problems, due to (by default) when there is a "layer" change, we disable the autostyle. Do you mind @saleiva if we follow the same behaviour?

**Comment by saleiva** [comment] 2017-01-18 14:00
So about this... it is pretty tricky. Can we estimate the cost of doing this in the natural way?

**Comment by nobuti** [comment] 2017-01-19 18:17
I've introduced an option to preserve auto style when saving, that hopefully let us to achieve it. Back to CR again.

**Comment by ivanmalagon** [comment] 2017-01-26 17:04
Found an issue while doing this acceptance.

Hiding layer also hides autostyle button until you change layers position.

### Steps to reproduce
- Get a visible layer with a widget.
- Check that autostyle buttons appears in the widget.
- Hide that layer.
- The autostyle button also hides.
- Move layer to another position, dragging it on top of another one, for example.
- Toggle layer visibility.
- The button doesn't hide anymore.

A sample of this behaviour:

![hide-autostyle](https://cloud.githubusercontent.com/assets/1078228/22341614/c3c6711e-e3f1-11e6-861b-42c85333ad4a.gif)

**Comment by xavijam** [comment] 2017-01-26 17:07
Oh, that's a good one, move it back to development please.

**Comment by xavijam** [comment] 2017-01-30 14:13
I've found the problem here. When we move a layer, it is removed from the collection and then re-added again in the correct position. That triggers a problem with the dataview model and layer link. That reference is broken and that's the reason why the "button" is not visible/not visible anymore.
cc @alonsogarciapablo

**Comment by xavijam** [comment] 2017-01-30 16:41
Fixed in https://github.com/CartoDB/cartodb.js/pull/1563.

**Comment by xavijam** [comment] 2017-01-31 15:01
Deployed

**Closed by xavijam** 2017-01-31 15:01 UTC
Labels: bug, Frontend
