### ISSUE TITLE
UI does not show search link in category widget

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#12416] opened 2017-06-30 08:59 UTC
### Context
I was testing something else, related with widgets and found out that *my* chrome browser in *my* ubuntu linux does not show the search link in category widgets.

### Steps to Reproduce
1. Open this embed in my computer with my chrome: https://team.carto.com/u/rtorre/builder/7eee47fb-3a67-4491-b137-abe037ddb296/embed

### Current Result
Here is a screenshot of builder showing the element that is not rendered. CSS properties are computed in such a way it has `height = 0` for some reason, as shown in the screenshot.

![image](https://user-images.githubusercontent.com/1914276/27727962-db2825c4-5d80-11e7-878f-e0ed31d8e17b.png)

### Expected result
This is how it works in all other browsers (chrome or firefox, as long as they are not my chrome in my linux):
![image](https://user-images.githubusercontent.com/1914276/27728170-87cffe1e-5d81-11e7-91d0-495205a6a088.png)

### Browser and version
```
Google Chrome	59.0.3071.115 (Official Build) (64-bit)
Revision	3cf8514bb1239453fd15ff1f7efee389ac9df8ba-refs/branch-heads/3071@{#820}
OS	Linux
JavaScript	V8 5.9.211.38
Flash	26.0.0.131 /home/rtorre/.config/google-chrome/PepperFlash/26.0.0.131/libpepflashplayer.so
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
Command Line	/usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end
Executable Path	/opt/google/chrome/google-chrome
Profile Path	/home/rtorre/.config/google-chrome/Default
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
```

### .carto file
This is the base .carto file that I worked with, but it shouldn't matter that much which one to use:

[An_overview_of_Nigeria_institutions__on_2017-03-13_at_11.51.55_.zip](https://github.com/CartoDB/cartodb/files/1114602/An_overview_of_Nigeria_institutions__on_2017-03-13_at_11.51.55_.zip)

### Additional info
No error in requests nor in js console.

I asked several colleagues with linux machines to try the same embed with chrome. I was the only one having that problem.

Consider this low priority for the moment, as I'm the only one affected and I have a workaround. But lets keep track of especially it in case we find out there are more people affected.

cc/ @jsanz and @xavijam for awareness.

**Comment by rafatower** [comment] 2017-06-30 10:45
I think I found the error but I don't know how to continue the debugging session w/o help from frontend:

![image](https://user-images.githubusercontent.com/1914276/27732278-cb2d5404-5d90-11e7-84d9-90b5a307b42b.png)

It is failing in this line, which is weird:

https://github.com/CartoDB/deep-insights.js/blob/d340b02989df36eb771df2adfbea4a6b704cf9b4/src/api/create-dashboard.js#L102

Out of curiosity, where are those traces logged? I don't see anything in the console.

**Comment by ztephm** [comment] 2017-07-05 14:47
Happening for S/B 12983454 in 
* same as above Google Chrome 59.0.3071.115 (Build oficial) (64 bits)
* Firefox 52.0.1 (32-bit)

**Comment by rafatower** [comment] 2017-07-05 14:54
@ztephm the operating system details can be relevant as well. Could you please add any info about Linux flavor and version? cheers!

**Comment by saleiva** [comment] 2017-07-06 13:30
this happened to me several times in the past, but I couldn't find a pattern to replicate it

**Comment by ztephm** [comment] 2017-07-06 14:03
@rafatower client's using Windows 7 Pro SP1 64bit

**Comment by michellechandra** [comment] 2017-07-31 17:53
An Enterprise user is reporting this issue using Windows10 (Surface Pro4) -  Chrome Version 59.0.3071.115.

S/B: 13289673

@rafatower - any update on this issue?

**Comment by rafatower** [comment] 2017-08-01 07:57
I reported the bug the best I could and I investigated the root cause and documented my findings, but as stated above I cannot pursue it any further w/o some help from others.

I added it to the response kanban (as candidate) for prioritization cc/ @noguerol

**Comment by piensaenpixel** [comment] 2017-08-02 07:29
it happened to me two or three time yesterday in Firefox.

**Comment by ivanmalagon** [comment] 2017-08-31 15:22
Cannot reproduce.
Tested in Mac with Chrome, Safari and Firefox.
Tested in Windows 7 with Chrome 59, Firefox and IE11.
No luck on getting the error.

Please, as soon as any of you is experiencing this issue at the office (so I can go to your computer and debug it), let me know.

**Comment by noguerol** [comment] 2017-08-31 15:57
Maybe @ramiroaznar can help.

**Comment by ramiroaznar** [comment] 2017-08-31 16:15
Sorry, I was not able to reproduce it. I can say the same with the autostyle button. I have not been able to find STR for that one.

**Comment by noguerol** [comment] 2017-09-01 09:44
Ok, I then suggest we close this until it happens again.

**Closed** 2017-09-04 07:25 UTC
Labels: bug, Frontend
