### ISSUE TITLE
Maps failing due to source tables with long names

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3808] opened 2015-05-27 14:07 UTC
Steps:

* Go to any of your tables (not important ones, please) that contains geometries.
* Rename it with a name of 63 characters, like: `cpre_charter_to_save_our_countryside_comments_ex_do_not_contact`
* Go to map view, nothing is drawn.
* Check the errors.
````
{"errors":["Error: could not fetch affected tables and last updated time: relation \"public.cpre_charter_to_save_our_countryside_comments_ex_do_not_\" does not exist"]}
`````

The tablename in the error is shorter that the actual table name, which means that we're trimming the name somewhere and the source table cannot be found afterwards.

@javisantana @Kartones

**Comment by javisantana** [comment] 2015-05-27 14:08
https://github.com/CartoDB/cartodb/pull/3762

**Comment by Kartones** [comment] 2015-05-27 14:12
@rafatowerthis seems related with the fix that @javisantana mentions (#3762)

**Comment by iriberri** [comment] 2015-06-08 16:13
Bump: Happened again today.

**Comment by iriberri** [comment] 2015-06-12 08:40
2 more. @saleiva

**Comment by javisantana** [comment] 2015-06-12 10:09
@rafatower shoudn't the table model validate the name length? looks like the PR is merged is previous to latests problems.

**Comment by rafatower** [comment] 2015-06-12 14:30
The name of the example is 64 chars long. Then at some other point `public.cpre_charter_to_save_our_countryside_comments_ex_do_not_` seems cut at 64 chars. In the mentioned PR I adjusted a limit to match an implicit limit of **postgres with identifiers, up to 63 chars**.

I made my point in the original issue #3747 that I fixed the limit size for consistency but then we need to decide how smart/picky the model should be (doing renames and stuff like that) and keep everything consistent across the app.

Comments are welcomed

**Comment by javisantana** [comment] 2015-06-12 14:33
there are two ways of changing names:

- using editor API: really easy to fix just checking name and returning an error <- current ticket
- using SQL API: this is really hard to manage

**Comment by Kartones** [comment] 2015-06-12 14:36
for second point, we could have a task like register ghost tables one that searches for "too long table names" and cuts them.

**Comment by rafatower** [comment] 2015-06-12 14:59
@Kartones usually postgres issues a NOTICE and truncates then without asking. And usually we don't notice those NOTICE's.
```
tests=# create table test();
CREATE TABLE
tests=# alter table test rename to cpre_charter_to_save_our_countryside_comments_ex_do_not_contact_very_long_blah;
NOTICE:  identifier "cpre_charter_to_save_our_countryside_comments_ex_do_not_contact_very_long_blah" will be truncated to "cpre_charter_to_save_our_countryside_comments_ex_do_not_contact"
ALTER TABLE
```

but then it is not limited to 63 chars when using the fully qualified schema name:
```
tests=# select * from public.cpre_charter_to_save_our_countryside_comments_ex_do_not_contact ;
--
(0 rows)
```

so I'd say we can live with truncates but need to check the sql api to see what's happening.

@iriberri that trace is from the sql api, right?

**Comment by iriberri** [comment] 2015-06-12 16:27
yep

**Comment by rafatower** [comment] 2015-06-15 09:31
The problem is not in the sql api but in postgres itself, observe the difference between using quotes or removing them:
```
tests=# select * from "public.cpre_charter_to_save_our_countryside_comments_ex_do_not_contact" ;
NOTICE:  identifier "public.cpre_charter_to_save_our_countryside_comments_ex_do_not_contact" will be truncated to "public.cpre_charter_to_save_our_countryside_comments_ex_do_not_"
ERROR:  relation "public.cpre_charter_to_save_our_countryside_comments_ex_do_not_" does not exist
LINE 1: select * from "public.cpre_charter_to_save_our_countryside_c...
                      ^
tests=# select * from public.cpre_charter_to_save_our_countryside_comments_ex_do_not_contact ;
--
(0 rows)
```

There are several problems here:
- The `Table` "model" (actually table service on top of `UserTable`) is pretty "rich" and used from the importer for instance to decide a suitable name in case of conflict, "sanitizes" tables name on users' behalf
- The postgres 63 chars limit of identifiers, which does not ensure everything will go fine as per the example shown above even if the table name length is < 63.
- We can take measures in the `Table` model but the sql api opens up the door to all sort of corner cases.

I guess I can fix the editor by modifying the resulting sql to something like this (mind the quotes):
```
select * from "public"."cpre_charter_to_save_our_countryside_comments_ex_do_not_contact";
```

@pramsey what do you think about increasing the `NAMEDATALEN` and recompiling postgres? What would be the consequences apart from maintaining another package?

**Comment by ztephm** [comment] 2015-06-17 16:10
Issue for S/B 5663013 also.

**Comment by rafatower** [comment] 2015-06-18 09:41
From tiler logs:
```
[2015-06-18 09:39:57.305] [ERROR] console - [POST LAYERGROUP ERROR] -- 404: Error: Error: could not fetch affected tables and last updated time: relation "public.bug3808_renamed_cpre_charter_to_save_our_countryside_com" does not exist
[2015-06-18 09:39:57.306] [INFO] [default] - undefined POST development.localhost.lan:8081/api/v1/map?map_key=0f938975d057039378a283da356d6c7c3b671107 404 106 ms -> application/json; charset=utf-8 ({"req2params.setup":1,"authorizedByAPIKey":1,"authorize":1,"mapSave":3,"validate":57,"incMapviewCount":1,"queryTablesAndLastUpdated":41,"total":105})

**Comment by rafatower** [comment] 2015-06-18 10:00
One of the problems comes from this query:
```
2015-06-18 09:49:42 UTC LOG:  statement: WITH querytables AS ( SELECT * FROM CDB_QueryTables($windshaft$select * from bug3808_renamed_cpre_charter_to_save_our_countryside_comments_e$windshaft$) as tablenames ) SELECT (SELECT tablenames FROM querytables), EXTRACT(EPOCH FROM max(updated_at)) as max FROM CDB_TableMetadata m WHERE m.tabname = any ((SELECT tablenames from querytables)::regclass[]);
2015-06-18 09:49:42 UTC ERROR:  relation "public.bug3808_renamed_cpre_charter_to_save_our_countryside_com" does not exist
```
but not with `CDB_QueryTables` itself:
```
# SELECT * FROM CDB_QueryTables('select * from bug3808_renamed_cpre_charter_to_save_our_countryside_comments_e');
                          cdb_querytables                          
-------------------------------------------------------------------
 {public.bug3808_renamed_cpre_charter_to_save_our_countryside_com}
```
https://github.com/CartoDB/Windshaft-cartodb/blob/master/lib/cartodb/api/query_tables_api.js#L36-L43

The issue is storing `schema.tablename` in an identifier that then exceeds the 63 char limit.

I think we can work-around it by casting `tablenames` to a couple of regclasses instead of just one in the query cc/ @rochoa @pramsey

**Comment by rafatower** [comment] 2015-06-18 10:27
An easier way to reproduce the issue:
```
# SELECT cdb_querytables::regclass[] FROM CDB_QueryTables('select * from bug3808_renamed_cpre_charter_to_save_our_countryside_comments_e');
ERROR:  relation "public.bug3808_renamed_cpre_charter_to_save_our_countryside_com" does not exist
```

**Comment by pramsey** [comment] 2015-06-18 12:28
@rafatower, important to remember that "this.is_a_table_name" and that "this"."is_a_fully_qualified_table_and_schema" and that "this"."is_also.full_qualified"

Anyways, that's why you can get "public.really_long_name" truncated, because it's still just a single table name and falling into the 64 char limit.

WRT just recompiling, in theory everything will work, though we'll just have a problem at a larger name limit instead. In practice, it's hard to know whether everyone has correctly used the right macro (probably) everywhere things matter.

**Comment by rafatower** [comment] 2015-06-18 12:50
> important to remember that "this.is_a_table_name" and that "this"."is_a_fully_qualified_table_and_schema" and that "this"."is_also.full_qualified"

yeah, I narrowed down the source of the problem and  created https://github.com/CartoDB/cartodb-postgresql/issues/86 to track that.

> WRT just recompiling, in theory everything will work...

I was wondering about performance pitfalls of having big tables. Let's keep that as a last resort.

I'll try to get around in that particular query using OID's for the join instead.

Thanks!

**Comment by ztephm** [comment] 2015-06-25 18:18
S/B 5740881 too

**Comment by rafatower** [comment] 2015-07-07 15:54
Will be fixed when this PR gets out: https://github.com/CartoDB/Windshaft-cartodb/pull/314

**Closed** 2015-07-09 10:39 UTC
Labels: 2 - Working, bug
