### ISSUE TITLE
Table / viz names get out of sync when navigating dashboard

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#2633] opened 2015-03-05 00:27 UTC
![wrong name](https://cloud.githubusercontent.com/assets/370259/6496645/6972c734-c293-11e4-8572-74b6b722de76.gif)

You see in the video, my 'datasets' list thinks there is something like 'sesame street Map', but that is maybe my visualization name? if i wait a while longer than I captured, it will pop back to the correct list.

that bouncing around of lists order and content happens in a number of scenarios, am I the only one that experiences that?

**Comment by saleiva** [comment] 2015-03-05 08:55
Uhm.... I've not experience this but will try. @viddo can you check this too?

**Comment by viddo** [comment] 2015-03-05 09:18
I can see (on superadmin) that you have the `cached_dashboard` feature flag enabled, can you try to disable that and confirm if it still happens?

**Comment by viddo** [comment] 2015-03-10 14:58
Confirmed that you have cached dashboard feature flag activated, and after talked with @xavijam  he also mentioned that it makes the dashboard appear "unstable", since the list loads a cached (in your cases, invalid) list which is not matching the real one (that gets fetched in the background and thus don't render until the response returns). cc @javisantana what would you like to do about this?

**Comment by javisantana** [comment] 2015-03-11 10:14
yes, this is a known issue, #2555

**Comment by viddo** [comment] 2015-03-11 12:16
Reassigning to santana, since this will be resolved with fixes related to the cached dashboard

**Closed** 2015-04-04 18:07 UTC
