### ISSUE TITLE
find a way to show import warnings to the user

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#4729] opened 2015-07-28 13:34 UTC
In some cases the files are imported but without problems like character encoding and so on. In those cases is better to import the file but we should warn the user somehow

**Comment by Kartones** [comment] 2015-07-28 14:45
Probably a duplicate of https://github.com/CartoDB/cartodb/issues/4502

**Comment by saleiva** [comment] 2015-08-03 16:08
Yep, duplicated

**Closed by saleiva** 2015-08-03 16:08 UTC
