### ISSUE TITLE
Privacy changes failing for tables without map

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6061] opened 2015-10-30 09:07 UTC
Error: https://rollbar.com/vizzuality/CartoDB/items/9695/occurrences/8573175083/

Trace:

```
NoMethodError: undefined method `save' for nil:NilClass
1
File "/home/ubuntu/www/production.cartodb.com/releases/20151030084536/app/models/table/privacy_manager.rb", line 14 in apply_privacy_change
2
File "/home/ubuntu/www/production.cartodb.com/releases/20151030084536/app/models/table.rb", line 454 in after_save
3
File "/home/ubuntu/www/production.cartodb.com/releases/20151030084536/app/models/table/user_table.rb", line 199 in after_save
... 15 non-project frames
19
File "/home/ubuntu/www/production.cartodb.com/releases/20151030084536/app/models/table.rb", line 88 in save
20
File "/home/ubuntu/www/production.cartodb.com/releases/20151030084536/app/models/synchronization/adapter.rb", line 84 in cartodbfy
21
File "/home/ubuntu/www/production.cartodb.com/releases/20151030084536/app/models/synchronization/adapter.rb", line 31 in run
22
File "/home/ubuntu/www/production.cartodb.com/releases/20151030084536/app/models/synchronization/member.rb", line 216 in run
23
File "/home/ubuntu/www/production.cartodb.com/releases/20151030084536/lib/resque/synchronization_jobs.rb", line 11 in block in perform
24
File "/home/ubuntu/www/production.cartodb.com/releases/20151030084536/lib/resque/base_job.rb", line 21 in call
25
File "/home/ubuntu/www/production.cartodb.com/releases/20151030084536/lib/resque/base_job.rb", line 21 in run_action
26
File "/home/ubuntu/www/production.cartodb.com/releases/20151030084536/lib/resque/synchronization_jobs.rb", line 10 in perform
... 30 non-project frames

```

cc @ethervoid @kartones

**Comment by rafatower** [comment] 2015-10-30 10:35
thanks for reporting, I was about to create it myself

**Comment by rafatower** [comment] 2015-11-06 10:30
let's keep this open to actually solve the bug

**Comment by gfiorav** [comment] 2015-11-11 17:12
We couldn't reproduce the problem. 

The best guest is that at some point something broke and was fixed in a short time. During said time, 2 synchronisations were created by 2 different users and turned out problematic. We have deleted this synchronisations and see no trace of them repeating.

**Closed by gfiorav** 2015-11-11 17:12 UTC
Labels: 0 - Backlog, bug
