### ISSUE TITLE
Nokia (Here) maps breaking in China

### ISSUE THREAD

**Issue by cshirky** [CartoDB/cartodb#5238] opened 2015-08-26 09:07 UTC
Bug: When viewing a CartoDB map at NYU's Shanghai campus. Nokia maps load highways and water, but no streets.

STR:
1. Be in Shanghai
2. Load map with Nokia basemap (The first map below, http://cdb.io/1Ei1cWR, is set to Nokia Day)
3. Observe that no streets are shown.
4. Change basemap to a Carto or Stamen map (The second map below is a screenshot of the same map, http://cdb.io/1Ei1cWR, set to Carto Positron.)
5. Observe streets

![screen shot 2015-08-26 at 4 36 02 pm](https://cloud.githubusercontent.com/assets/226500/9489512/2b895aa4-4c14-11e5-9c68-329817912262.png)
.
![screen shot 2015-08-26 at 5 01 45 pm](https://cloud.githubusercontent.com/assets/226500/9489563/8780ce5a-4c14-11e5-994f-a98e3477bae8.png)

This especially matters in China because Nokia maps are offset according to Chinese rules, while OSM-based maps are not, so any map made with a Nokia map can't be shifted to an OSM-based map without breaking.

**Comment by ohasselblad** [comment] 2015-08-27 13:53
Hey @cshirky, this is a problem of data coverage for (Nokia) HERE maps, not a bug.. I get the same view when looking at this from NYC. Just how OSM maps aren't good in some locations, the HERE maps aren't complete in others..

**Comment by cshirky** [comment] 2015-08-28 00:35
Thanks, ohasselblad.

Do you know when it changed? We made dozens of maps this spring using Nokia basemaps in China, and they all just broke.

And sadly, OSM maps (which I would happily switch to) don't line up with Nokia maps in China. :(

**Comment by ohasselblad** [comment] 2015-08-28 13:27
If Google maps or Bing work, you could use either of them with CartoDB.js. It will be outside of the editor, but the amount of coding is pretty minimal. Some example are here:
https://github.com/CartoDB/cartodb.js/tree/develop/examples

**Comment by ohasselblad** [comment] 2015-08-28 13:45
And I'm not sure when it changed, but I'll look into it. BTW, I've been emailing with your TA so I'll let him know.

I'm going to close this issue as it's 'resolved'.

**Closed by ohasselblad** 2015-08-28 13:45 UTC

**Comment by cshirky** [comment] 2015-08-29 02:22
Andy, it looks like it changed in late spring:
http://www.mobilegeeks.com/here-maps-no-longer-supports-china-hong-kong-macau-on-android/

Given that it co-incided with a Baidu tie-up, I wonder if Carto could use
Baidu maps in the country?

-c

**Comment by saleiva** [comment] 2015-09-03 13:41
Interesting question about the baidu integration @cshirky. Will research on that.

**Comment by ohasselblad** [comment] 2015-09-03 14:11
@saleiva there's a leaflet baidu plugin but it needs some more dev work: https://github.com/sureleo/leaflet-baidu
