### ISSUE TITLE
Static Torque layer renders the browser static too

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#12985] opened 2017-10-23 14:59 UTC
### Context
Setting a static Torque layer clogs the browser

### Steps to Reproduce
1. Create a map with an arbitrary points layer
2. Style the layer as Torque
3. Set duration = 0
4. Set frames = 1
5. ...whatever

### Current Result
The CPU load jumps and the browser becomes irresponsive for some minutes

### Browser and version
Chrome Version 62.0.3202.62 (Official Build) (64-bit)

**Comment by ramiroaznar** [comment] 2017-10-24 10:28
Happening to me as well. OS: Also working with Ubuntu 16 (Abel's is 17) and Google Chrome.

**Comment by ramiroaznar** [comment] 2017-10-24 10:42
@ernesmb has just tested it on Mac and it is working fine. It looks like it is a Ubuntu issue.

**Comment by ramiroaznar** [comment] 2017-10-24 10:47
Hey @rochoa do you know what our browsers are crashing on Ubuntu? @ernesmb suggested that maybe it is because it is not using the GPU.

**Comment by AbelVM** [comment] 2017-10-24 10:51
You should check `chrome://gpu` to see that everything is running as expected, so the bottleneck should be anywhere else

![image](https://user-images.githubusercontent.com/9017165/31939191-e37b48b6-b8b9-11e7-97f0-4dddd1aeb3bd.png)

**Comment by jgoizueta** [comment] 2018-07-11 16:41
I couldn't reproduce the problem with Chrome 67, Ubuntu 16.04. @ramiroaznar can you check again in your machine?

**Comment by ramiroaznar** [comment] 2018-07-12 08:04
Not happening anymore (but this has been an issue for me for months!). I couldn't reproduce it using any of these maps:
https://team.carto.com/u/ramirocartodb/builder/6d760df8-bb09-11e6-9938-0ee66e2c9693/embed
https://team.carto.com/u/ramirocartodb/builder/ab797f96-0a40-11e7-a19d-0e3ebc282e83/embed
https://team.carto.com/u/ramirocartodb/builder/8846ac54-154b-11e7-b277-0e3ff518bd15/embed

@AbelVM are you still experiencing this issue?

**Comment by ramiroaznar** [comment] 2018-07-16 10:14
Closing this then.

**Closed by ramiroaznar** 2018-07-16 10:14 UTC
Labels: engine
