### ISSUE TITLE
Creating a layer from an analysis node always create the layer on top, even if you drop on the bottom of the layer list

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8245] opened 2016-06-27 15:37 UTC

**Comment by viddo** [comment] 2016-06-27 15:57
This sounds like a dupe of #7970, if it's not please provide (the different) STR for this particular case.

**Comment by alonsogarciapablo** [comment] 2016-06-27 15:57
I feel like this is related to https://github.com/CartoDB/cartodb/issues/7970. cc: @viddo

**Comment by saleiva** [comment] 2016-06-27 16:01
This is happening always to me @viddo and @alonsogarciapablo 
for replicating just drag and drop any analysis below the original layer

**Comment by alonsogarciapablo** [comment] 2016-06-28 08:38
@saleiva this is what happens when I drag and drop an analysis below the original layer (in prod, currently):

![layers](https://cloud.githubusercontent.com/assets/390398/16409086/180c0a36-3d1c-11e6-825f-8d58b9902df5.gif)

Seems to be working fine in this case, "even" when I reload the map.... Is it failing for you on new maps too? Are you doing/did you do something before dragging the layer? thx

**Comment by saleiva** [comment] 2016-06-28 08:41
In the list the order is correct, but in the map it isnt'

2016-06-28 10:38 GMT+02:00 Pablo Alonso <notifications@github.com>:

> @saleiva <https://github.com/saleiva> this is what happens when I drag
> and drop an analysis below the original layer (in prod, currently):
>
> [image: layers]
> <https://cloud.githubusercontent.com/assets/390398/16409086/180c0a36-3d1c-11e6-825f-8d58b9902df5.gif>
>
> Seems to be working fine in this case, "even" when I reload the map.... Is
> it failing for you on new maps too? Are you doing/did you do something
> before dragging the layer? thx
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/8245#issuecomment-228987303>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENWgA-Z4AUnXhn-dGNgYHa_hQW2pjks5qQN1qgaJpZM4I_OTP>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by alonsogarciapablo** [comment] 2016-06-28 08:45
Ok, now we're talking! 👍

**Comment by alonsogarciapablo** [comment] 2016-06-28 11:04
This seems to be working but I noticed when an analysis is dragged out of a layer, the [map is reloaded twice](https://github.com/CartoDB/cartodb/issues/7881#issuecomment-229008711).

**Comment by alonsogarciapablo** [comment] 2016-06-28 15:23
I was finally able to reproduce this. Should be fixed in https://github.com/CartoDB/cartodb/pull/8292.

**Closed** 2016-06-29 08:53 UTC
Labels: bug
