### ISSUE TITLE
Changing from 3 to another number of classes produces gray in the ramp

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#9059] opened 2016-07-21 15:35 UTC
The first time you change from 3 to any other number of classes when styling by value, there is gray being added to the ramp. This only happens the first time. Also, if you choose another ramp, the gray goes away.

I noticed this with polygons.

![styling-issue](https://cloud.githubusercontent.com/assets/1566273/17028889/472a2fa2-4f26-11e6-9277-d7daa6d0dda8.gif)

**Comment by javierarce** [comment] 2016-08-30 08:54
Hi, @makella: I'm closing this issue, since I can't reproduce what you describe. Please, let me know if it's still happening to you.

![map](https://cloud.githubusercontent.com/assets/4933/18082637/15927028-6ea0-11e6-9b9f-11347be2abe0.gif)

**Closed by javierarce** 2016-08-30 08:54 UTC
Labels: bug, Builder, cartography
