### ISSUE TITLE
Delete a dataset warns about map that no longer points to it

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#9758] opened 2016-09-14 14:55 UTC
# STR

1. Upload twice the same dataset
2. Create a map with one
3. Change sql on the layer to point to other dataset
4. Delete original dataset

# Expected result

Dataset is deleted

# Actual result

A warning is issued about the map being deleted and it's effectively deleted upon confirmation.

NOTE: It also warns when deleting the right dataset.

**Comment by javitonino** [comment] 2016-09-16 15:36
The problem here lies in how data dependencies are calculated for analysis. Note that the same problem existed before (for layer). Basically, the dependencies are taken from the analysis query (extracting tables from the query) and from the `table_name` option. Both are added together.

The problem is that `table_name` may get outdated if the user changes the query to point to some other table than what is mentioned in `table_name`. The dataset referred to in `table_name` is still marked as a dependency although it is not actually one. So you cannot delete that dataset without also dropping the visualization.

This of course, happens only in some advanced workflows, so it's not a common issue.

My proposal is to check the query, and if we can extract some tables from there, use just those as the dependencies. If we cannot extract form the query (broken query, or not present) simply take the table_name. It should help some, but I foresee a problem in the UI, where the `table_name` is displayed and could point to a deleted dataset. We could also change that `table_name`, but that seems way overcomplicated.

Maybe we can just decide to ignore this, instead. It is not widespread after all. Comments?

cc @xavijam @CartoDB/builder-backend

**Comment by juanignaciosl** [comment] 2016-09-19 07:19
`table_name` is a really legacy attribute. As soon as you can write a query involving several tables, having a single table name on it makes no sense. Your proposal of checking the query is the best we can do, IMHO. `table_name` should only be used when there's no `query`. We should also consider displaying the query tables instead of table name.

**Closed** 2016-09-27 10:41 UTC
Labels: backend, bug
