### ISSUE TITLE
Improve DO analysis UI 

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#9711] opened 2016-09-08 10:06 UTC
Related to https://github.com/CartoDB/design/issues/68
(The visual design is on the ticket)

**Comment by saleiva** [comment] 2016-10-22 09:37
@xavijam this is an enhancement, but would be great to prioritize just after the launch.

**Comment by saleiva** [comment] 2017-01-25 23:29
dupe of https://github.com/CartoDB/cartodb/issues/9991

**Closed by saleiva** 2017-01-25 23:29 UTC
Labels: enhancement
