### ISSUE TITLE
Prevent users from adding more layers when max number of layers have been reached

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#7750] opened 2016-06-09 14:45 UTC
Right now, when you try to add more layers than you're allowed to, the API returns an error (`{"description":"You cannot add a layer in this visualization"}`) and the UI displays the following message:

![screen shot 2016-06-09 at 16 40 24](https://cloud.githubusercontent.com/assets/390398/15933687/f80697ac-2e60-11e6-8c72-2e83a51c690e.png)

The message is not very informative and users won't know why the layer couldn't be added. We could disable the Add layer button and inform the user that the maxinum number of layers has been reached.

cc: @xavijam

**Comment by xavijam** [comment] 2016-06-09 14:46
In fact that dialog should not be opened, it should display a beautiful CTA dialog. Pending...

**Comment by saleiva** [comment] 2016-06-27 14:17
Layers should not be a limitation on the builder. I'd remove this

**Comment by xavijam** [comment] 2016-06-27 14:18
Not layers limitation anymore?

**Comment by viddo** [comment] 2016-06-27 14:34
Then I imagine this would also fail if you try to create new layer from a dragged analysis node right now, so if the limitation is still there we need to prevent the user from dragging analysis too.

**Comment by saleiva** [comment] 2016-06-27 14:44
no layers limitation anymore guys

**Comment by xavijam** [comment] 2016-06-27 14:45
cc @CartoDB/backend, we will need backend changes.

**Comment by saleiva** [comment] 2016-06-27 14:47
whatever is easier, I don't mind removing the limitation on the future. Up to you!

**Comment by saleiva** [comment] 2017-03-08 16:38
closing! dupe of https://github.com/CartoDB/cartodb/issues/10689

**Closed by saleiva** 2017-03-08 16:38 UTC
