### ISSUE TITLE
Error adding widget: Abort

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11637] opened 2017-02-24 15:02 UTC
### Context
Lately I'm seeing this error a lot when handling widget options.
<img width="320" alt="screen shot 2017-02-24 at 16 01 14" src="https://cloud.githubusercontent.com/assets/132149/23308183/8e8c206e-faaa-11e6-95a9-86816156f2ca.png">

### Steps to Reproduce
Not a clear pattern, but it appears after editing a few widgets
Most of the times the change is made.

Not sure if it's a frontend issue or not
cc/ @xavijam @juanignaciosl

**Comment by xavijam** [comment] 2017-03-10 16:29
I feel I caught the problem. It appears when a widget request is cancelled by other one, and the notification appears, although nothing bad has happened. Stay tuned.

**Comment by nobuti** [comment] 2017-04-11 06:01
I can't reproduce it anymore, any clear STR @xavijam?

**Comment by saleiva** [comment] 2017-04-11 11:02
it happens less frequently to me now...

**Comment by xavijam** [comment] 2017-04-11 13:35
It is true I can't reproduce it now either 😱 . Let me close it and if we find a clear pattern to reproduce it, let's reopen it with the STR.

**Closed by xavijam** 2017-04-11 13:35 UTC
Labels: bug, Frontend, Next

**Comment by saleiva** [comment] 2017-04-11 14:57
VAMOS!
