### ISSUE TITLE
Include annotation elements, legends and overlays as part of static map export 

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#6284] opened 2015-12-15 20:44 UTC
@xavijam - unless someone else should review?
S/B 7647677

## Context
When export an image from the Editor, overlays and annotation elements are not included as part of the export

## Process
Create a map in the Editor, add a text annotation element to the map, select "Export Image" option, and export. Text overlay will not be included in the resulting image.

## Expected Result
Image will include overlays and annotations

## Current Result
Image does not include overlays, annotations, only the basemap and markers

**Comment by xavijam** [comment] 2015-12-30 11:12
Have you reproduced this error in production? I've checked it in my account and it is working properly...

Example:
![download](https://cloud.githubusercontent.com/assets/132146/12049959/a486a974-aeee-11e5-9307-1143043dd785.png)

**Comment by michellechandra** [comment] 2016-01-07 22:09
@xavijam - yup!

The issue is with advanced export, not the regular "Export".

Regular Export returns an image with the overlays:
![export](https://cloud.githubusercontent.com/assets/5423288/12184121/2f2c1c80-b548-11e5-9ffa-c33945c1a03f.png)

Advanced Export just returns the basemap and marker:
![advancedexport](https://cloud.githubusercontent.com/assets/5423288/12184127/363f56f4-b548-11e5-8e67-dfd7d243bb84.png)

Is this the expected result? The user wanted to generate a larger image for print quality reasons, but was unable to export an image with the overlays.

**Comment by xavijam** [comment] 2016-01-11 14:15
Yes, it is expected. In "advanced export" you can only *create* a new image with larger dimensions, but we can't include those components. It is a limitation of how we add those elements to the final image, it is like we make a photo about what the user is viewing ([Library](https://html2canvas.hertzen.com/) we use for that). But in the advanced export we can't create that canvas with those elements on the fly.

**Comment by xavijam** [comment] 2016-01-11 14:18
Closing since we don't provide that functionality in the current editor, taking into account in the new one :).

**Closed by xavijam** 2016-01-11 14:18 UTC
Labels: Editor
