### ISSUE TITLE
Organization login not for not org users

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11123] opened 2016-12-23 08:19 UTC
### Steps to Reproduce

1. Go to an organization login page.
2. Login with a user outside the organization.
3. You'll be logged in.

### Expected result

It should fail.

### Additional info

It's not a concern: you login as usual, without any relation to the org. Anyway, it might look strange.

**Comment by javitonino** [comment] 2017-01-02 19:48
Opening this one up for discussion. How do you think this should work?

My first idea would be to use some kind of error message, asking the user to go to the general login, which I think is the more explicit solution. A quick sketch:

![screenshot_20170102_203028](https://cloud.githubusercontent.com/assets/7569673/21595096/6ec81c78-d12a-11e6-8443-133398231fe4.png)

A concern, is that it may expose that the username is not a member of the organization. This could be avoided with a more generic "Username/password invalid. Not a member of team? Go to the general login." for all failed logins.

More ideas:
 - Automatically redirect to the general login without notice and ask the user to login again (but I think this is the worst of both worlds, bad feedback and more user interaction required).
 - We can also keep the current behaviour, which I don't think is bad. I don't think many users see the difference between the org login and general login (although they may have custom colors and logo), and it could be confusing to ask the user to login elsewhere.

Another thing we can consider is to disable the login page for user subdomains (javitonino.carto.com/login) and automatically redirect to the central login (carto.com/login). This makes it easier to avoid problems logging in between multiple clouds (if you to the login page of an user/org in a different cloud, your login doesn't work).

**Comment by saleiva** [comment] 2017-01-03 00:09
Hey, I actually love your latest idea about disabling login from user subdomains.

On the other hand, we would still need a solution for when an user try to login within an organization while doesn't belonging to it. For that particular scenario, I propose we do your second idea, we raise an error saying "Not a member of {organization_name}?, Go to carto.com/login"

Let me know if you need a quick mockup for that.

**Comment by javitonino** [comment] 2017-01-03 11:00
Yes, a mockup would be great. Specially since the organization login page can be customized and it's a bit harder to do something that looks nice in different customizations.

Thanks!

**Comment by javitonino** [comment] 2017-01-03 14:40
Another question: What should we do for on-premise / open source? I suggest keeping current behaviour in that case, as there is not a clear place to send the user to (no Central, so all login URLs are for an organization/user).

**Comment by saleiva** [comment] 2017-01-03 14:51
Sounds good to me

**Comment by carlostallon** [comment] 2017-01-03 14:56
Hi guys, I prepared some mockups but my proposal is:

#### Add the copy for the login remembering to use the corporate email".
![01 org login](https://cloud.githubusercontent.com/assets/1712650/21611419/11dd07f0-d1cd-11e6-9c2f-2aeb070ab981.png)

#### If the user fail, change that copy to the one @javitonino proposed.
![02 org login error](https://cloud.githubusercontent.com/assets/1712650/21611418/11dd2a28-d1cd-11e6-86fd-3795efdd0a51.png)

#### keep using the same behaviour for error messages with red bullets + tooltips.
![03 org login error hover](https://cloud.githubusercontent.com/assets/1712650/21611417/11db9096-d1cd-11e6-9960-8b139d48a0c0.png)

**Comment by javitonino** [comment] 2017-01-03 15:04
@carlostallon Looks good to me! Just one detail, I would not put the domain ("@nyu.edu" in your example) in the copy because it can actually be a long list of allowed domains. Also, it might disclose some potentially sensitive data (some private email domain). So I'd just say something generic like in the signup page: "Please, remember to use an email address belonging to this organization to login to your account."

**Comment by carlostallon** [comment] 2017-01-03 15:07
@javitonino you are right! updated!

#### Login updated
![02 org login](https://cloud.githubusercontent.com/assets/1712650/21611799/a947842a-d1ce-11e6-90b7-74777a3ddd9c.png)

**Comment by saleiva** [comment] 2017-01-03 15:26
Cool! Moving to Done in design then!

**Comment by gfiorav** [comment] 2017-01-04 17:38
Could someone add some instructions for acceptance? Thanks!

**Comment by javitonino** [comment] 2017-01-04 18:02
They are in the PR :)

**Comment by javitonino** [comment] 2017-01-05 14:36
Let's stop this PR for a minute. I've been testing, and it breaks auto-user creation via SAML (and I'm pretty sure that via LDAP as well). Moving back to development and stopping to think about it.

**Comment by ohasselblad** [comment] 2017-01-05 14:52
For the record, knowing the proper login (or even signup) page for university org users has been a big source of confusion.

**Comment by javitonino** [comment] 2017-01-05 14:55
@ohasselblad Not sure what the problem is for login, since you can login from pretty much anywhere. Can you elaborate? I know about signup (which is a bit more complicated, since you can signup inside or outside the org), we have that ticket in the backburner. But it seems to me that login should not be a problem, carto.com/login works for everyone.

**Comment by ohasselblad** [comment] 2017-01-05 15:00
Sorry, you're right. Yeah, the signup was the only source of confusion.

**Comment by javitonino** [comment] 2017-01-05 15:16
The issue I mentioned is not an issue for now, as it only affects the SaaS. I'll document what needs to be done in https://github.com/CartoDB/cartodb/issues/11108

This can continue as it is for now.

**Closed** 2017-01-11 09:23 UTC
Labels: Backend
