### ISSUE TITLE
Custom legend /infowindow disappear after changing privacy and visualizing a dataset

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3736] opened 2015-05-22 09:57 UTC
Steps:

* Create an empty dataset (private by default)
* Add a couple of points in map view
* Enable infowindows on hover, create a custom legend: add a word in html template
* **Change privacy of the dataset to "private with link"**
* Visualize: infowindows disabled, legend gone.

Happening in accounds iriberri and trainings, with and without new endpoints respectively.

**Comment by Kartones** [comment] 2015-05-22 10:17
This only happens if you do the actions quickly (not letting the browser get the response), else works correctly.

**Comment by rafatower** [comment] 2015-05-25 13:51
I could systematically reproduce this issue. I think the caches are not being invalidated at some point. Duplicate of https://github.com/CartoDB/cartodb/issues/3736

**Closed by rafatower** 2015-05-25 13:51 UTC
