### ISSUE TITLE
Empty histograms in embed                                                                                   

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#11157] opened 2016-12-30 15:10 UTC
Making an app with 4 sync tables, all of them linked, with a structure like:
![image](https://cloud.githubusercontent.com/assets/9017165/21567166/311942ee-ceaa-11e6-945d-784d9b25e763.png)

It works ok, but once the data is synced the first time since the publishing, the histograms are ok within Builder:

![image](https://cloud.githubusercontent.com/assets/9017165/21567178/4db4bd98-ceaa-11e6-824d-46c6712b33c6.png)

But the behavior of the embed is quite different:

![image](https://cloud.githubusercontent.com/assets/9017165/21567186/5e3a5ace-ceaa-11e6-8b51-68bb4e6365cf.png)

**Comment by AbelVM** [comment] 2016-12-30 15:17
.carto file on request

**Comment by saleiva** [comment] 2017-01-02 15:49
do we finally have STR?

**Comment by AbelVM** [comment] 2017-01-02 15:52
WiP, but you can check the v 2.0 dashboard at https://github.com/CartoDB/solutions/issues/880, or I can share the .carto.

I'm short on time right now :disappointed:

**Comment by AbelVM** [comment] 2017-01-11 16:07
The dashboard affected is going to receive some media attention, so it would be great if anybody takes a look on it so I can make any change if needed

**Comment by saleiva** [comment] 2017-01-12 17:24
hi @AbelVM how often is this happening in production right now?

**Comment by AbelVM** [comment] 2017-01-12 17:35
I have only one case with the evil combination of synctables, analysis and widgets that gives this issue back.

But this case may turn into a blogpost next week

**Comment by saleiva** [comment] 2017-01-12 20:34
but does this happen all the time on that embed? have you tried replicating the map exactly?

**Comment by AbelVM** [comment] 2017-01-13 10:45
Duplicating the map, the histograms are OK there

![image](https://cloud.githubusercontent.com/assets/9017165/21927019/ac7ac054-d984-11e6-856a-534025ea7265.png)

Forcing the sync of pollution dataset (node **a0**), the traffic histograms are still OK. 

But forcing the sync of traffic dataset (node **b0**), even when the traffic data is exactly the same, because the source has not changed in the meantime, turns the histograms like they have 0 width buckets:

![image](https://cloud.githubusercontent.com/assets/9017165/21927076/dffc0c80-d984-11e6-8804-368dcffb98c8.png)

But this is where it gets weirder. Checking the same dashboard in Builder:

![image](https://cloud.githubusercontent.com/assets/9017165/21927227/7148077a-d985-11e6-9dca-e04a2ae6efc6.png)

**Comment by xavijam** [comment] 2017-01-26 17:56
I've already checked the behaviour and I don't have a clear idea about the problem, I'll review it with @rochoa.

**Comment by AbelVM** [comment] 2017-02-03 13:27
I have a new dashboard with similar behaviour. No sync tables this time. Just play dataset with widgets. No analyses either. The embed fails with formula, histograms and time series

I can't share the link because of the customer data, but feel free to ask privately.

Builder:
![selection_004](https://cloud.githubusercontent.com/assets/9017165/22592966/920c1256-ea1c-11e6-9a68-0c371f590884.png)

Embed:
![selection_005](https://cloud.githubusercontent.com/assets/9017165/22592979/a21b297a-ea1c-11e6-9f72-dc68de559547.png)

![selection_006](https://cloud.githubusercontent.com/assets/9017165/22592987/a809ad16-ea1c-11e6-8a3f-7afd2b496d33.png)

**Comment by angdelfue1** [comment] 2017-02-07 09:41
Hi guys! we want to use [this map](https://team.carto.com/u/abel/builder/6fc33032-ba91-4ca8-becb-67e481c4bf43/embed) for an upcoming blog post - do you have approx. date/milestone to work on this? (just to know if we can still publish the post)

Thanks!

**Comment by saleiva** [comment] 2017-02-07 09:58
if publishing this in the blog, can we be sure @makella takes a look first? There is a bunch of issues with contrast on that map.

**Comment by rochoa** [comment] 2017-02-22 14:24
I took me some time, but I've finally described what's the problem behind this bug. I will prioritise this issue in Engine.

For more details, check https://github.com/CartoDB/Windshaft-cartodb/issues/629.

**Comment by ethervoid** [comment] 2017-04-12 12:56
I've been checking if the fix we deployed it's working as intended and it is :).

I've created a visualization with an analysis and a histogram data view pointing to a numeric column. 

With the previous buggy version, the data view doesn't change when we make a change in the table data because the cache doesn't get invalidated:

![builder_dataview_bug](https://cloud.githubusercontent.com/assets/741240/24958563/049db24a-1f90-11e7-9839-7c4a1becf5d1.png)

Using the version with the fix applied, the cache gets invalidated and the data view reflects the changes properly:

![builder_dataview_without_bug](https://cloud.githubusercontent.com/assets/741240/24958536/e81d8082-1f8f-11e7-8d10-7e926c469ebe.png)

What I've not been able to reproduce is this problem without analysis like @AbelVM said [here](https://github.com/CartoDB/cartodb/issues/11157#issuecomment-277246314)

**Comment by saleiva** [comment] 2017-04-12 13:41
So closing this then? 💪

**Comment by xavijam** [comment] 2017-04-12 13:47
woaw, :_)

**Comment by ethervoid** [comment] 2017-04-12 14:05
Closing :)

**Closed by ethervoid** 2017-04-12 14:05 UTC
Labels: bug

**Comment by rochoa** [comment] 2017-04-20 12:31
❤️ !
