### ISSUE TITLE
Style by category for polygons after applied an analysis is not working

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9524] opened 2016-08-23 15:07 UTC
## STR
- Create a map with a layer of points.
- Apply an AOI by distance analysis over that layer.
- Click over "style this analysis result" is not working either, but go to the style tab.
- Change the fill attribute, select by value, and choose a string column.
- Category columns don't appear, check console.

**Comment by javierarce** [comment] 2016-08-30 08:20
I'm closing this issue, since I can't reproduce it. For me, selecting string columns gave me the list of categories: 

![screen shot 2016-08-30 at 10 15 05](https://cloud.githubusercontent.com/assets/4933/18081462/ad48d746-6e9a-11e6-8672-c1770e144344.png)

I created an issue for the "style this analysis result" that you mention here: https://github.com/CartoDB/cartodb/issues/9609

**Closed** 2016-08-30 08:21 UTC
Labels: bug, Builder
