### ISSUE TITLE
Error when creating sync table with interval=0

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/cartodb#2834] opened 2015-03-19 13:06 UTC
From the documentation (http://docs.cartodb.com/cartodb-platform/import-api.html#syncing-a-file-from-an-url):

>interval: The number of seconds for the synchronisation period. CartoDB supports the following values: 0 (never synched), 3600 (sync each hour), 86400 (sync each day), 604800 (sync each week) or 2592000 (sync each month).

However, if I try to create a sync table with interval=0, I get the following error:

```
{"errors":"Invalid interval: Sync interval must be at least 15 minutes"}
```

Please, either fix the API or the docs, but note that having a sync table that is only sync'ed manually makes sense for some use cases.

**Comment by xavijam** [comment] 2015-03-20 09:22
Weird, it should work with 0, at least in the UI we use it in that way and there isn't any problem. @kartones @rafatower @juanignaciosl

**Comment by Kartones** [comment] 2015-03-20 09:23
Assign to me and I'll check (but please, at least [Guarroman milestone](https://github.com/CartoDB/cartodb/milestones/Guarroman))

**Comment by xavijam** [comment] 2015-03-20 09:25
@Xatpy, could you take care of it? Basically check with @danicarrion what the problem is and if the docs are ok.

**Comment by Xatpy** [comment] 2015-03-20 10:17
Sure!

And yes, I had the same problem than @danicarrion. 
I've been testing with: 
> curl -v -H "Content-Type: application/json" -d '{"url":"http://www.jaimechapinal.com/cartodb/test_import_url.csv", "interval":"900"}' "https://xatpy.cartodb.com/api/v1/synchronizations/?api_key=MY_API_KEY"
and I've checked that the first value allowed is 900 (15 minutes).
So, I'm changing the doc with this.

@xavijam , I think that it's a backend issue. Also, I don't know why 0 value should be allowed (because it will never be synced again with that value. cc @Kartones

**Comment by Kartones** [comment] 2015-03-20 10:24
uhmm, are you sure old dashboard wasn't removing that `interval:0` field?

Because checking backend code, it's been since jun 2014 disallowing intervals lesser than 15 minutes. Backend doesn't allows a 0 as interval.

I'd bet that dashboard discerned between calling sync if interval > 0 or import if interval == 0, so looks like a documentation issue.

**Comment by Xatpy** [comment] 2015-03-20 11:17
I've just updated the [documentation](http://docs.cartodb.com/cartodb-platform/import-api.html#definition-4)

I can't figure out the reason about syncing each 0 minutes. I think that in this case, import api should be used.

I'm closing this issue. But if you want to discuss about it, please feel free to re-open it again. :)

**Comment by danicarrion** [comment] 2015-03-27 09:12
Why do tables have to be synced _periodically_? Why can't I have a table that I sync manually? The import API creates a new table, but what if I just want to reload an existing one?

**Comment by Kartones** [comment] 2015-03-27 09:19
There is an (undocummented) endpoint to force a manual sync from the CartoDB Editor:
`(/u/:user_domain)/api/v1/synchronizations/:id/sync_now`
In order to preserve platform stability and avoid abuse it won't sync if the internal since last sync is lower than 900 seconds.

In the future we might implement webhooks for some services (Dropbox, etc. provide them) so would only sync if had changes, but is not in the roadmap right now, is just an idea.

**Comment by danicarrion** [comment] 2015-03-27 09:58
Does that work for regular tables too, or only for sync tables?

Because there is already a way to manually force a manual sync in the import API for sync tables, the problem is that there's no way to avoid periodic, automatic syncs.

**Comment by Kartones** [comment] 2015-03-27 10:02
uhmmm, normal imports are just imported, so why would you like to "resync"? They don't store the source of their data, that's what sync tables are for.
Anyway is only from the sync endpoint so only for sync tables. 

Nothing prevents you from creating a monthly sync, or even a yearly one. From the syncs endpoint you can define any interval >= 900.

**Comment by danicarrion** [comment] 2015-03-27 10:11
there, my point is: instead of making users set the interval to a high number themselves, why don't we allow setting interval=0 and internally make the interval be Float::INFINITY or similar?

i know, it's kind of silly, but this way the user doesn't have to make a decision (a year? ten years? how many seconds is 10 years?), avoid typing mistakes, etc.

**Comment by danicarrion** [comment] 2015-03-27 10:11
there, my point is: instead of making users set the interval to a high number themselves, why don't we allow setting interval=0 and internally make the interval be Float::INFINITY or similar?

i know, it's kind of silly, but this way the user doesn't have to make a decision (a year? ten years? how many seconds is 10 years?), avoid typing mistakes, etc.

**Comment by Kartones** [comment] 2015-03-27 10:29
Could be added, but for that ask or discuss with @saleiva. From the code point of view could be done, take any interval=0 as infinity... But not changing internally, if 0 becomes "forever" it would stay as zero and just never sync.

Take into account this has some implications, we have some ways of forcing a sync of **every** sync table just in case an internal error broke something, so there is a small chance that even those syncs would change.

**Closed** 2015-10-06 08:11 UTC
Labels: enhancement, importer
