### ISSUE TITLE
Hover Infowindow Error Builder - Windows 7

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9140] opened 2016-07-27 11:48 UTC
@michellechandra commented on [Tue Jul 26 2016](https://github.com/CartoDB/cartodb-management/issues/4532)

## Context
A user is having difficulties when creating hover infowindows with a Map in the Builder. The user is using Chrome Version 51.0.2704.103 m (64-bit) and Windows 7 Enterprise SP1 operating system. When switching between a hover infowindow and click infowindow and clearing the click infowindow, the hover infowindow menu options disappear.

## STR
![hover_bug](https://cloud.githubusercontent.com/assets/5423288/17119756/c00a6410-527c-11e6-8264-4a32aaa7d020.gif)

Maybe related to this issue? https://github.com/CartoDB/cartodb/issues/8312

S/B: 9418954

---

@xavijam commented on [Wed Jul 27 2016](https://github.com/CartoDB/cartodb-management/issues/4532#issuecomment-235523670)

Moving to CartoDB repository.

**Comment by xavijam** [comment] 2016-10-04 15:50
Could you take a look please, I hope we don't have that bug, so just to confirm it.

**Comment by matallo** [comment] 2016-10-05 14:01
can't reproduce (find attached)

![ie](https://cloud.githubusercontent.com/assets/36676/19116220/f861f154-8b14-11e6-85b9-e160ae31fd80.gif)

closing then

**Closed by matallo** 2016-10-05 14:01 UTC
Labels: bug, Builder
