### ISSUE TITLE
Boolean fields are not showing in dropdown menu from Filter by col. value analysis

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#11546] opened 2017-02-15 12:04 UTC
### Steps to Reproduce

1. Create map with `chicago_crimes` dataset.
2. Add Filter by column value analysis.
3. "Select" `arrest` (a boolean column) from the dropdown menu.

### Current Result

* Boolean columns are not showed on the dropdown menu.

![bug](https://cloud.githubusercontent.com/assets/5215798/22973618/c192006a-f37e-11e6-81be-82c8919f679d.png)

### Expected result

* Boolean columns should appear on the dropdown menu.

### Browser and version

* Google Chrome v54.

### .carto file

* Because the map size is too big, you can download a sample data from [here](https://team.carto.com/u/ramirocartodb/tables/builder-demo.chicago_crimes_sampled/public/map?redirected=true).

**Comment by saleiva** [comment] 2017-02-15 12:49
moving to next since this is part of the filter analysis (which is quite common)

**Comment by nobuti** [comment] 2017-05-18 16:07
@jorgesancha @noguerol @xavijam PR opened [here](https://github.com/CartoDB/cartodb/pull/12158) but the thing is, it won't work until https://github.com/CartoDB/cartodb/issues/10000 it's fixed in engine side. Basically it's the same issue, the tiler returns the whole set of features.

**Comment by ethervoid** [comment] 2017-05-19 10:40
We have the same problem in different projects and is how we treat boolean values. 

Issue #10000 is a turbo-carto issue but the one that is blocking Butis is related to camshaft. I'm going to ope an issue there

**Comment by ethervoid** [comment] 2017-05-19 15:07
The analysis is filtering the values properly. But we have, at least in local, some weird behavior painting the values. Funny thing is that the analysis resulting dataset is filtered correctly.

**Comment by ethervoid** [comment] 2017-05-22 09:49
I've been checking and the filtering is working fine. Is there any step to reproduce the case where the analysis is returning the whole set of features @nobuti ? thx

**Comment by nobuti** [comment] 2017-05-22 10:09
I tried with only two features and it seems to work, but still, there are weirdos with the boolean fields in the form.
- [ ] Validators don't play nice with those fields. @matallo is doing his magic here.
- [ ] If you try to select `true` and `hide` combination, it replaces automagically to `true` and `show`.
Anyway, it seems a full frontend issue now.

**Comment by xavijam** [comment] 2017-05-31 09:22
Deployed

**Closed** 2017-05-31 09:22 UTC
Labels: Analysis, bug, Frontend
