### ISSUE TITLE
Maps with overviews are not working in the Builder

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#10917] opened 2016-11-30 16:20 UTC
### Steps to Reproduce

1. Create a map with overviews in the editor.
2. Migrate that user to the Builder.
3. Open that map in the Builder and check the error.

```
PoS: Postgis Plugin: ERROR: column "xxxx" does not existLINE 1: ...cator",1e-05),1e-05,true),5) AS geom,"cartodb_id","xxxx",... ^in executeQuery Full sql was: 'SELECT ...
…
m.psz * 48), m.xmin, m.ymin), bucketA AS (SELECT * FROM bucketA_snap WHERE points_count > 48 * 1 ) , bucketB_snap AS (SELECT ST_SnapToGrid(f.the_geom_webmercator, 0, 0, m.psz * 0.75 * 48, m.psz * 0.75 * 48) the_geom_webmercator, ...
…
```

_SQL shortened_
cc @ramiroaznar 

@javisantana @rochoa

**Comment by javitonino** [comment] 2016-11-30 16:22
Maybe related https://github.com/CartoDB/cartodb/issues/10783

**Comment by jgoizueta** [comment] 2016-11-30 16:35
Is that happening for any map?
I'm only aware of the problem mentioned by javitonino and the fact that overviews are not used when analyses are added to a layer (but should not cause an error)

**Comment by jgoizueta** [comment] 2016-11-30 16:52
I guess it was a cluster map

**Comment by xavijam** [comment] 2016-11-30 16:57
I've seen that error in a layer without analyses.

**Comment by jgoizueta** [comment] 2016-11-30 17:07
Yes, we have an error I can reproduce when the cluster wizard has been applied to a layer with overiews in the editor and then the map is migrated to the builder. Maybe with some other wizard too, I haven't tried all of them yet.

Note: dropping the overviews doesn't fix the broken maps 😞

**Comment by jgoizueta** [comment] 2016-12-02 14:06
A [fix](https://github.com/CartoDB/Windshaft-cartodb/pull/599) for this is coming to the tiler.

**Comment by ramiroaznar** [comment] 2016-12-02 14:20
@ernesmb We roll an account back due to this problem, right?

**Comment by jgoizueta** [comment] 2016-12-02 15:59
The problems related to overviews are fixed now, but other problems remain with some visualizations using clusters. Moving to #10953

**Closed by jgoizueta** 2016-12-02 15:59 UTC
Labels: bug, Builder
