### ISSUE TITLE
Removing a dataset linked to various layers of a map results in broken map

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#9759] opened 2016-09-14 15:16 UTC
# STR

1. Create a dataset
2. Create a map with 2 layers referencing that dataset
3. Remove dataset (user warned)

# Expected result

The map is deleted

# Actual result

The map isn't deleted and is left like an (accessible) _"empty shell"_, a map with no layers

Related to https://github.com/CartoDB/cartodb/issues/9758

cc/ @javitonino @juanignaciosl

**Comment by juanignaciosl** [comment] 2016-09-14 15:51
@gfiorav is the user warned about the deletion on step 3?

**Comment by gfiorav** [comment] 2016-09-14 15:52
Yes!

**Comment by javitonino** [comment] 2016-09-16 15:45
Uhm, cannot reproduce this anymore :disappointed:

**Comment by juanignaciosl** [comment] 2016-09-28 10:30
This is fixed now (checked both editor and builder) ✨

**Closed by juanignaciosl** 2016-09-28 10:30 UTC
Labels: backend, bug
