### ISSUE TITLE
Builder styling for Torque crashes if value driven style is used

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#12328] opened 2017-06-15 09:02 UTC
**Tightly related to https://github.com/CartoDB/cartodb/issues/10947, but this issue does not duplicate or override the former issue. This is only about Builder Styling for Torque**

### Context
Data driven styling for Torque crashes in Builder

### Steps to Reproduce
Style a Torque layer and then you may take one of the next actions:
* Change the bucketing from `category` to any other
* Just change the basemap

### Current Result

![image](https://user-images.githubusercontent.com/9017165/27138506-e87342f2-5120-11e7-871f-4eb2b47951ce.png)

### Expected result
Normal data driven styling

### Browser and version
Any

### .carto file
Any

### Additional info
CartoCSS generated by Builder UI when just changing the bucketing to quantiles

![image](https://user-images.githubusercontent.com/9017165/27138575-22f5e7c2-5121-11e7-8267-01e977d2be85.png)

**Comment by xavijam** [comment] 2017-07-12 08:00
I've been checking the error and it is not happening doing what you suggested @AbelVM, gif included:

![](https://www.dropbox.com/s/pjb6juesmtdilzw/torque-no-bug.gif?dl=0)

**Comment by xavijam** [comment] 2017-07-12 08:05
Let me close this in favour of https://github.com/cartodb/cartodb/issues/10947, because the issue is the same 💋 .

**Comment by AbelVM** [comment] 2017-07-12 08:35
You skipped the first step of the STR!! :stuck_out_tongue_closed_eyes: 

`· Change the bucketing from category to any other`

**Comment by xavijam** [comment] 2017-07-12 08:48
Ahhhh, thanks for pointing me to that. It is not possible to select a "ramp" for that. Only categories are available. We CAN'T right now provide that behaviour because we don't have the necessary data to create the "conditionals" in the CartoCSS without making another previous request (:scream:). So in my opinion we should "disable" the possibility to change the quantification. @noguerol @jorgesancha

**Comment by xavijam** [comment] 2017-07-12 09:18
And again, it is the same ticket than https://github.com/cartodb/cartodb/issues/10947. So let's close it.

**Closed by xavijam** 2017-07-12 09:18 UTC
Labels: bug, Frontend

**Comment by AbelVM** [comment] 2017-07-12 09:35
That's why I reopened it, this issue is Builder related while the other one is Engine related. We should block the user from changing the ramp in Builder when Torque is selected while the main issue is fixed because this action leads to a crash always.

So, at the end, I agree with your point.

**Comment by xavijam** [comment] 2017-07-12 09:38
Well... that's a good point 👍 . But I feel that decision should be taken by @noguerol or @kevin-reilly. Let them decide what to do in (https://github.com/cartodb/cartodb/issues/10947), and if it is needed, let's reopen this one :kiss:.
