### ISSUE TITLE
Enter key on column delete causes interface loop

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#1814] opened 2015-01-15 16:51 UTC
![doubleconfirm](https://cloud.githubusercontent.com/assets/370259/5761934/cda2a92a-9cac-11e4-9889-b71aeeaaa479.gif)

You'll see that I click Enter to confirm the delete. Then it gets stuck. Then even using a mouse click doens't fix it and I end up hitting ESC to exit the modal

**Comment by saleiva** [comment] 2015-01-16 10:48
Sorry mate, but I'd consider this important :(

**Comment by xavijam** [comment] 2015-01-16 11:09
@Xatpy, take a look please.

**Comment by viddo** [comment] 2015-01-16 11:27
_(since I worked on the delete dialog for new dashboard recently and know the code more or less I give some hints to not have to waste too much time on looking for things:)_

@Xatpy 
- probably related to [CartoDB.js common.Dialog's behaviour on `close_on_enter`](https://github.com/CartoDB/cartodb.js/blob/develop/src/ui/common/dialog.js#L104-L106)
- the delete dialog is created in [table_item.js](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/dashboard/tables/table_item.js#L282-L288)

**Comment by Xatpy** [comment] 2015-01-16 11:36
I've been testing it, and I think that the problem is when you click on **Enter key** *very quickly* (when you've just clicked on delete column with the mouse). 

So I think that the problem is that it hasn't been loaded when the 'Enter key' is pressed.

![bug_delete_column](https://cloud.githubusercontent.com/assets/3958416/5775587/47f81384-9d7c-11e4-852a-a95b2c7552b9.gif)

I'll check it. thanks!

**Comment by Xatpy** [comment] 2015-01-19 11:05
I've been debugging it, and I think that the problem could be [here](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/models/table.js#L317) 
*c* is undefined, and because of that the error appears. 
I think that the reason is  because *c* has not been loaded when enter is pressed. As it's asynchronous, it's been loaded in another 'thread'.
Also, it's hard to catch the error in local development (because it's faster than production)
My proposal would be to have a "defender", I mean:
```
if (c !== undefined) {
    c.destroy({
     ....
}
```
This way, we would be defending about that error.
I don't know if exists another methods, for example some "active wait" or something like that.

@xavijam @viddo what do you think?

**Comment by viddo** [comment] 2015-01-19 18:40
IMHO, adding a "defender"/if-check is merely covering up the symptoms. If there are prerequisite data for that action to be carried out either don't allow the action to be triggered until data is ready, or hold back the action until the data notifies that it's done. I guess that is what you meant by "active wait"? In JS that would be solved by a "promise", or such.

Btw, you can [enable network conditions in Chrome develop tools](https://developer.chrome.com/devtools/docs/device-mode#network-conditions) to simulate slow requests if you want to troubleshoot async issues.

**Comment by Xatpy** [comment] 2015-01-20 10:16
@viddo  thank you so much for your recommendations! Sincerely, I didn't remember that enable network conditions feature in Chrome develop tools. thanks! :)

About the issue, yes you're right. It would be better if we use promises (sorry, I didn't choose the correct words with 'active wait'). I've been searching about that. Would it be [this](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/delete_dialog.js#L249) related ?

**Comment by viddo** [comment] 2015-01-20 10:29
doesn't have to solved by a promise per se, but if using that as an example:
the `model.fetch` methods for example returns a kind of promise, see [backbone docs, #Model-fetch](http://htmlpreview.github.io/?https://raw.github.com/jashkenas/backbone/0.9.2/index.html#Model-fetch) for details. So together with opening dialog you could have something like:"
```js
var jqXHR = dependentModel.fetch();
```
and later somewhere in a dialog
```
// show some intermediate
jqXHR.done(function() {
  // enable delete button and whatnot, or trigger the deletion if enter key was pressed while loading data.
})
.fail(function(model, error, e) {
  // necessary data could not be loaded for whatever reason
});
```

ofc, the user won't see/know these details so the appropriate thing to add as well is some kind of feedback that required data is loading, until the jqXHR resolves (open the delete table/vis dialog and you will see an example of how's it done).

**Comment by Xatpy** [comment] 2015-01-20 18:10
The problem also is that when the first deletion is done, the dialog should disappear. And that's not happening.

**Comment by Xatpy** [comment] 2015-01-29 16:35
closing this issue with this commit: https://github.com/CartoDB/cartodb/commit/ee69d39043a23778d74e90089bf77ccb225ba896

**Closed by Xatpy** 2015-01-29 16:35 UTC
Labels: 3 - Done
