### ISSUE TITLE
In Builder: Legend colors don't appear in IE 11+

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#10596] opened 2016-11-07 17:28 UTC
### Context
S/B 10417008
cc @nygeog 
@CartoDB/support let client know when fixed please

Hi @javierarce looks like [this issue](https://github.com/CartoDB/cartodb.js/issues/431) is happening again?

Builder legend colors don't appear in Internet Explorer.

### Steps to Reproduce
1. Import any dataset - I used Data Library one for earthquakes - & make a Builder map from it.
2. Click into the layer, click STYLE tab, click Fill color bar
3. Choose Style By Value, then choose a string column to get Categories (in earthquakes dataset I chose *magtype*). 

### Current Result
Legend looks good in Chrome:
![screen shot 2016-11-07 at 10 53 05 am](https://cloud.githubusercontent.com/assets/1779444/20064346/612a749a-a4d8-11e6-8c5c-e9ee125ec69c.png)

Legend colors do not appear in Internet Explorer 11 (tested in VirtualBox w/Windows 8):
![screen shot 2016-11-07 at 12 28 09 pm](https://cloud.githubusercontent.com/assets/1779444/20068131/a5c30e02-a4e5-11e6-9a1b-8c59327fbf57.png)

### Expected result
Legend colors in IE should appear the same as in Chrome, Firefox etc.

### Browser and version
* successful: Chrome 54.0.2840.71
* not successful: Internet Explorer 11 tested on virtual Windows 8.1 in Virtual Box 

### .carto file
[ie_legend_colors_test (on 2016-11-07 at 15.59.08).zip](https://github.com/CartoDB/cartodb/files/576107/ie_legend_colors_test.on.2016-11-07.at.15.59.08.zip)

### Additional info
* We had this issue in Editor maps also: https://github.com/CartoDB/cartodb/issues/3068
* Custom marker icons are also missing from legend.

**Comment by xavijam** [comment] 2016-11-07 17:39
I feel @nobuti checked that recently and it was working... could you take a look again mate please?

**Comment by nobuti** [comment] 2016-11-08 10:41
I can't reproduce it 😞 

![ie11](https://cloud.githubusercontent.com/assets/1366843/20095974/0cd8b958-a5a8-11e6-9523-037ad0f47fc1.gif)

**Comment by saleiva** [comment] 2016-11-08 12:24
hi @ztephm closing til we can replicate it. Thanks!

**Comment by nygeog** [comment] 2016-11-08 12:34
Try to view it as the ..../embed. Also, try it with a legacy Editor map as the customer did.

**Comment by nygeog** [comment] 2016-11-10 14:50
Hey @saleiva we had to roll this paid user back to Editor. This issue hasn't been fixed for this case. All of those screenshots are in the platform, not the *embed* map.

**Comment by nobuti** [comment] 2016-11-10 15:16
Hi @nygeog sorry for any trouble it may have caused to you, I'm still trying to reproduce it but even in the embed, the category legend seems to be generated without any problem.

![virtualbox_ie11 - win8_embed](https://cloud.githubusercontent.com/assets/1366843/20182084/da2c7c14-a760-11e6-88a6-26606e59ea3f.png)

I'll keep working on that.

**Comment by xavijam** [comment] 2016-11-10 15:18
Woot, the zoom control is weird cc @piensaenpixel.

**Comment by nygeog** [comment] 2016-11-10 15:21
Does it work on this map (http://redpawtechnologies.com/test_page2/) for you in IE? I rolled this user back to Editor, so not sure if that'll make the legends work now.

**Comment by nobuti** [comment] 2016-11-11 16:41
@ztephm @nygeog I've just pushed a fix, could you confirm is working for you too? I don't trust in my local environment anymore...

![virtualbox_ie11 - win8 - legends](https://cloud.githubusercontent.com/assets/1366843/20222474/c7565198-a835-11e6-993e-fd4469d9e7bb.png)

**Comment by nygeog** [comment] 2016-11-12 11:50
This user has been moved back to Editor so legends are now working in IE. We can't really test against him w/ this map anymore since he's been pushed back to Editor.

**Comment by nobuti** [comment] 2016-11-12 12:32
But this map is from Builder right? https://mayadog4.carto.com/builder/e3170b2e-3c79-406f-8ef9-61ccc32fe0f9/embed

Enviado desde mi iPhone

**Comment by michellechandra** [comment] 2016-11-29 22:07
The user is reporting that the issue is still occurring in Internet Explorer. 

http://redpawtechnologies.com/annarbor/

**Comment by rubenmoya** [comment] 2018-05-22 07:48
It seems like this was fixed in https://github.com/CartoDB/carto.js/pull/1498

I tested it in `Internet Explorer 11.0.9600.18860` and it's working.

**Closed by rubenmoya** 2018-05-22 07:48 UTC
Labels: Frontend, bug
