### ISSUE TITLE
Style Tab: all CartoCSS edits revert on one new Values edit - for both Clear and Continue

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#8345] opened 2016-06-29 23:17 UTC
In Style tab:
edits made in CartoCSS panel are erased when you toggle back to Values panel, hit Continue, and make one change in the Values panel. 

The same behavior happens if you click Clear instead of Continue. 

## Context
(I have animated gif if u need - didn't want to post full UI yet)

## Process
1. From Maps page click New Map > Connect dataset & Submit this url, then click Connect (don't sync): https://javi.cartodb.com:443/api/v2/sql?q=select%20*%20from%20javi.paradas_metro_madrid&format=geojson
2. Click into cartodb_query layer
3. Click STYLE tab
4. Change marker fill & stroke colors, enable Labels & change label size & color
5. Click toggle to CartoCSS
6. Make edits to CartoCSS 
7. Click toggle back to Values
8. Click Continue
9. While you're still in the Values panel change the marker fill color

(Repeat, but choose Clear in step 8 instead of Continue)

## Expected result
All previous edits you made in CartoCSS will stay the same except for the parameter you just changed in Values.

## Current result
The latest Values change is being applied, but it gets rid of all other CartoCSS edits you made in the previous step.

----------------------------------------------------------------------------------------------------------------------------------
'Clear' should revert all edits when going back to Values panel, right?

'Continue' should save all edits, right? - so for example if I change marker fill color & font size in CartoCSS panel, toggle back to Values, click Continue, and change marker fill color from Values panel, font size should *not* revert also?

----------------------------------------------------------------------------------------------------------------------------------
Not sure if these are related? 
https://github.com/CartoDB/cartodb/issues/8150
https://github.com/CartoDB/cartodb/issues/7821

**Comment by saleiva** [comment] 2016-06-30 07:21
Hey! Since keeping the styles and modifying only the desired parameters (after applying CartoCSS) is not technically possible right now, I consider this a duplicate of https://github.com/CartoDB/cartodb/issues/7823

Thanks for reporting! :)

**Closed by saleiva** 2016-06-30 07:21 UTC

**Comment by javisantana** [comment] 2016-06-30 07:23
nice report BTW
