### ISSUE TITLE
Time series widget filter issue

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#7365] opened 2016-05-11 14:37 UTC
STR:
1. Import [twitter_t3chfest_reduced.csv.zip](https://github.com/CartoDB/cartodb/files/259526/twitter_t3chfest_reduced.csv.zip) dataset and create a map with it.
2. Open the map with the new editor.
3. Add a time series widget based on `postedtime` column (it should've been imported as `Date`).
4. Filter a time window. It will fail with `404 Not Found` and the following message: `Error creating the map instance on Windshaft: operator does not exist: date >= integer`

This is the query:

``` bash
curl 'https://juanignaciosl.cartodb.com/api/v1/map?stat_tag=d8be2808-1784-11e6-b15c-0e674067d321&api_key=***&filters=%7B%22dataviews%22%3A%7B%22d72963f9-44db-49e0-b2e1-f408341b0cab%22%3A%7B%22min%22%3A1423481850%2C%22max%22%3A1423745100%7D%7D%7D' -H 'Origin: https://team.cartodb.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8,es;q=0.6,en-GB;q=0.4' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: https://team.cartodb.com/u/juanignaciosl/editor/d8be2808-1784-11e6-b15c-0e674067d321' -H 'Connection: keep-alive' --data-binary '{"layers":[{"type":"cartodb","options":{"cartocss":"/** simple visualization */\n\n#twitter_t3chfest_reduced_2{\n  marker-fill-opacity: 0.9;\n  marker-line-color: #FFF;\n  marker-line-width: 1;\n  marker-line-opacity: 1;\n  marker-placement: point;\n  marker-type: ellipse;\n  marker-width: 10;\n  marker-fill: #FF6600;\n  marker-allow-overlap: true;\n}","cartocss_version":"2.1.1","interactivity":[],"source":{"id":"d69c2ee8-96a4-4147-a327-bff20796841c"}}}],"dataviews":{"d72963f9-44db-49e0-b2e1-f408341b0cab":{"type":"histogram","source":{"id":"d69c2ee8-96a4-4147-a327-bff20796841c"},"options":{"column":"postedtime","bins":256}}},"analyses":[{"id":"d69c2ee8-96a4-4147-a327-bff20796841c","type":"source","params":{"query":"select * from twitter_t3chfest_reduced_2"}}]}' --compressed
```

cc @xavijam @alonsogarciapablo @rochoa

**Comment by alonsogarciapablo** [comment] 2016-05-11 14:45
This looks like a duplicate of CartoDB/Windshaft-cartodb#419.

**Comment by juanignaciosl** [comment] 2016-05-11 15:01
Probably, although this is not a Torque layer.

**Comment by noguerol** [comment] 2017-03-15 12:46
Fixed.

**Closed by noguerol** 2017-03-15 12:46 UTC
Labels: bug
