### ISSUE TITLE
Dragging out a analysis to make a new layer and then deleting that layer makes map unloadable

### ISSUE THREAD

**Issue by joepringle** [CartoDB/cartodb#9246] opened 2016-08-02 21:43 UTC
I managed to completely and irreparably break this map:  

[](https://team.carto.com/u/jpringle/builder/f8c52dcc-5825-11e6-8540-0e05a8b3e3d7/embed?) 
https://team.carto.com/u/jpringle/builder/f8c52dcc-5825-11e6-8540-0e05a8b3e3d7/embed?

The map has 2 layers -  19 hospitals in San Bernadino county CA and block level population data for the county. 

Datasets:
[](https://team.carto.com/u/jpringle/tables/san_bernardino_block_groups)
[](https://team.carto.com/u/jpringle/tables/ca_hospital_general_information_sb_1)

Repro: (note i tried but can't reproduce this but I'm sharing the original series of steps before it broke)

1)  I did a driving time AOI on the hospital dataset, and then an intersect with the population layer. 
2) dragged the AOI to a new layer, deleted it because I meant to drag the aggregate layer
3) dragged then aggregate analysis to a new layer, and it hung.  
4) I tried to refresh, and poof - map’s broken.  Is it worth filing a github issue for this even though I can’t reproduce it? (i tried).  Thanks.

Here's the error message from chrome inspector:

cartodb.js 4.0.0-alpha.1
https://jpringle.carto.com/api/v1/map/named/tpl_f8c52dcc_5825_11e6_8540_0e05a8b3e3d7?stat_tag=f8c52dcc-5825-11e6-8540-0e05a8b3e3d7 Failed to load resource: the server responded with a status of 400 (Bad Request)
tracker.js:10 Error: Map instantiation failed(…)

**Comment by viddo** [comment] 2016-08-03 09:29
@joepringle Thanks for taking the time to report this!

>  Is it worth filing a github issue for this even though I can’t reproduce it? (i tried)

IMHO yes, because it highlights problems on the builder that needs a solution. The more reports we get the easier it is to motivate spending time to solve it.

I've not been able to reproduce it neither (thanks for thorough STR though!), but the root problem [is known, and have been discussed earlier](https://github.com/CartoDB/cartodb/issues/7608), but was decided offline to be postponed for the time being. But due to this issue (and more) it's been decide to prioritize it now 👉  #9257 so hopefully we'll have a solution promptly. 

So, I'll close this issue for now, if you manage to reproduce it consistently feel free to re-open it and provide any steps/dataset that may be missing.

**Closed by viddo** 2016-08-03 09:29 UTC
Labels: bug, Builder
