### ISSUE TITLE
Text Overlay changes not in sync

### ISSUE THREAD

**Issue by chriswhong** [CartoDB/cartodb#3165] opened 2015-04-13 17:54 UTC
On this map:

https://team.cartodb.com/u/chriswhong/viz/4a3c5ac4-e066-11e4-9567-0e4fddd5de28/map

Text in the 2nd overlay box from the top was not updating... it showed one thing in the editor, and another when viewed using the share link.  

Editing the text fixed the issue, but it was out of sync for a while.

**Comment by javisantana** [comment] 2015-04-14 07:17
probably duplicated

**Comment by javierarce** [comment] 2015-04-14 07:44
Can you reproduce the issue consistently? 

I've tried this several times and always worked fine:

1. Create a text overlay.
2. Double click to change the default text.
3. Write something.
4. Click outside the box.
5. Open the public map.

**Comment by javierarce** [comment] 2015-04-14 07:46
Oh, I've discovered that if you click the 'esc' key and don't click outside the box, the overlay is not saved (because the save event is only triggered when the box is unselected). Maybe this was the issue?

**Comment by chriswhong** [comment] 2015-04-14 14:31
I believe it was a network issue... I can't reproduce it on demand, but it
has happened to me twice since I started 2 weeks ago.  Reloading the editor
window shows my changes, but the published map remains unchanged.

**Comment by javierarce** [comment] 2015-04-20 16:55
Ok, I'm closing this issue, since we can't replicate the problem consistently.

**Closed by javierarce** 2015-04-20 16:55 UTC
Labels: 2 - Working
