### ISSUE TITLE
Builder time widget is not precise

### ISSUE THREAD

**Issue by jaakla** [CartoDB/cartodb#11294] opened 2017-01-18 14:57 UTC
### Context
* Created table with GPS locations, one point every 10 seconds or so, with gps_time (date) field
* I added and continue to add data to the table in real time using SQL API INSERT. I have data for about 6 days (150000 points now)
* Created map and widget with timeline of GPS locations
 
### Steps to Reproduce
Either try with steps above, or I can share the map ID to see how it works

### Current Result
Two issues, maybe same or even different:
1. **Text labels in timeline graphics and text are shifted**. See image 1 - in graphic I try to select _Sat 14 12PM to Wed 18 00:00_. I try to put as close to the horizontal lines which seem to be in midnight and midday. But the Selected: shows from 5:31 to 5:26 - more than 5 hours off from the selection. In different days I see quite different shift, sometimes it is just 1-2 hours off, sometimes more. It may depend on length of the time bar.
2. **Selection itself is wrong**, it does not match neither graphical nor textual "Selected from..." text. See second example - I have selected as short time frame as I can - text shows "Selected from 22:27 to 00:00". This should not select and show any points on map at all, as time is now 16:43 and I have no data for the future in the table. Also labels on map and hover on map shows that the points are from past and outside of selected range, with earliest point from 14:40. See second screenshot. It does filter out some of the points, as if I turn off filter then I see more points; the filter error seems to be about 7 hours here.

### Expected result
* Timeline graph text and graphical part match each other more precisely
* Time graph selection works precisely and allows to select specific time ranges

### Browser and version
* Latest Chrome on mac 

### Additional info
*Please PM me to get the data or access; the dataset includes private/personal data
![screenshot 2017-01-18 16 38 41](https://cloud.githubusercontent.com/assets/5609650/22068606/3b8fb746-dd9e-11e6-86e6-c1df09336c80.png)
![screenshot 2017-01-18 16 47 34](https://cloud.githubusercontent.com/assets/5609650/22068611/3f11e902-dd9e-11e6-8183-541cce833c4d.png)

**Comment by jaakla** [comment] 2017-01-18 15:00
Probably overlaps partly https://github.com/CartoDB/cartodb/issues/10946

**Comment by javisantana** [comment] 2017-04-28 12:12
do you have the .carto? with that information is not possible to reproduce the issue

**Comment by jaakla** [comment] 2017-05-04 10:20
Cannot repro now also. It may be related to fact that my data is dynamic - new records are added all the time, so the timeslider was "calibrated" using older timeranges, and later not refreshed. It is also not refreshed when I force data range change, e.g. set some smaller timerange in data SQL.

**Comment by saleiva** [comment] 2017-05-04 11:12
Closing this then, since this could be related with a prev fix done

**Closed by saleiva** 2017-05-04 11:12 UTC
Labels: bug, Frontend
