### ISSUE TITLE
Send e-mail on "normal" licensing

### ISSUE THREAD

**Issue by alrocar** [CartoDB/cartodb#15137] opened 2019-10-13 21:34 UTC
https://github.com/CartoDB/cartodb/pull/15136#issuecomment-541461914

**Flow and copies**
https://docs.google.com/document/d/13NYr2t_IqN9ox_utr_uNL1vg9Bn3Ums2jSJqRs7u-O8/edit

**Comment by gonzaloriestra** [comment] 2019-10-14 06:16
@cmongut reminder to find out the recipient :pray:

**Comment by cmongut** [comment] 2019-10-14 20:20
👋 Are we managing the case where the user isn't an enterprise one? Could we check that?

**Comment by gonzaloriestra** [comment] 2019-10-14 20:23
No, but this endpoint is under Feature Flag (and we could enable it just for orgs).

**Comment by gonzaloriestra** [comment] 2019-10-14 20:24
Or we could check it as well, no problem.

**Comment by cmongut** [comment] 2019-10-14 20:44
Both options are perfect. Let me check with customer success to see if they have a generic email

**Comment by gonzaloriestra** [comment] 2019-10-25 09:58
Catalog requests have been enabled from builder, so we should do the same here instead of sending an email (it seems like it uses Hubspot).

**Comment by cmongut** [comment] 2019-11-18 07:41
I have updated the first comment and move the flow and copies to a [doc](https://docs.google.com/document/d/13NYr2t_IqN9ox_utr_uNL1vg9Bn3Ums2jSJqRs7u-O8/edit):

@gonzaloriestra could you confirm it makes sense?
@xavipereztr could you review the copies?

**Comment by xavipereztr** [comment] 2019-11-18 10:04
Hi @cmongut 

This process is only for datasets available for speed licensing (eg. the user know the price already) or for any dataset advertised in the Discovery catalog?

**Comment by cmongut** [comment] 2019-11-18 10:12
I was just taking the field `estimated_delivery_days` into account. What we should do is to update the subscription copy when we don't have the price isn't it?

**Comment by xavipereztr** [comment] 2019-11-18 10:46
Basically what I am thinking is whether it should be a different process depending on how much information has been exposed to the customer. For the cases of "speed" or "quasi-speed" licensing in which the user may have seen already the prices and the T&Cs of the licenses etc., we can assume that the customer may be ready to buy. In the cases which the customer has not seen prices, business model of the data product, conditions in the licenses, etc....the best we can assume is that a consultative sales process will start and hence we'll need alignment with Sales.

Even if during the beta phase we handle both cases similarly (email to me), I think when we launch this into production we may want to treat them differently. So, now that you are developing it you may want to make the distinction by design.

**Comment by cmongut** [comment] 2019-11-18 12:47
I would treat both cases the same way for now. I wouldn't assume that our first users know everything about the license of the dataset. We can update the flow in the backend when we start seeing people with no doubts.

**Comment by gonzaloriestra** [comment] 2019-11-20 08:41
Regarding the process, this is the current subscription logic:
- We do not allow to subscribe if the dataset doesn't have `subscription_list_price`, `estimated_delivery_days` and `available_in`.
- When `estimated_delivery_days` = 0, we just enable it.
- When `estimated_delivery_days` > 0, we have to send the emails (the pending task)

Is it ok? Or should we allow to "subscribe" even without metadata and send the emails anyway?

**Comment by gonzaloriestra** [comment] 2019-11-20 08:45
About the email for the user, we are not sending anything in case of the "speed" license, but just showing a message from CARTOframes.

I think both types should have the same output for the user: message in CF + email (or just the message). What do you think?

**Comment by alasarr** [comment] 2019-11-25 13:54
The subscription logic depends on the user who made the request.

Subscription_info will return all the info if the user has access to DO.

Regarding subscribe:

### 1. Normal user with access to DO and without speed licensing

We always send the email, even if the following fields are null `subscription_list_price`,  `estimated_delivery_days` and `available_in` 

What we want first is to get the request of the user.

Always email

### 2. Normal user with access to DO and with speed licensing

All fields (`subscription_list_price`, `estimated_delivery_days` and `available_in`) must be not null.

Speed licensing only happens if  `estimated_delivery_days`> 0

### 3. Admin user from CARTO

All fields (`subscription_list_price`, `estimated_delivery_days` and `available_in)` must be not null. or set as a parameter at the caller task: https://github.com/CartoDB/cartodb-central/issues/2596

The aim of this issue is to resolve point 1.

**Comment by Jesus89** [comment] 2019-12-20 14:00
Closed via https://github.com/CartoDB/cartodb/pull/15315

**Closed by Jesus89** 2019-12-20 14:00 UTC
Labels: Backend, do-licensing
