### ISSUE TITLE
Distance validation on area of influence

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#8581] opened 2016-07-06 17:05 UTC
Distance at the area of influence validation are always integers:

- Meters go 1 to 100
- Kilometers go from 1 to 100

So I can't select anything between 100m and 1km :smile: 

![2016-07-06_18 53 41_selection](https://cloud.githubusercontent.com/assets/188264/16627120/27cdb9f6-43ac-11e6-89a8-d399c147a0a1.png)

![2016-07-06_18 54 17_selection](https://cloud.githubusercontent.com/assets/188264/16627108/1a33de1a-43ac-11e6-9039-367237b96a02.png)

### Expected result

* Be allowed to put float numbers at the text boxes 
* And probably also numbers above 100 even doing distance buffers above 100km will be rare (but still possible).

**Comment by xavijam** [comment] 2016-07-06 17:45
:joy: we know it, we know it. There is a component designed and we should implement it.
Thanks man 💋

**Comment by viddo** [comment] 2016-07-06 17:50
Duplicate of #7501

**Closed by viddo** 2016-07-06 17:50 UTC
Labels: bug, editor-3
