### ISSUE TITLE
Notify the user when a map becomes popular

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#4751] opened 2015-07-28 17:11 UTC
Add a new notification to the user when the user's map becomes popular.

What is the number of likes to promote a map to popular?

//  @saleiva

**Comment by saleiva** [comment] 2015-07-28 17:29
I'd say that more than 1K mapviews per day

**Comment by saleiva** [comment] 2015-07-29 08:50
Sorry, after doing a quick analysis, 500 mapviews would be better.

**Comment by ethervoid** [comment] 2015-07-30 11:40
I'm going to need the email design for this issue too

**Comment by ethervoid** [comment] 2015-08-20 14:41
One question. We want to send a unique notification or every 500 maps views achieved?

**Comment by saleiva** [comment] 2015-08-20 14:43
I'd do it exponential

500, 1250, 2500, ...

**Comment by ethervoid** [comment] 2015-08-20 14:46
We should establish a temporal limit for the check. What about 1 week?

**Comment by saleiva** [comment] 2015-08-20 14:48
what do you mean?

**Comment by ethervoid** [comment] 2015-08-20 15:00
The increment of mapviews is made a) by the tailer or b) with a cron script when the request was against a cached element so we need to check for trending maps asynchronously. This leads to filter the total amount of maps we need to process (we can't all the visualizations we have) so we need to put a temporal limit. For example only check the maps created from 1 week ago.

Also we need to cache the notifications we have sent (hence the previous question) and the mapviews value when we sent the notification.

**Comment by saleiva** [comment] 2015-08-20 15:40
That doesn't work, since you would not receive emails when a map becomes relevant for something in particular.

For example, a map about the apple stores expansion, that is published on a newspapaper each quarter.

**Comment by Kartones** [comment] 2015-09-11 14:27
Isn't this a duplicate of https://github.com/CartoDB/cartodb/issues/3366 ? :disappointed: 

Feels almost like the same, but per day

**Comment by ethervoid** [comment] 2015-09-11 14:41
Yes we can take to paths here:

a) Make the task check once per day and notify the trending maps of the day (that could be done quickly because we don't have to change the stats)
b) Check every hour if there is a trend map (this need more work and add values to the stats).

For the option B we need to store the state of the last notification mapviews number inside the `user:user_name:mapviews:stat_tag:visualization_id` zsets in a key called for example `notified_at`. With this stored we could check the delta between total, last notification mapviews number and current day number.

What do you think @saleiva ?

For the option B I'd like to know if there is a problem storing the `user:user_name:mapviews:stat_tag:visualization_id` key ( @rochoa @luisbosque )

**Comment by saleiva** [comment] 2015-09-13 17:42
For the time being, option A sounds logic.

**Comment by ethervoid** [comment] 2015-09-15 11:10
Here we have the mail, please @saleiva or @piensaenpixel or @carlostallon take a look and give feedback to change things :)

The subject of the mail is `Recent activity on one of your maps!`

![captura de pantalla 2015-09-15 13 04 54](https://cloud.githubusercontent.com/assets/741240/9875000/f22c1214-5baa-11e5-8eb2-8a7ccc6907f4.png)

**Comment by ethervoid** [comment] 2015-09-16 08:35
Bump!

**Comment by saleiva** [comment] 2015-09-16 08:42
What about adding the... More than XXXXX people have seen your map! or something like that? @csobier

**Comment by ethervoid** [comment] 2015-09-16 11:10
Yup I could add that, I have the amount of mapviews for that map. What about the heart icon, do you like it or we should put other?

**Comment by carlostallon** [comment] 2015-09-16 11:17
Why not the "eye" icon?

**Comment by csobier** [comment] 2015-09-16 11:53
I like the dialog as is above, but also agree with @saleiva , since it is actually the visit functionality.  (Do we need to add any more information about how maps are visited or how to turn on/off this notification?)

"Your **untitled map** has received XXXXX mapviews from your public profile!"

Also, while I do love the heart :-) that is a different feature, (the "like") feature (Correct me if I am wrong?)  Perhaps you should use the "visit" icon as an overlay on your map image to match the actual UI option.  Always match the interface options whenever possible, for consistency.

![image](https://cloud.githubusercontent.com/assets/13319925/9903709/8764f738-5c46-11e5-86d3-8746b62287c8.png)

![image](https://cloud.githubusercontent.com/assets/13319925/9903719/927ba6c6-5c46-11e5-9315-73349748e92d.png)

**Comment by piensaenpixel** [comment] 2015-09-17 08:29
Finally which icon? i agree with @csobier about we should use the "visit" icon

**Comment by carlostallon** [comment] 2015-09-17 08:54
I would use the eye, I agree that in that case we should change it also in the dashboard.

**Comment by carlostallon** [comment] 2015-09-17 08:55
Ouch, for activity (visits) I think this is the right icon

**Comment by ethervoid** [comment] 2015-09-17 10:17
I've been putting the mapsviews in a pretty way what do you think of this:

Congratulations!, Your **cb_2013_us_cbsa_5m** has received **8.43 Thousand mapviews** from your public profile!

**Comment by csobier** [comment] 2015-09-17 12:09
@ethervoid , text looks good.  You do not need the comma after the exclamation point though.  Just the exclamation point.  "Congratulations! Your ...."

**Comment by ethervoid** [comment] 2015-09-18 13:45
Final result (2 versions one with hundreds, another with thousands):

![captura de pantalla 2015-09-18 15 44 40](https://cloud.githubusercontent.com/assets/741240/9960662/345f593e-5e1c-11e5-8666-2eb6ddac1c55.png)

![captura de pantalla 2015-09-18 15 43 44](https://cloud.githubusercontent.com/assets/741240/9960670/3b66b3c6-5e1c-11e5-8d37-38904c15eedd.png)

**Comment by carlostallon** [comment] 2015-09-18 13:47
Like ti

**Comment by saleiva** [comment] 2015-09-18 14:06
I’d put an icon that means celebrating! or in case we want the chart, something showing more trend!

S.

-----
@saleiva

**Closed** 2015-09-21 10:54 UTC
Labels: 3 - Done

**Comment by mariodelvalle** [comment] 2015-09-21 12:27
Two proposals

Screenshot attached

![1](https://cloud.githubusercontent.com/assets/3064293/9991725/d435eb88-606c-11e5-87b2-d94850da49fa.png)

![2](https://cloud.githubusercontent.com/assets/3064293/9991726/d4371012-606c-11e5-8eb1-17d1690228be.png)

**Comment by saleiva** [comment] 2015-09-21 14:08
Ok, I'd go with the 1st one. The CHAMPIONS LEAGUE one
