### ISSUE TITLE
line-offset makes the tile borders visible

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#12017] opened 2017-04-18 15:17 UTC
### Context
Trying to style a layer using `line-offset` and the tiles borders become visible as a side effect

### Steps to Reproduce
1. Create a map from a polygon dataset or from scratch with an empty layer, and then draw a polygon by hand
2. Style the layer with an extra border with Npx offset as
```css
#layer {
  polygon-fill: #374c70;
  polygon-opacity: 0;
  line-width: 2;
  line-color:red;
  line-opacity: 1;
}
#layer::2 {
  polygon-fill: #374c70;
  polygon-opacity: 0;
  line-width: 2;
  line-color: blue;
  line-opacity: 1;
  line-offset:-3;
}
```

### Current Result
**red lines:** actual polygon border
**blue lines:** polygon border with offset

* If offset is < 0: the tiles that intersect my polygon has visible borders **inside** the polygon
![image](https://cloud.githubusercontent.com/assets/9017165/25138222/40269cd6-245a-11e7-815b-9107b2196f7d.png)

* If offset = 0: Behavior as expected
![image](https://cloud.githubusercontent.com/assets/9017165/25138245/4e1ba43a-245a-11e7-9cd0-8bc6c8341e5a.png)

* if offset > 0: the tiles that intersect my polygon has visible borders **outside** the polygon
![image](https://cloud.githubusercontent.com/assets/9017165/25138277/657a0b08-245a-11e7-8ad3-237c05657375.png)

### Expected result
Just no tiles borders :)

### Browser and version
Any

### .carto file
[test_offset.carto.zip](https://github.com/CartoDB/cartodb/files/930176/test_offset.carto.zip)

### Additional info
*Please add any information of interest here below*

**Comment by makella** [comment] 2018-02-28 18:17
Sorry I never posted, but found a temporary workaround haven't tested lately, but you can see here

![tile-artifacts](https://user-images.githubusercontent.com/1566273/36804683-8bcd0fa0-1c78-11e8-97e9-2aba39f2f7ed.gif)

**Comment by rafatower** [comment] 2018-05-11 08:49
It can be reproduced easily in local, with and without metatiling. I could not confirm it yet, but I'm pretty sure the bug is within mapnik, most likely around these lines:

https://github.com/mapnik/mapnik/pull/2955/files

(offset converter, line symbolizer)

Aside, as @makella pointed out, there's a workaround to it, that I reproduce:
```css
#layer {
  
  // Use just one layer w/ 2 styles
  // this line-width below prevents the grid effect
  line-width: 0;
  
  ::top {
  	polygon-fill: #374c70;
  	polygon-opacity: 0;
  	line-width: 2;
  	line-color:red;
  	line-opacity: 1;
  }
  ::2 {
    polygon-fill: #374c70;
  	polygon-opacity: 0;
  	line-width: 2;
    line-color: blue;
    line-opacity: 1;
    line-offset: -3;
  }
}
```

I created a PR reverting the suspect change: https://github.com/CartoDB/mapnik/pull/59

but did not have time to test it. Mind that this is just a hail mary pass in an attempt of quickly fixing it...

**Comment by Algunenano** [comment] 2018-05-24 13:53
I'm having a look into into this. It can be solved by disabling [`line-clip`](https://carto.com/docs/carto-engine/cartocss/properties/#line-clip-boolean) in the second layer:
```
#layer {
  polygon-fill: #374c70;
  polygon-opacity: 0;
  line-width: 2;
  line-color:red;
  line-opacity: 1;
}
#layer::2 {
  polygon-fill: #374c70;
  polygon-opacity: 0;
  line-width: 2;
  line-color: blue;
  line-opacity: 1;
  line-offset:-3;
  line-clip: false; //<<<<<<<<<<
}
```

**Comment by Algunenano** [comment] 2018-06-04 11:00
I have it partially fixed (it was an issue in where the clipping was being done):
![image](https://user-images.githubusercontent.com/664253/40914060-04aab5fc-67f7-11e8-8bf1-53a14f9be490.png)

But I've noticed that the clipping has some issues (you can see some lines disappearing now) so I'm looking into this with a minimal test case to have it shipped together:
![image](https://user-images.githubusercontent.com/664253/40914111-3567632a-67f7-11e8-8ace-b84c3bd77ff8.png)
Left = no clipping, Right = with clipping

**Comment by Algunenano** [comment] 2018-06-04 17:27
The issue is found in how the offsetted points are calculated. After some changes I see both improvements and deterioration in the visual tests, so this is really tricky to get it right:
![image](https://user-images.githubusercontent.com/664253/40931826-c61fae74-682c-11e8-951a-01bda0b3bd6f.png)

I'll see if I can find a better compromise since the issue with the test from my previous message is that after clipping the points are too close (closer than the static threshold) so it decides to skip them. I'll look into making that threshold more dynamic (based on the properties of the CartoCSS) or increase the distance to the clipping grid.

**Comment by Algunenano** [comment] 2018-06-05 14:51
Should be fixed with https://github.com/CartoDB/mapnik/pull/63

Since it requires review, performance regression tests and multiple intermediate releases it might take a while to get it into production. I'll let you know once it's ready.

**Comment by Algunenano** [comment] 2018-06-11 09:13
Moving this out of RT. It'll be deployed with the next Mapnik release

**Comment by ramiroaznar** [comment] 2018-06-29 13:05
Fixed in https://github.com/CartoDB/cartodb/pull/14124

**Comment by Jesus89** [comment] 2018-06-29 13:13
@ramiroaznar I'm not sure that this is related to #14124.

I think it's related to mapnik (engine), but it can be closed since they are going to deploy Mapnik soon.

**Comment by Algunenano** [comment] 2018-06-29 13:17
Yeah, it's not related to #14124. I'm keeping this open until the fix is released and installed in production.

**Comment by ramiroaznar** [comment] 2018-06-29 13:31
Sorry! Yes, I see it is not the same problem.

**Comment by Algunenano** [comment] 2019-04-15 12:10
> Yeah, it's not related to #14124. I'm keeping this open until the fix is released and installed in production.

Well, it's only taken me 13 months but it's now in production.

**Closed by Algunenano** 2019-04-15 12:10 UTC
Labels: Backend, bug, cartography

**Comment by makella** [comment] 2019-04-15 18:08
woot!!

**Comment by ramiroaznar** [comment] 2019-04-16 10:00
:100:
