### ISSUE TITLE
Ghost table not removed if it has a named map

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3712] opened 2015-05-20 12:34 UTC
A table was removed by a user months ago but this removal failed, although the table remained inaccessible in the dashboard.

After dropping it in the user database:

https://rollbar.com/vizzuality/CartoDB/items/3942/?item_page=0&#instances

> Message action: 	"dropping table" appears several times for the table

https://rollbar.com/vizzuality/CartoDB/items/6793/?item_page=0&#instances

> This error conincides with the dropping attemps (catched by @juanignaciosl):

````
CartoDB::NamedMapsWrapper::HTTPResponseError: GET:403 http://10.0.1.254:80/api/v1/map/named/tpl_a38c3adc_a262_11e4_924a_0e018d66dc29?api_key= {"error":"Error: Only authenticated users can get template maps"}
1
File "/home/ubuntu/www/production.cartodb.com/releases/20150520104210/services/named-maps-api-wrapper/lib/named-maps-wrapper/named_maps.rb", line 69 in get
2
File "/home/ubuntu/www/production.cartodb.com/releases/20150520104210/app/models/visualization/member.rb", line 450 in has_named_map?
3
File "/home/ubuntu/www/production.cartodb.com/releases/20150520104210/app/models/visualization/member.rb", line 232 in delete
4
File "/home/ubuntu/www/production.cartodb.com/releases/20150520104210/app/models/table.rb", line 671 in each
5
File "/home/ubuntu/www/production.cartodb.com/releases/20150520104210/app/models/table.rb", line 671 in after_destroy
6
File "/home/ubuntu/www/production.cartodb.com/releases/20150520104210/app/models/table/user_table.rb", line 209 in after_destroy
... 16 non-project frames
23
File "/home/ubuntu/www/production.cartodb.com/releases/20150520104210/app/models/user.rb", line 1211 in block in link_deleted_tables
24
File "/home/ubuntu/www/production.cartodb.com/releases/20150520104210/app/models/user.rb", line 1204 in each
25
File "/home/ubuntu/www/production.cartodb.com/releases/20150520104210/app/models/user.rb", line 1204 in link_deleted_tables
26
File "/home/ubuntu/www/production.cartodb.com/releases/20150520104210/app/models/user.rb", line 1096 in link_ghost_tables
27
File "/home/ubuntu/www/production.cartodb.com/releases/20150520104210/lib/resque/user_jobs.rb", line 16 in perform
... 30 non-project frames
28
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb" line 240 in block (3 levels) in perform
29
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-metrics-0.1.1/lib/resque/metrics.rb" line 353 in around_perform_metrics
30
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb" line 239 in block (2 levels) in perform
31
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb" line 247 in call
32
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/job.rb" line 247 in perform
33
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb" line 250 in perform
34
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb" line 189 in block in work
35
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb" line 166 in loop
36
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/worker.rb" line 166 in work
37
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/resque-1.25.2/lib/resque/tasks.rb" line 41 in block (2 levels) in <top (required)>
38
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb" line 205 in call
39
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb" line 205 in block in execute
40
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb" line 200 in each
41
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb" line 200 in execute
42
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb" line 158 in block in invoke_with_call_chain
43
File "/usr/lib/ruby/1.9.1/monitor.rb" line 211 in mon_synchronize
44
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb" line 151 in invoke_with_call_chain
45
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb" line 144 in invoke
46
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb" line 116 in invoke_task
47
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb" line 94 in block (2 levels) in top_level
48
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb" line 94 in each
49
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb" line 94 in block in top_level
50
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb" line 133 in standard_exception_handling
51
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb" line 88 in top_level
52
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb" line 66 in block in run
53
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb" line 133 in standard_exception_handling
54
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb" line 63 in run
55
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake" line 33 in <top (required)>
56
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake" line 19 in load
57
File "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/bin/rake" line 19 in <main>
````

cc @javisantana @Kartones

**Comment by rafatower** [comment] 2015-05-21 09:04
@iriberri S/B 5402076? This might have been the problem again: https://github.com/CartoDB/cartodb/commit/468f8a5c

Also related with https://github.com/CartoDB/cartodb/issues/3286 ?

It's better to paste the link to rollbar occurrences for future reference.

**Comment by iriberri** [comment] 2015-05-21 09:28
https://rollbar.com/vizzuality/CartoDB/items/3942/occurrences/5464731433/

**Comment by juanignaciosl** [comment] 2015-07-13 14:04
I haven't been able to reproduce this. This is what I've done (staging):

1. Set 2 tables private.
2. Use both in a public visualization in order to create a named map (I checked viz.json, there was a namedmap).
3. Delete both in the console.
4. Enter the dashboard, triggering deletion ([1](https://rollbar.com/vizzuality/CartoDB/items/4426/occurrences/6473381765/) and [2](https://rollbar.com/vizzuality/CartoDB/items/4426/occurrences/6473381373/).

Both datasets and map are gone, no error. @iriberri am I missing something? I'll close otherwise. Looks like it's been solved during this weeks. Also, error might be related with the URL missing the api_key.

**Comment by iriberri** [comment] 2015-07-13 14:10
This is not something that I could reproduce but errors that happened to users. I haven't detected any more of this after this issue (neither before), so probably this is something worthy to take a quick look to see if there's something obviously wrong and if not we can just remain alert I guess.

**Comment by juanignaciosl** [comment] 2015-07-13 14:20
Ok. I'll close this to remove the clutter. Since this involves several moving parts that have changed since then (ghost tables, named maps, that strange missing api_key...) we can focus on new cases if there's any. Thanks!

**Closed by juanignaciosl** 2015-07-13 14:20 UTC
Labels: 2 - Working, backend, bug
