### ISSUE TITLE
[POPUPS] Cannot edit infowindows anymore

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7499] opened 2016-05-24 18:25 UTC
In an existing map where infowindows used to work, I cannot change them any more since whenever I try to edit it gives the following error

tracker.js:17 PUT https://team.cartodb.com/u/saleiva/api/v1/maps/aa9e61af-af76-492b-bebc-cdc7ca5915b6/layers/433001e5-7526-4cf9-a269-d0c3ffe6f164 500 (Internal Server Error)

a.send @ tracker.js:17Y.cors.a.crossDomain.send @ jquery:8630_.extend.ajax @ jquery:8166b.ajax @ backbone.js:1428b.sync @ backbone.js:1411c.extend.sync @ backbone.js:436b.exports @ sync-abort.js:16c.extend.save @ backbone.js:647b.Model.extend.save @ backbone-model-file-upload:116f.Model.extend.save @ model.js:71(anonymous function) @ infowindow-fields-view.js:28i @ underscore:828d.util.hasFunction.f.(anonymous function) @ tracker.js:3

cc/ @xavijam

**Comment by matallo** [comment] 2016-05-25 16:20
can't reproduce (with an existing map with infowindows), we've merged a PR with infowindows changes, is this still happening?

thanks!

**Closed** 2016-05-25 17:44 UTC
Labels: bug
