### ISSUE TITLE
Geocoding don't geocode all rows

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#3746] opened 2015-05-23 16:00 UTC
I've imported [this table](http://15mpedia.org/wiki/Lista_de_casos_de_corrupci%C3%B3n) into [this one](https://team.cartodb.com/u/juanignaciosl/tables/corrupcion_espana/public) and geocoding doesn't work as expected. Many rows are not geocoded in spite of having the same value. I've geocoded with "ambito" column in "Spain" country, and, for example, Baleares is geocoded in row 65 but not in row 77.

**Comment by iriberri** [comment] 2015-05-25 12:27
I have detected this behaviour too

**Comment by iriberri** [comment] 2015-11-26 14:10
Cannot reproduce anymore. Closing. :-)

**Closed by iriberri** 2015-11-26 14:10 UTC
Labels: geocoding
