### ISSUE TITLE
Category maps breaking in Firefox+Windows

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#11195] opened 2017-01-05 12:59 UTC
### Context
When trying to create a category map with more than 10 categories (using Firefox in a Windows machine), styling component breaks and TurboCARTO code is not generated properly, leading to a map instantiation error. 

### Steps to Reproduce

1. Make sure you're using a Windows machine and Firefox browser
2. Create a map, go to *STYLE* and select *BY VALUE* visualization
3. Use a column with **more than 10 categories**
4. Interface will break like in the screenshot

![screen shot 2017-01-05 at 13 13 55](https://cloud.githubusercontent.com/assets/10940006/21681149/343cb8b8-d34e-11e6-94b2-da234fd02ded.png)

5. If you click again on the *FILL* parameter, you'll see this: 

![screen shot 2017-01-05 at 13 23 25](https://cloud.githubusercontent.com/assets/10940006/21681171/564d62cc-d34e-11e6-9149-a436ba00841a.png)

6. CartoCSS code looks like this, it lacks some parameters and the map won't instantiate: 

```
 polygon-fill: ramp([categorie]);
```

7. As soon as you open the *FILL* component in a different browser, the error corrects itself and the map works as usual

### Current Result
TurboCARTO code is not generated properly and the map instantiation isn't successful 

### Expected result
The map should be instantiated OK

### Browser and version
Tested on a [Windows 7 VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) with [Firefox last version](https://www.mozilla.org/en-US/firefox/new/) 

### Additional info
This doesn't reproduce with other browser/OS combinations. Tested so far:

- Chrome + Mac
- Firefox + Mac
- Chrome + Windows

cc/ @saleiva

**Comment by MariaCheca** [comment] 2017-01-16 14:05
Unassigned the issue because I've not been able to reproduce it in a local environment following the steps in the issue. @ernesmb is making sure if it still happens or not.

**Comment by MariaCheca** [comment] 2017-01-16 14:09
Looks like this is not happening again, as it has been tested again with the same datasets that were failing and now it looks ok. So closing the issue :)

Thanks for reporting it @ernesmb!

**Closed by MariaCheca** 2017-01-16 14:09 UTC
Labels: bug, Frontend
