### ISSUE TITLE
Viewer users cannot acces their own maps if marked as private

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#12171] opened 2017-05-23 07:42 UTC
### Steps to Reproduce
1. As a builder
2. Create a map, make it private
3. Convert your user to viewer
4. Try to open your map (from dashboard)

### Current Result
Map does not exist or is private error

### Expected result
You can view your map.

cc @juanignaciosl

**Comment by mayoral** [comment] 2017-05-29 09:01
I've tested on both on domainless and domainfull users and orgs, but I can't reproduce the behaviour, it always works as expected: the viewer can see his private map.

Closing this issue, but I'll keep an eye on this.

**Closed by mayoral** 2017-05-29 09:01 UTC
Labels: Backend, bug
