### ISSUE TITLE
Not possible to download a table that has been shared with someone on read only mode

### ISSUE THREAD

**Issue by jatorre** [CartoDB/cartodb#9449] opened 2016-08-16 16:40 UTC
When part of a team account. Someone shares a dataset with you with read only. It appears on the list of tables shared with you. You can click on it and you get sent to the public view of the table.

For example:

https://team.carto.com/u/jatorre-test/tables/jmartin-cdb.daily_basemap_referrers/public/map?redirected=true

If you click the button to download and get the CSV you get sent to this page:

https://jatorre-test.carto.com/api/v2/sql?filename=daily_basemap_referrers&q=select+*+from+%22jmartin-cdb%22.daily_basemap_referrers&format=csv&bounds=&api_key=&skipfields=the_geom_webmercator

Where it says:

`{"error":["permission denied for relation daily_basemap_referrers"]}`

For the record If I click on create map I also get to a page to create an account, but that might be a different issue?

**Comment by juanignaciosl** [comment] 2016-08-17 09:04
Ok:

1.- Download error: CSV download is missing the api key, that's why there's a permission error.
2.- Create map error: I can't reproduce your "create an account redirection", but creating from from private shared datasets won't work, I've opened an issue: #9458. Could you give us more details about your issue? The privacy of the dataset, for example, is likely to be relevant (although I've tried without being able to reproduce that issue).

**Comment by juanignaciosl** [comment] 2016-08-17 09:07
So this is actually a duplication of #6020, which should be fixed after #6002. I'm closing this to continue the discussion at the previous one. Please open an issue if you manage to reproduce the redirection to account creation, please.

**Closed by juanignaciosl** 2016-08-17 09:07 UTC
Labels: bug, duplicate
