### ISSUE TITLE
the_geom guessed as double instead of Geometry

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#5595] opened 2015-09-18 11:44 UTC
Here's the input file: https://gist.githubusercontent.com/rafatower/f2b6c2918a66749d5898/raw/5a345f34cb57c41f506af54a335f9389dbfc69f0/untitled_table_3%2520(2).csv

And here's the failure:
```
true: Errored importing data from /tmp/imports/20150918-26933-1dz6hjn/untitled_table_3%25202.csv:
false: Sequel::DatabaseError: PG::Error: ERROR:  invalid input syntax for type double precision: ""
LINE 4:           AND the_geom != ''
                                  ^

```
It happens around the georeferencer.rb and column.rb classes.

**Comment by gfiorav** [comment] 2015-09-23 14:51
Filed a ticket to osgeo.org

You can see it [here](https://trac.osgeo.org/gdal/ticket/6128#no1)

**Comment by gfiorav** [comment] 2015-09-24 13:33
@rafatower 

On purpose of making CartoDB more robust against this error:

I've found that the method call that causes the issue is this one:
https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/column.rb#L58

`raise "empty column #{column_name}" if empty?`

In context:
```ruby
def geometrify
  job.log 'geometrifying'
  raise "empty column #{column_name}" if empty?
  convert_from_wkt                                  if wkt?
  convert_from_kml_multi                        if kml_multi?
  convert_from_kml_point                        if kml_point?
  convert_from_geojson_with_transform if geojson? && @from_geojson_with_transform
  convert_from_geojson                           if geojson?

  cast_to('geometry')
  convert_to_2d
  job.log 'geometrified'
  self
end
```

I'm trying to find a way to universally check if a string is empty or a number 0 so to modify the subsequent call in https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/column.rb#L221-L228

```ruby
def records_with_data
  @records_with_data ||= db[%Q{
    ELECT #{column_name} FROM "#{schema}"."#{table_name}"
    WHERE #{column_name} IS NOT NULL
    AND #{column_name} != ''
    LIMIT 1
  }]
end
```

so that `!= ''` doesn't make the code break in case that `the_geom` is interpreted as a number.

**Comment by rafatower** [comment] 2015-09-24 16:43
geometrify is only called on certain columns, right? there's an overlap between that code and this ticket: #4730

**Comment by gfiorav** [comment] 2015-09-25 14:27
@rafatower 

After our chat, it's still not clear for me what we should do in this case.

Should we:
1. Add a deprecated warning and monitor this code
2. Remove this code

Any insight is greatly appreciated :smile:

**Comment by rafatower** [comment] 2015-09-25 14:38
For the moment, just make it robust. I'll add the deprecation note in my branch, since it is there where the supposedly unique usage is.

**Comment by gfiorav** [comment] 2015-09-25 14:39
Does that mean that PR #5743 can be merged? (Not today, on Monday)

**Closed** 2015-09-28 12:27 UTC
Labels: 0 - Backlog, bug, importer
