### ISSUE TITLE
#MG26 Admin aggregation doesnt work

### ISSUE THREAD

**Issue by AleGoiko** [CartoDB/cartodb#11811] opened 2017-03-21 16:27 UTC
### Context
*Please explain here below what you were doing when the issue happened*

 Performing smote test #MG26

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. upload dataset (http//www.naturalearthdata.com/download/10m/cultural/ne_10m_populated_places.zip)
2. click on dataset layer
3. click on style and choose admin

### Current Result
*Please describe here below the current result you got*

aggregation doesnt take place and I get this error:
`ne_10m_populated_places_copy: Failed to process "polygon-fill" property: unable to compute ramp, could not connect to server "aggregation"`

 

### Expected result
*Please describe here below what should be the expected behaviour*

a map with areas aggregated by admin region

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version* 

chrome 56.0.2924.87

 

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

http//www.naturalearthdata.com/download/10m/cultural/ne_10m_populated_places.zip
 

### Additional info
*Please add any information of interest here below*

**Comment by alonsogarciapablo** [comment] 2017-03-22 10:15
@rochoa rings a bell?

**Comment by alonsogarciapablo** [comment] 2017-03-23 12:03
It looks like this is caused by a problem with the staging server that was used for the smokes. Closing this then.

**Closed by alonsogarciapablo** 2017-03-23 12:03 UTC
