### ISSUE TITLE
Ghost tables might be generating two tables with the same name and dropping incorrect vizs

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#6133] opened 2015-11-13 18:16 UTC
SB/7301378

**Scenario**:
* Two tables with the same name were listed in the dashboard
* When trying to delete one of them, it said it had X attached maps. When trying to delete the other, it didn't mention any attached map.
* User deletes the one with apparently "no attached maps"
* Both tables get removed of the account
* All maps related to them get removed

I have found a single "dropping table" event (occurrence # 8931111338) in Rollbar and a table with that name is not right now in the user database.

**Comment by anderser** [comment] 2015-11-13 19:34
Hi. I can elaborate on this since I reported the issue with CartoDB. The table(s) was created using the API via this small script I created: https://gist.github.com/anderser/4d20691122f8582eb3cd 
It first creates the tables and then "cartodbfy" (according to this: https://github.com/CartoDB/cartodb/wiki/creating-tables-though-the-SQL-API) them to make them visible in CartoDB. 

I had some trouble getting the tables created via the API to display in the list on cartodb.com - at least there was a significant delay. But in the end it worked out well. The table was updated pretty regularily on election night with new data every minute. I am afraid I am not quite sure when I saw that there were two tables with identical name/api-url in the list of tables.

**Comment by gfiorav** [comment] 2015-11-25 13:51
I found this in `link_ghost_tables` (see code [here](https://github.com/CartoDB/cartodb/blob/master/app/controllers/admin/visualizations_controller.rb#L431)):
```ruby
def link_ghost_tables
    return true unless current_user.present?

    if current_user.search_for_modified_table_names && current_user.has_feature_flag?('ghost_tables')
      # this should be removed from there once we have the table triggers enabled in cartodb-postgres extension
      # test if there is a job already for this
      if !current_user.link_ghost_tables_working
        ::Resque.enqueue(::Resque::UserJobs::SyncTables::LinkGhostTables, current_user.id)
      end
    end
  end
```

Not all users have `ghost_tables` feature flag active, so they won't see their tables linked by doing the normal things (refreshing dashboard, for example).

This poses an issue for 2 reasons:
1) I'm not sure about returning `true` on `current_user.present?`, seems error prone
2) Should we keep `ghost_tables` feature flag? should we remove it?

Do you know anything about this feature flag, @juanignaciosl ?

**Comment by iriberri** [comment] 2015-11-25 13:53
Hmmm I thought that the `ghost_tables` flag was applied for everybody already.

**Comment by gfiorav** [comment] 2015-11-25 13:55
@iriberri I created a user in staging (with master deployed) and it wasn't! Maybe some issue in user creation?

**Comment by juanignaciosl** [comment] 2015-11-25 14:21
![screen shot 2015-11-25 at 15 20 37](https://cloud.githubusercontent.com/assets/932968/11399493/1c5c34be-9388-11e5-9060-46ac341924cf.png)

Ghost tables flag is public, everybody has it. It's been kept as a safety measure for those moments we need to disable it.

**Comment by juanignaciosl** [comment] 2015-11-25 14:22
1) "I'm not sure about returning true on current_user.present?, seems error prone"

Not error prone but defensive. What error do you think it might cause?

**Comment by gfiorav** [comment] 2015-11-25 15:40
@juanignaciosl After your explanation, it's clear that this is not a "left over". No problems with that :smile: 

I'm back to reproducing this problem.

**Comment by gfiorav** [comment] 2016-04-08 15:09
Closed via https://github.com/CartoDB/cartodb/pull/7037

**Closed** 2016-04-08 15:10 UTC
Labels: bug, ghost-tables
