### ISSUE TITLE
When trying to export a dataset from a query it does not return results

### ISSUE THREAD

**Issue by jatorre** [CartoDB/cartodb#3450] opened 2015-04-30 17:30 UTC
I have a table called geocodes. I go to the SQL view and enter the following SQL:

SELECT * FROM geocodes limit 100000

I click on Edit/Export/CSV and I get back my 10000 records as I wanted.

Now if I enter this SQL

SELECT *,st_x(the_geom) as lon,st_y(the_geom) as lat FROM geocodes limit 100000

And try to export, I get an empty file with just the headers, when I was expecting to get the same 10000 results bu with two extra columns.

This is a regression I believe.

Adding @rochoa as I guess is an API problem, but adding also @javisantana FYI

**Comment by jatorre** [comment] 2015-04-30 17:34
And trying to get a "Table from query" also seems to be broken. Not sure if related.

Same query just clicking

Edit/Dataset from Query

Gives me back:

![screen shot 2015-04-30 at 1 33 28 pm](https://cloud.githubusercontent.com/assets/127803/7418670/965cc674-ef3d-11e4-9025-ecf4feea5196.png)

**Comment by jatorre** [comment] 2015-04-30 17:38
And also, through the SQL API I was able to perform the operation and it worked.

https://geocoding-cache.cartodb.com/api/v2/sql?format=csv&api_key=xxxx&q=SELECT cartodb_id,geocode_string,st_x(the_geom) as lon,st_y(the_geom) as lat FROM geocodes limit 100000

**Comment by jatorre** [comment] 2015-04-30 17:40
No, actually I was not able to do it neither on the SQL API with

https://geocoding-cache.cartodb.com/api/v2/sql?format=csv&api_key=xxx&q=SELECT cartodb_id,geocode_string,st_x(the_geom) as lon,st_y(the_geom) as lat FROM geocodes limit 100000

But with less records it seemed to work, so now I am really confused.

**Comment by rochoa** [comment] 2015-05-11 13:18
What is the schema definition for that table?

**Comment by rochoa** [comment] 2015-05-27 13:15
The problem is due `the_geom` column containing geometries not accepted by `st_x` function, for instance `MULTILINESTRING`.

The SQL API should return an error instead of returning an empty csv file with just the headers, that issue will be addressed in https://github.com/CartoDB/CartoDB-SQL-API/issues/227

Anyway as the query will result in a bad request once that issue fixed the best approach here is to filter by geometry type to be sure st_x only gets accepted geometries.

**Closed by rochoa** 2015-05-27 13:15 UTC
Labels: bug
