### ISSUE TITLE
Layer ordering is disconnected from visualization and layer selector

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10107] opened 2016-10-10 12:03 UTC
This behaviour does not happen always, so I was not able to replicate a clear pattern/steps. But basically sometimes changing the layers order (from a three layers map) has not effect on the layers selector and visualisation.

**Comment by xavijam** [comment] 2016-10-10 12:14
Already talked with @ramiroaznar offline, closing since there is no steps to reproduce. 💋  thanks mate.

**Closed by xavijam** 2016-10-10 12:14 UTC
Labels: bug, Builder
