### ISSUE TITLE
Remove old modals code

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4840] opened 2015-08-03 11:03 UTC
And also check what libraries are not used anymore, as in:

jquery.fileupload-fp.js
jquery.fileupload.js
jquery.fileupload-ui.js
...

**Comment by viddo** [comment] 2015-08-06 08:04
duplicate of #4673, moved the comment regarding old, potentially unused libs there

**Closed by viddo** 2015-08-06 08:04 UTC
Labels: enhancement, Frontend
