### ISSUE TITLE
Error creating points in a map from an empty table : branch cache-geometry-types

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/cartodb#2206] opened 2015-02-12 12:18 UTC
In this [branch](https://github.com/CartoDB/cartodb/pull/2165) , I can't create several points.

The steps are:
1. create an empty table
2. go to map
3. create a point
4. create another point..and if fails with : `Uncaught TypeError: undefined is not a function``
The line is :
> this.drawer = new d[b]({mapview: this.mapView}), this.drawer.start();

 (in createGeom function)

![bug_creating_points](https://cloud.githubusercontent.com/assets/3958416/6167170/9fbfcb4c-b2b8-11e4-9dbe-7163fdac8416.gif)

Stack:
```
Uncaught TypeError: undefined is not a functiontable.                                   table.js:29 
cdb.admin.GeometryEditor.cdb.core.View.extend.createGeom                      table.js:29
cdb.admin.MapTab.cdb.core.View.extend._addGeometry                              table.js:33 
a.Events.trigger                                                                                                cdb.js:4 
cdb.admin.LayerPanelView.cdb.admin.RightMenu.extend._addGeometry     table.js:32 
cdb.admin.LayerPanelView.cdb.admin.RightMenu.extend._addFeature        table.js:32
a.Events.trigger                                                                                                cdb.js:4 
cdb.core.View.extend.click                                                                               table.js:24
J.event.dispatch                                                                                               cdb.js:2 
J.event.add.g.handle.h                                                                                    cdb.js:2
```
![screen shot 2015-02-12 at 14 31 57](https://cloud.githubusercontent.com/assets/3958416/6168283/28f15114-b2c4-11e4-910a-7f525439ff63.png)

**Comment by rafatower** [comment] 2015-02-12 13:50
I could not reproduce it locally. I think we saw the effect of having js code from master mixed with rails code from cache-geometry-types.

I updated the version number of javascript in https://github.com/CartoDB/cartodb/commit/b0ab231427b727831cf587ea26e8309ce8cef022

**Comment by javisantana** [comment] 2015-02-12 13:51
i can't reproduce it neither, closing

**Closed by javisantana** 2015-02-12 13:51 UTC
Labels: bug
