### ISSUE TITLE
AOI buffers disappear after running a second analysis

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#9042] opened 2016-07-21 09:15 UTC
### Steps

I have encountered a couple of issues while replicating the 2nd demo @cartodave made in #the-retraining:

- Create a map with points dataset (`layer1`).
- Run AOI analysis in `layer1`.

![aoi1](https://cloud.githubusercontent.com/assets/5215798/17017453/a8e78098-4f33-11e6-9547-8f363892582a.png)

- Continue the workflow analysis in `layer1`. This time "Enrich from DO". I select `United States` as COUNTRY, `Transportation` as MEASUREMENT and `Commuters by Subway or Elevated` as SEGMENTS.

![aoi2](https://cloud.githubusercontent.com/assets/5215798/17017527/f6d4e62e-4f33-11e6-9a1b-92486ceb5ca8.png)

- The buffers disappear. In addition, the values from the DO are really low. According to @AbelVM it is because the values are normalized. But another explanation could be that the second analysis is using the point geometry instead of the buffer geometry to extract the DO data.

![commuters](https://cloud.githubusercontent.com/assets/5215798/17017633/644d2c52-4f34-11e6-9944-9cb3af422979.png)

**Comment by saleiva** [comment] 2016-07-21 09:23
as you see, the geometries are still polygons so this looks as a bug with the cache of layers and the style we apply.

**Comment by saleiva** [comment] 2016-07-21 09:23
Does this happen always?

**Comment by ramiroaznar** [comment] 2016-07-21 09:35
It always happens with "Enrich with DO" analysis.

**Comment by saleiva** [comment] 2016-07-21 10:29
@xavijam feel free to assign to @viddo with priority tho...

**Comment by saleiva** [comment] 2016-07-25 15:27
Happening to me as well when doing an "Intersect with second layer" analysis in a polygon layer with a previously analized points layer. As soon as you any property on the style form on the polygons layer, they get correctly rendered as polygons 

cc/ @javisantana

**Comment by talos** [comment] 2016-07-25 19:29
The really low column values were a result of numbers being calculated per sq m instead of per sq km.  This should be resolved now.

**Comment by talos** [comment] 2016-07-25 19:44
Also want to flag https://github.com/CartoDB/dataservices-api/pull/237 here, as once that's merged then we'll get different numbers again for polygon measures -- the absolute number instead of a rate per sq km.  This is the original intended behavior, but there were several layers of problems thus the back and forth.

**Comment by javisantana** [comment] 2016-07-26 12:17
ok, several things here:

- hey, I can't reproduce with my datasets, could you send the .carto so I can check?
- I think DO analysis should have an option to normalize by pop at UI level cc @saleiva

**Comment by ramiroaznar** [comment] 2016-07-26 12:58
@javisantana Sent it via slack.

**Comment by saleiva** [comment] 2016-07-26 13:33
@javisantana the original design contains a denominator.
also AFAIK, for polygons those variables come up already normalized by sqkm

**Comment by talos** [comment] 2016-07-26 14:49
@saleiva that's actually in error.  The documentation says we should normalize by sq km for points, but have absolute values for polygons.  This is a known issue documented here (https://github.com/CartoDB/dataservices-api/issues/235) that will be resolved by https://github.com/CartoDB/dataservices-api/pull/237 when deployed.

**Comment by talos** [comment] 2016-07-26 14:49
And 👍 surfacing the normalize by denominator option!

**Comment by viddo** [comment] 2016-07-27 15:16
Been debugging @ramiroaznar's map together with @javisantana , what we found was that when the maps API returns status "ready", and as such we do a lookup of the data to get the geometry type, the SQL API call returns no data even if there should be. If checking a moment later the data is there, so definitely a race condition. Seems like the maps API returns ready too early, so fixing that should fix this issue.

There's also a 2nd issue, which is that we should probably not set `simple` styles if a geometry is not found, so will change that separately.

**Comment by talos** [comment] 2016-07-27 15:20
Ah, a 🐞 inside of a 🐞 ... just had one of those last week.  Glad to hear this should be resolvable so easily.

**Comment by javisantana** [comment] 2016-07-28 14:25
cc @rochoa read the last @viddo comment. My guess is it only happens on SaaS so it's likely a race condition thing. It's easily reproducible with the steps provided and this carto https://cartoteam.slack.com/files/ramiro/F1V4VHYCB/subwaystations_map__on_2016-07-26_at_12.58.07_.carto

**Comment by rochoa** [comment] 2016-08-01 17:08
I see queries to the SQL API to retrieve the geometry type before the node is set to `ready` status. Furthermore, those tables are not being cached, if you check the response headers you see `X-Cache:MISS`. I see the client is sending a cache_buster param to avoid being cached, but that should not be needed since https://github.com/CartoDB/CartoDB-SQL-API/pull/330.

Does the client cache the geometry type at any time?

**Comment by viddo** [comment] 2016-08-02 08:36
> I see the client is sending a cache_buster param to avoid being cached, but that should not be needed since CartoDB/CartoDB-SQL-API#330.

The cache bust was added as a temporary solution (#8749), I've created a separate issue to have it 🔥 then 👉  #9217

> Does the client cache the geometry type at any time?

No, not yet, it's planned to be done soon enough though 👉  #8827

**Comment by viddo** [comment] 2016-08-02 10:26
Debugged with @rochoa in-person:

> I see queries to the SQL API to retrieve the geometry type before the node is set to ready status. 

This was a false lead, separate request done by the [table-view](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/components/table/table-view.js#L116-L121). it has not affect on how the layer is rendered though.

Anyway, @javisantana @ramiroaznar we can't reproduce the issue anymore, and unfortunately we're not sure why. 😕  For now we'll close it, feel free to re-open if this happens again (and hopefully have some more data/STR to go on).

Note that an exported .carto file that have undesired layer styles (as the one sent offline for this issue) will always render the things wrong, removing/adding a node will update the styles accordingly though.

**Closed by viddo** 2016-08-02 10:26 UTC
Labels: Analysis, bug, Builder
