### ISSUE TITLE
Filter by widget is waiting...

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#12385] opened 2017-06-26 13:30 UTC
If the analysis is cached it's works but if i try one new it doesn't work

https://team.carto.com/u/piensaenpixel/builder/f4e8ff3f-ec3d-4cbc-8945-7121454e86e3/embed

If i filter by 'Carabanchel' it works but, for example Suanzes it doesn't 

[Línea 5 (on 2017-06-26 at 13.23.44).carto.zip](https://github.com/CartoDB/cartodb/files/1102228/Linea.5.on.2017-06-26.at.13.23.44.carto.zip)

**Comment by javisantana** [comment] 2017-06-28 15:25
The issue is:
1) add a a points table
2) add a AIO (500m)
3) add data obs analysis with 

add a filter to source node and filter by something.

"data obs" analysis gets stuck but going to the database there is no query running for that user.

If you remove the AIO analysis works (with points)

**Comment by ramiroaznar** [comment] 2017-10-02 16:33
Hey @piensaenpixel the filters are working on the embed. I was not able to import the .carto file? It says the file is not supported. Can you test it again to check if the issue has been fixed?

**Comment by ramiroaznar** [comment] 2017-11-15 10:24
Closing this, both the embed map and the map from the .carto are working fine.

**Closed by ramiroaznar** 2017-11-15 10:24 UTC
Labels: bug
