### ISSUE TITLE
Add the option to create layer from source without analysis

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#8231] opened 2016-06-27 13:24 UTC
If I want to create a new layer from the node B0 **without adding a new analysis**

![selection_008](https://cloud.githubusercontent.com/assets/9017165/16381033/c5622c4e-3c7a-11e6-8a2d-2bc4aa2889ca.png)

I drag'n'drop the node, but then, I get a new layer pointing to a new node C0 instead of my original B0!!

![selection_009](https://cloud.githubusercontent.com/assets/9017165/16381048/e1cbd376-3c7a-11e6-92de-83f33e4e0c32.png)

But, If I add an analysis, and then create the layer

![selection_010](https://cloud.githubusercontent.com/assets/9017165/16381081/0b0407cc-3c7b-11e6-8252-824f351e6339.png)

cc @xavijam

**Comment by saleiva** [comment] 2016-06-27 13:33
Well, this is not a bug, it's a feature
we will have an analysis for linking layers, so closing :)

**Comment by saleiva** [comment] 2016-06-27 13:34
Sorry I commented in the wrong place. Reoppening.
Actual behaviour should be able by just duplicating a layer.

**Comment by viddo** [comment] 2016-06-27 13:35
> Actual behaviour should be able by just duplicating a layer.

Including styles, popup etc.?

**Comment by saleiva** [comment] 2016-06-27 13:37
When clicking on Duplicate layer (under the layer options when available) yes.
What abel is saying is different, just adding a layer as a datasource for another layer.

**Comment by AbelVM** [comment] 2016-06-27 13:45
Use case: two layers from the same source node, one with one style and the other with an aggregated style, but you want to link your widgets to the node behind, so both layers are filtered at the same time

**Comment by saleiva** [comment] 2016-06-27 14:40
ha! I was first - https://github.com/CartoDB/cartodb/issues/8132

**Closed** 2016-07-13 16:00 UTC
Labels: Builder, enhancement
