### ISSUE TITLE
Adding/removing widgets when having Time Series

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#12402] opened 2017-06-28 16:35 UTC
### Context
When you delete existing widgets when having a Time Series, the TS bar grows horizontally but without the histogram

### Steps to Reproduce

1. Create a map
2. Add few widgets
3. Add TS Widget
4. Delete all widgets except the TS one

### Current Result
![bug](https://user-images.githubusercontent.com/596509/27648732-bd834d0c-5c2f-11e7-8abe-1351a4f87e4e.gif)

---

### Context
When you have a Time Series widget added and you try to add some others widgets from scratch

### Steps to Reproduce

1. Create a map
2. Add TS Widget
3. Add few widgets
4. Widgets may not appear until you refresh the page

### Current Result
![bug2](https://user-images.githubusercontent.com/596509/27648874-4a4edef4-5c30-11e7-8676-60cfc7310de0.gif)

**Comment by rjimenezda** [comment] 2017-06-28 16:41
Tip: if you resize the page, it 'solves' the problem.

**Comment by xavijam** [comment] 2017-06-28 17:01
I feel this issue has already been reported, but in any case you have reported with the new "handlers" thing but happens in production right now.

**Comment by rjimenezda** [comment] 2017-07-03 15:31
Possible duplicate of #12123

**Comment by ivanmalagon** [comment] 2017-07-11 10:29
While developing another issue, we ran into this and the reason seems that autostyle is enabled by default, but the model lacks some color information so it breaks.

It breaks in function `_generateFillGradients` of `chart.js`

**Comment by xavijam** [comment] 2017-08-08 09:56
Closing it because, as @rjimenezda mentioned, it is duplicated with https://github.com/CartoDB/cartodb/issues/12123. 💋  thanks @josecruz

**Closed by xavijam** 2017-08-08 09:56 UTC
Labels: bug, Frontend

**Comment by Jesus89** [comment] 2017-08-28 10:21
Duplicated: #12655
