### ISSUE TITLE
Import mail notifier raises an exception when creating tables from queries

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#6502] opened 2016-02-02 08:30 UTC
The stacktrace is:

````
2016-02-02 08:01:58 UTC: Running on server xxx.xxx.xx.xxx with PID: 21329
2016-02-02 08:01:58 UTC: from_table()
2016-02-02 08:01:58 UTC: import_from_query()
2016-02-02 08:03:59 UTC: migrate_existing()
2016-02-02 08:03:59 UTC: Table valid
2016-02-02 08:05:01 UTC: Table 'buildings_time_copy_5' registered
2016-02-02 08:05:01 UTC: After dispatch
2016-02-02 08:05:01 UTC: Import finished

2016-02-02 08:05:01 UTC: Exception: no implicit conversion of nil into String
2016-02-02 08:05:01 UTC: ["/home/ubuntu/www/production.cartodb.com/releases/xxxx/services/importer/lib/importer/mail_notifier.rb:58:in `basename'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/mail_notifier.rb:58:in `extract_file_names'", "/home/ubuntu/www/production.cartodb.com/releases/xxxx/services/importer/lib/importer/mail_notifier.rb:31:in `send!'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/mail_notifier.rb:18:in `notify_if_needed'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/app/models/data_import.rb:812:in `notify'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/app/models/data_import.rb:298:in `handle_success'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/app/models/data_import.rb:191:in 
2016-02-02 08:05:01 UTC: ERROR!

2016-02-02 08:05:01 UTC: Exception: no implicit conversion of nil into String
2016-02-02 08:05:01 UTC: ["/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/mail_notifier.rb:58:in `basename'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/mail_notifier.rb:58:in `extract_file_names'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/mail_notifier.rb:31:in `send!'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/services/importer/lib/importer/mail_notifier.rb:18:in `notify_if_needed'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/app/models/data_import.rb:812:in `notify'", "/home/ubuntu/www/production.cartodb.com/releases/xxx/app/models/data_import.rb:330:in `handle_failure'", 
===LOG END===
````

The import is taking [more than three minutes](https://github.com/CartoDB/cartodb/blob/8def2492b26c50984dff80bf82e2a57bfb089318/services/importer/lib/importer/mail_notifier.rb#L21) so the notifier is acting, and [here](https://github.com/CartoDB/cartodb/blob/8def2492b26c50984dff80bf82e2a57bfb089318/services/importer/lib/importer/mail_notifier.rb#L58), `service_item_id` seems to be nil at the results.

**Comment by rafatower** [comment] 2016-02-29 10:36
@ethervoid I think this is a duplicate of another issue. Can you please reference it that is the case?

**Comment by ethervoid** [comment] 2016-03-01 13:44
Is referenced by @iriberri above #6296

**Comment by rafatower** [comment] 2016-03-01 15:40
closing as duplicate

(sorry about the noise. let's try not to create duplicates, which sometimes is hard)

**Closed by rafatower** 2016-03-01 15:40 UTC
Labels: Data-services
