### ISSUE TITLE
Import error: CDB(_CDB_Rewrite_Table:42P07:relation "file_name" already exists)

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#5407] opened 2015-09-07 09:07 UTC
When user tries to import a CSV file to his/her account, it appears the next error: 
 CDB(_CDB_Rewrite_Table:42P07:relation "file_name" already exists)

cc @iriberri @rafatower

**Comment by rafatower** [comment] 2015-09-07 09:43
@oriolbx any instructions to reproduce the issue? this is not the common scenario. Importing from UI or from ogr2ogr?

**Comment by iriberri** [comment] 2015-09-10 09:05
Import error ID: `a5cd285e-01c1-4e05-9d4b-21e8a14537c3`

Will keep updating.

**Comment by rafatower** [comment] 2015-09-10 09:15
Most likely related to this: https://github.com/CartoDB/cartodb-postgresql/pull/127
as duplicate seq name can be generated as indices where. I'll double-check whether this is fixed or still broken. Thanks for the details

**Comment by iriberri** [comment] 2015-09-10 12:49
I just found a new one without the sequence thing:

````
2015-09-10 12:48:22 UTC: Exception: PG::Error: ERROR:  CDB(_CDB_Rewrite_Table:42P07:relation "community_connections_program_100_gigabit_speed_google_fiber_1_" already exists): CREATE TABLE iriberri.community_connections_program_100_gigabit_speed_google_fiber_1_a9a9885d7c72ed4225e4
````

By importing: https://data.austintexas.gov/Geodata/Community-Connections-Program-100-Gigabit-Speed-Go/ysrd-25kv as CSV

**Comment by iriberri** [comment] 2015-09-10 12:50
I just renamed the file to "reduced.csv" and it worked. It's the first time I tried to upload that table to my account, so I don't have any table with the same name.

**Comment by iriberri** [comment] 2015-09-10 12:52
SB/6573507

**Comment by rafatower** [comment] 2015-09-10 13:16
That one is due to the 63 char limit, so at least it is easy to reproduce and locate in the code. Thanks for the follow-up

**Comment by rafatower** [comment] 2015-09-30 08:06
Fixed in the extension. I believe there's another ticket for the 63 char limit, otherwise it needs to be created.

**Closed by rafatower** 2015-09-30 08:06 UTC
Labels: 0 - Backlog, bug, cartodbfy
