### ISSUE TITLE
Style issues with the login page of an organization

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#11272] opened 2017-01-17 09:57 UTC
The login page of an organization shows some minor problems:

1. The GitHub button hover style doesn't look ok: the title disappears (see the animated gif below).
2. The "Sign up here" link points to `carto.com/signup` instead of the organization signup page.
3. Check that the "Please, use an email address belonging to this organization." message displays when username/password auth is disabled.

![login](https://cloud.githubusercontent.com/assets/4933/22015738/8c07cb2e-dca3-11e6-86cc-4949a7e1c784.gif)

**Comment by xavijam** [comment] 2017-01-17 09:58
cc @juanignaciosl and @saleiva

**Comment by saleiva** [comment] 2017-01-17 23:05
It's easy so I'd prioritize

**Comment by ramiroaznar** [comment] 2017-11-07 11:00
1. Not happening anymore. The only org that has Github option on the login website is `team` and the hovering is working well.
2. I think this is an expected behavior because no org has a signup web (but `team`).
3. Not happening anymore.

@noguerol should we close this?

**Closed** 2017-11-07 11:20 UTC
Labels: bug, Frontend, Next
